/*
This file is part of Giswater 3
The program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This version of Giswater is provided by Giswater Association
*/



SET search_path = "SCHEMA_NAME", public, pg_catalog;


--FILL config_web_fields TABLE
------------------------------

INSERT INTO config_web_fields VALUES (51, 'review_connec', 'arc_type', NULL, 'string', 18, NULL, '', 'arc_type', 'combo', 'arc_type', 'id', 'id', NULL, true, 5);
INSERT INTO config_web_fields VALUES (81, 'F24', 'value', NULL, 'double', 12, NULL, '0.00', 'Value', 'text', NULL, NULL, NULL, NULL, true, 4);
INSERT INTO config_web_fields VALUES (85, 'F24', 'value1', NULL, 'double', NULL, NULL, '0.00', 'value1', 'text', NULL, NULL, NULL, NULL, true, 5);
INSERT INTO config_web_fields VALUES (52, 'review_connec', 'shape', NULL, 'string', 30, NULL, '', 'shape', 'combo', 'cat_arc_shape', 'id', 'id', NULL, true, 6);
INSERT INTO config_web_fields VALUES (53, 'review_connec', 'geom1', NULL, 'double', 12, 3, '0.00', 'geom1', 'text', NULL, NULL, NULL, NULL, true, 7);
INSERT INTO config_web_fields VALUES (86, 'F24', 'value2', NULL, 'double', NULL, NULL, '0.00', 'value2', 'text', NULL, NULL, NULL, NULL, true, 6);
INSERT INTO config_web_fields VALUES (98, 'v_edit_man_chamber', 'chamber_ymax', NULL, 'double', 12, 3, '0.00', 'Ymax', 'text', NULL, NULL, NULL, NULL, true, 3);
INSERT INTO config_web_fields VALUES (82, 'F24', 'geom1', NULL, 'double', NULL, NULL, '0.00', 'Geom1', 'text', NULL, NULL, NULL, NULL, true, 7);
INSERT INTO config_web_fields VALUES (54, 'review_connec', 'geom2', NULL, 'double', 12, 3, '0.00', 'geom2', 'text', NULL, NULL, NULL, NULL, true, 8);
INSERT INTO config_web_fields VALUES (55, 'review_connec', 'annotation', NULL, 'string', 500, NULL, '', 'annotation', 'textarea', NULL, NULL, NULL, NULL, true, 9);
INSERT INTO config_web_fields VALUES (83, 'F24', 'geom2', NULL, 'double', NULL, NULL, '0.00', 'Geom2', 'text', NULL, NULL, NULL, NULL, true, 8);
INSERT INTO config_web_fields VALUES (56, 'review_connec', 'observ', NULL, 'string', 500, NULL, '', 'observ', 'textarea', NULL, NULL, NULL, NULL, true, 10);
INSERT INTO config_web_fields VALUES (84, 'F24', 'geom3', NULL, 'double', NULL, NULL, '0.00', 'Geom3', 'text', NULL, NULL, NULL, NULL, true, 9);
INSERT INTO config_web_fields VALUES (1, 'review_arc', 'sys_id', NULL, 'string', 16, NULL, '', 'arc_id', 'text', NULL, NULL, NULL, NULL, false, 1);
INSERT INTO config_web_fields VALUES (57, 'review_connec', 'field_checked', NULL, 'boolean', NULL, NULL, 'FALSE', 'field_checked', 'checkbox', NULL, NULL, NULL, NULL, true, 11);
INSERT INTO config_web_fields VALUES (59, 'review_gully', 'sys_id', NULL, 'string', 16, NULL, '', 'arc_id', 'text', NULL, NULL, NULL, NULL, false, 1);
INSERT INTO config_web_fields VALUES (60, 'review_gully', 'gratecat_id', NULL, 'string', 30, NULL, '', 'gratecat_id', 'combo', 'cat_grate', 'id', 'id', NULL, true, 3);
INSERT INTO config_web_fields VALUES (62, 'review_gully', 'matcat_id', NULL, 'string', 18, NULL, '', 'matcat_id', 'combo', 'cat_mat_arc', 'id', 'id', NULL, true, 5);
INSERT INTO config_web_fields VALUES (87, 'F24', 'text', NULL, 'string', NULL, NULL, '', 'Text', 'textarea', NULL, NULL, NULL, NULL, true, 10);
INSERT INTO config_web_fields VALUES (63, 'review_gully', 'shape', NULL, 'string', 30, NULL, '', 'shape', 'combo', 'cat_arc_shape', 'id', 'id', NULL, true, 6);
INSERT INTO config_web_fields VALUES (94, 'F22', 'parameter_id', NULL, 'string', 30, NULL, 'parameter', 'Parameter_id', 'text', NULL, NULL, NULL, NULL, true, 1);
INSERT INTO config_web_fields VALUES (182, 'v_edit_man_chamber', 'node_id', NULL, 'string', 16, NULL, NULL, 'Node id', 'text', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_web_fields VALUES (100, 'v_edit_man_chamber', 'node_type', NULL, 'string', 30, NULL, NULL, 'Node type', 'combo', 'node_type', 'id', 'id', NULL, true, 5);
INSERT INTO config_web_fields VALUES (2, 'review_arc', 'y1', NULL, 'double', 12, 3, '0.00', 'y1', 'text', NULL, NULL, NULL, NULL, true, 2);
INSERT INTO config_web_fields VALUES (95, 'F23', 'parameter_id', NULL, 'string', NULL, NULL, 'parameter', 'Parameter_id', 'text', NULL, NULL, NULL, NULL, true, 1);
INSERT INTO config_web_fields VALUES (90, 'F23', 'position_id', NULL, 'string', NULL, NULL, '', 'Position id', 'combo', NULL, NULL, NULL, NULL, true, 2);
INSERT INTO config_web_fields VALUES (64, 'review_gully', 'geom1', NULL, 'double', 12, 3, '0.00', 'geom1', 'text', NULL, NULL, NULL, NULL, true, 7);
INSERT INTO config_web_fields VALUES (91, 'F23', 'position_value', NULL, 'double', NULL, NULL, '', 'Position value', 'text', NULL, NULL, NULL, NULL, true, 3);
INSERT INTO config_web_fields VALUES (3, 'review_arc', 'y2', NULL, 'double', 12, 3, '0.00', 'y2', 'text', NULL, NULL, NULL, NULL, true, 3);
INSERT INTO config_web_fields VALUES (4, 'review_arc', 'arc_type', NULL, 'string', 18, NULL, '', 'arc_type', 'combo', 'arc_type', 'id', 'id', NULL, true, 4);
INSERT INTO config_web_fields VALUES (5, 'review_arc', 'matcat_id', NULL, 'string', 30, NULL, '', 'matcat_id', 'combo', 'cat_mat_arc', 'id', 'id', NULL, true, 5);
INSERT INTO config_web_fields VALUES (6, 'review_arc', 'shape', NULL, 'string', 30, NULL, '', 'shape', 'combo', 'cat_arc_shape', 'id', 'id', NULL, true, 6);
INSERT INTO config_web_fields VALUES (7, 'review_arc', 'geom1', NULL, 'double', 12, 3, '0.00', 'geom1', 'text', NULL, NULL, NULL, NULL, true, 7);
INSERT INTO config_web_fields VALUES (11, 'review_arc', 'field_checked', NULL, 'boolean', NULL, NULL, 'FALSE', 'field_checked', 'checkbox', NULL, NULL, NULL, NULL, true, 11);
INSERT INTO config_web_fields VALUES (68, 'review_gully', 'field_checked', NULL, 'boolean', NULL, NULL, 'FALSE', 'field_checked', 'checkbox', NULL, NULL, NULL, NULL, true, 11);
INSERT INTO config_web_fields VALUES (70, 'review_gully', 'groove', NULL, 'boolean', NULL, NULL, 'FALSE', 'groove', 'checkbox', NULL, NULL, NULL, NULL, true, 13);
INSERT INTO config_web_fields VALUES (71, 'review_gully', 'siphon', NULL, 'boolean', NULL, NULL, 'FALSE', 'siphon', 'checkbox', NULL, NULL, NULL, NULL, true, 14);
INSERT INTO config_web_fields VALUES (73, 'review_gully', 'featurecat_id', NULL, 'string', 30, NULL, '', 'featurecat_id', 'combo', 'cat_feature', 'id', 'id', NULL, true, 15);
INSERT INTO config_web_fields VALUES (14, 'review_node', 'ymax', NULL, 'double', 12, 3, '0.00', 'ymax', 'text', NULL, NULL, NULL, NULL, true, 3);
INSERT INTO config_web_fields VALUES (92, 'F23', 'value', NULL, 'double', NULL, NULL, '0.00', 'value', 'text', NULL, NULL, NULL, NULL, true, 4);
INSERT INTO config_web_fields VALUES (93, 'F23', 'text', NULL, 'string', NULL, NULL, '', 'Text', 'textarea', NULL, NULL, NULL, NULL, true, 5);
INSERT INTO config_web_fields VALUES (88, 'F22', 'value', NULL, 'double', NULL, NULL, '0.00', 'value', 'text', NULL, NULL, NULL, NULL, true, 2);
INSERT INTO config_web_fields VALUES (89, 'F22', 'text', NULL, 'string', NULL, NULL, '', 'Text', 'textarea', NULL, NULL, NULL, NULL, true, 3);
INSERT INTO config_web_fields VALUES (78, 'F24', 'parameter_id', NULL, 'string', 30, NULL, 'parameter', 'Parameter_id', 'text', NULL, NULL, NULL, NULL, true, 1);
INSERT INTO config_web_fields VALUES (15, 'review_node', 'node_type', NULL, 'string', 18, NULL, '', 'node_type', 'combo', 'node_type', 'id', 'id', NULL, true, 4);
INSERT INTO config_web_fields VALUES (180, 'v_edit_man_conduit', 'conduit_builtdate', NULL, 'date', NULL, NULL, NULL, 'builtdate', 'date', NULL, NULL, NULL, NULL, true, 31);
INSERT INTO config_web_fields VALUES (16, 'review_node', 'matcat_id', NULL, 'string', 30, NULL, '', 'matcat_id', 'combo', 'cat_mat_node', 'id', 'id', NULL, true, 5);
INSERT INTO config_web_fields VALUES (17, 'review_node', 'shape', NULL, 'string', 30, NULL, '', 'shape', 'combo', 'cat_node_shape', 'id', 'id', NULL, true, 6);
INSERT INTO config_web_fields VALUES (22, 'review_node', 'field_checked', NULL, 'boolean', NULL, NULL, 'FALSE', 'field_checked', 'checkbox', NULL, NULL, NULL, NULL, true, 11);
INSERT INTO config_web_fields VALUES (47, 'review_connec', 'y1', NULL, 'double', 12, 3, '0.00', 'y1', 'text', NULL, NULL, NULL, NULL, true, 1);
INSERT INTO config_web_fields VALUES (48, 'review_connec', 'sys_id', NULL, 'string', 16, NULL, '', 'connec_id', 'text', NULL, NULL, NULL, NULL, false, 2);
INSERT INTO config_web_fields VALUES (49, 'review_connec', 'matcat_id', NULL, 'string', 30, NULL, '', 'matcat_id', 'combo', 'cat_mat_arc', 'id', 'id', NULL, true, 3);
INSERT INTO config_web_fields VALUES (50, 'review_connec', 'y2', NULL, 'double', 12, 3, '0.00', 'y2', 'text', NULL, NULL, NULL, NULL, true, 4);
INSERT INTO config_web_fields VALUES (79, 'F24', 'position_id', NULL, 'string', 30, NULL, '', 'Position id', 'combo', NULL, NULL, NULL, NULL, true, 2);
INSERT INTO config_web_fields VALUES (80, 'F24', 'position_value', NULL, 'double', 12, NULL, '0.00', 'Position value', 'text', NULL, NULL, NULL, NULL, true, 3);
INSERT INTO config_web_fields VALUES (102, 'v_edit_man_chamber', 'sector_id', NULL, 'string', NULL, NULL, NULL, 'Sector', 'combo', 'sector', 'sector_id', 'name', NULL, true, 7);
INSERT INTO config_web_fields VALUES (108, 'v_edit_man_chamber', 'dma_id', NULL, 'string', NULL, NULL, NULL, 'Dma', 'combo', 'dma', 'dma_id', 'name', NULL, true, 14);
INSERT INTO config_web_fields VALUES (107, 'v_edit_man_chamber', 'chamber_comment', NULL, 'string', 500, NULL, NULL, 'Comment', 'text', NULL, NULL, NULL, NULL, true, 13);
INSERT INTO config_web_fields VALUES (128, 'v_edit_man_chamber', 'verified', NULL, 'string', 50, NULL, NULL, 'Verified', 'combo', 'value_verified', 'id', 'id', NULL, true, 33);
INSERT INTO config_web_fields VALUES (181, 'v_edit_man_conduit', 'arc_id', NULL, 'string', 16, NULL, NULL, 'Arc id', 'text', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_web_fields VALUES (8, 'review_arc', 'geom2', NULL, 'double', 12, 3, '0.00', 'geom2', 'text', NULL, NULL, NULL, NULL, true, 8);
INSERT INTO config_web_fields VALUES (9, 'review_arc', 'annotation', NULL, 'string', 500, NULL, '', 'annotation', 'textarea', NULL, NULL, NULL, NULL, true, 9);
INSERT INTO config_web_fields VALUES (10, 'review_arc', 'observ', NULL, 'string', 500, NULL, '', 'observ', 'textarea', NULL, NULL, NULL, NULL, true, 10);
INSERT INTO config_web_fields VALUES (12, 'review_node', 'sys_id', NULL, 'string', 16, NULL, '', 'node_id', 'text', NULL, NULL, NULL, NULL, false, 1);
INSERT INTO config_web_fields VALUES (112, 'v_edit_man_chamber', 'chamber_fluid_type', NULL, 'string', 50, NULL, NULL, 'Fluid type', 'combo', 'man_type_fluid', 'fluid_type', 'fluid_type', 'SELECT * FROM man_type_fluid WHERE feature_type=''NODE'' AND (featurecat_id is null OR featurecat_id=''CHAMBER'');', true, 18);
INSERT INTO config_web_fields VALUES (13, 'review_node', 'top_elev', NULL, 'double', 12, 3, '0.00', 'top_elev', 'text', NULL, NULL, NULL, NULL, true, 2);
INSERT INTO config_web_fields VALUES (18, 'review_node', 'geom1', NULL, 'double', 12, 3, '0.00', 'geom1', 'text', NULL, NULL, NULL, NULL, true, 7);
INSERT INTO config_web_fields VALUES (19, 'review_node', 'geom2', NULL, 'double', 12, 3, '0.00', 'geom2', 'text', NULL, NULL, NULL, NULL, true, 8);
INSERT INTO config_web_fields VALUES (20, 'review_node', 'annotation', NULL, 'string', 500, NULL, '', 'annotation', 'textarea', NULL, NULL, NULL, NULL, true, 9);
INSERT INTO config_web_fields VALUES (21, 'review_node', 'observ', NULL, 'string', 500, NULL, '', 'observ', 'textarea', NULL, NULL, NULL, NULL, true, 10);
INSERT INTO config_web_fields VALUES (58, 'review_gully', 'top_elev', NULL, 'double', 12, 3, '0.00', 'top_elev', 'text', NULL, NULL, NULL, NULL, true, 2);
INSERT INTO config_web_fields VALUES (61, 'review_gully', 'ymax', NULL, 'double', 12, 3, '0.00', 'ymax', 'text', NULL, NULL, NULL, NULL, true, 4);
INSERT INTO config_web_fields VALUES (65, 'review_gully', 'geom2', NULL, 'double', 12, 3, '0.00', 'geom2', 'text', NULL, NULL, NULL, NULL, true, 8);
INSERT INTO config_web_fields VALUES (66, 'review_gully', 'annotation', NULL, 'string', 500, NULL, '', 'annotation', 'textarea', NULL, NULL, NULL, NULL, true, 9);
INSERT INTO config_web_fields VALUES (67, 'review_gully', 'observ', NULL, 'string', 500, NULL, '', 'observ', 'textarea', NULL, NULL, NULL, NULL, true, 10);
INSERT INTO config_web_fields VALUES (69, 'review_gully', 'sandbox', NULL, 'double', 12, 3, '0.00', 'sandbox', 'text', NULL, NULL, NULL, NULL, true, 12);
INSERT INTO config_web_fields VALUES (74, 'review_gully', 'feature_id', NULL, 'string', 16, NULL, '', 'feature_id', 'text', NULL, NULL, NULL, NULL, true, 16);
INSERT INTO config_web_fields VALUES (136, 'v_edit_man_chamber', 'chamber_bottom_channel', NULL, 'boolean', NULL, NULL, NULL, 'Bottom channel', 'checkbox', NULL, NULL, NULL, NULL, true, 40);
INSERT INTO config_web_fields VALUES (119, 'v_edit_man_chamber', 'chamber_muni_id', NULL, 'string', NULL, NULL, NULL, 'Municipality', 'combo', 'ext_municipality', 'muni_id', 'name', NULL, true, 25);
INSERT INTO config_web_fields VALUES (113, 'v_edit_man_chamber', 'chamber_location_type', NULL, 'string', 50, NULL, NULL, 'Location type', 'combo', 'man_type_location', 'location_type', 'location_type', 'SELECT * FROM man_type_location WHERE feature_type=''NODE'' AND (featurecat_id is null OR featurecat_id=''CHAMBER'');', true, 19);
INSERT INTO config_web_fields VALUES (114, 'v_edit_man_chamber', 'chamber_workcat_id', NULL, 'string', 30, NULL, NULL, 'Work', 'combo', 'cat_work', 'id', 'id', NULL, true, 20);
INSERT INTO config_web_fields VALUES (115, 'v_edit_man_chamber', 'chamber_workcat_id_end', NULL, 'string', 30, NULL, NULL, 'Work end', 'combo', 'cat_work', 'id', 'id', NULL, true, 21);
INSERT INTO config_web_fields VALUES (117, 'v_edit_man_chamber', 'chamber_builtdate', NULL, 'date', NULL, NULL, NULL, 'Built date', 'date', NULL, NULL, NULL, NULL, true, 23);
INSERT INTO config_web_fields VALUES (118, 'v_edit_man_chamber', 'chamber_enddate', NULL, 'date', NULL, NULL, NULL, 'End date', 'date', NULL, NULL, NULL, NULL, true, 24);
INSERT INTO config_web_fields VALUES (131, 'v_edit_man_chamber', 'chamber_width', NULL, 'double', NULL, NULL, '0.00', 'Width', 'text', NULL, NULL, NULL, NULL, true, 35);
INSERT INTO config_web_fields VALUES (135, 'v_edit_man_chamber', 'chamber_inlet', NULL, 'boolean', NULL, NULL, NULL, 'Inlet', 'checkbox', NULL, NULL, NULL, NULL, true, 39);
INSERT INTO config_web_fields VALUES (137, 'v_edit_man_chamber', 'chamber_accessibility', NULL, 'string', 16, NULL, NULL, 'Accessibility', 'text', NULL, NULL, NULL, NULL, true, 41);
INSERT INTO config_web_fields VALUES (138, 'v_edit_man_chamber', 'chamber_name', NULL, 'string', 255, NULL, NULL, 'Name', 'text', NULL, NULL, NULL, NULL, true, 42);
INSERT INTO config_web_fields VALUES (139, 'v_edit_man_conduit', 'conduit_code', NULL, 'string', 15, NULL, NULL, 'Code', 'text', NULL, NULL, NULL, NULL, true, 1);
INSERT INTO config_web_fields VALUES (140, 'v_edit_man_conduit', 'conduit_y1', NULL, 'double', NULL, NULL, '0.00', 'conduit_y1', 'text', NULL, NULL, NULL, NULL, true, 2);
INSERT INTO config_web_fields VALUES (141, 'v_edit_man_conduit', 'conduit_y2', NULL, 'double', NULL, NULL, '0.00', 'conduit_y2', 'text', NULL, NULL, NULL, NULL, true, 3);
INSERT INTO config_web_fields VALUES (142, 'v_edit_man_conduit', 'conduit_custom_y1', NULL, 'double', NULL, NULL, '0.00', 'conduit_custom_y1', 'text', NULL, NULL, NULL, NULL, true, 4);
INSERT INTO config_web_fields VALUES (103, 'v_edit_man_chamber', 'state', NULL, 'string', NULL, NULL, NULL, 'State', 'combo', 'value_state', 'id', 'name', NULL, true, 8);
INSERT INTO config_web_fields VALUES (177, 'v_edit_man_conduit', 'expl_id', NULL, 'string', NULL, NULL, NULL, 'exploitation', 'combo', 'exploitation', 'expl_id', 'name', NULL, true, 16);
INSERT INTO config_web_fields VALUES (160, 'v_edit_man_conduit', 'conduit_soilcat_id', NULL, 'string', 30, NULL, NULL, 'soilcat', 'text', 'cat_soil', 'id', 'id', NULL, true, 23);
INSERT INTO config_web_fields VALUES (161, 'v_edit_man_conduit', 'conduit_function_type', NULL, 'string', 50, NULL, NULL, 'function type', 'text', 'man_type_function', 'function_type', 'function_type', 'SELECT * FROM man_type_function WHERE feature_type=''ARC'' AND (featurecat_id is null OR featurecat_id=''CONDUIT'');', true, 24);
INSERT INTO config_web_fields VALUES (174, 'v_edit_man_conduit', 'conduit_address_03', NULL, 'string', 250, NULL, NULL, 'address 3', 'text', NULL, NULL, NULL, NULL, true, 38);
INSERT INTO config_web_fields VALUES (175, 'v_edit_man_conduit', 'conduit_descript', NULL, 'string', 250, NULL, NULL, 'descript', 'text', NULL, NULL, NULL, NULL, true, 39);
INSERT INTO config_web_fields VALUES (104, 'v_edit_man_chamber', 'state_type', NULL, 'string', NULL, NULL, NULL, 'State type', 'combo', 'value_state_type', 'id', 'name', NULL, true, 9);
INSERT INTO config_web_fields VALUES (178, 'v_edit_man_conduit', 'conduit_num_value', NULL, 'double', NULL, NULL, '0.00', 'num value', 'text', NULL, NULL, NULL, NULL, true, 41);
INSERT INTO config_web_fields VALUES (159, 'v_edit_man_conduit', 'dma_id', NULL, 'string', NULL, NULL, NULL, 'dma', 'text', 'dma', 'dma_id', 'name', NULL, true, 22);
INSERT INTO config_web_fields VALUES (96, 'v_edit_man_chamber', 'chamber_code', NULL, 'string', 30, NULL, NULL, 'Code', 'text', NULL, NULL, NULL, NULL, true, 1);
INSERT INTO config_web_fields VALUES (97, 'v_edit_man_chamber', 'chamber_top_elev', NULL, 'double', 12, 3, '0.00', 'Top elev', 'text', NULL, NULL, NULL, NULL, true, 2);
INSERT INTO config_web_fields VALUES (99, 'v_edit_man_chamber', 'chamber_elev', NULL, 'double', 12, 3, '0.00', 'Elev', 'text', NULL, NULL, NULL, NULL, true, 4);
INSERT INTO config_web_fields VALUES (121, 'v_edit_man_chamber', 'chamber_streetaxis_id', NULL, 'string', 16, NULL, NULL, 'Street', 'combo', 'ext_streetaxis', 'id', 'name', NULL, true, 27);
INSERT INTO config_web_fields VALUES (179, 'v_edit_man_chamber', 'expl_id', NULL, 'string', NULL, NULL, NULL, 'exploitation', 'combo', 'exploitation', 'expl_id', 'name', NULL, true, 10);
INSERT INTO config_web_fields VALUES (101, 'v_edit_man_chamber', 'nodecat_id', NULL, 'string', 30, NULL, NULL, 'Nodecat', 'combo', 'cat_node', 'id', 'id', NULL, true, 6);
INSERT INTO config_web_fields VALUES (105, 'v_edit_man_chamber', 'chamber_annotation', NULL, 'string', 500, NULL, NULL, 'Annotation', 'text', NULL, NULL, NULL, NULL, true, 11);
INSERT INTO config_web_fields VALUES (106, 'v_edit_man_chamber', 'chamber_observ', NULL, 'string', 500, NULL, NULL, 'Observ', 'text', NULL, NULL, NULL, NULL, true, 12);
INSERT INTO config_web_fields VALUES (109, 'v_edit_man_chamber', 'chamber_soilcat_id', NULL, 'string', 30, NULL, NULL, 'Soilcat', 'combo', 'cat_soil', 'id', 'id', NULL, true, 15);
INSERT INTO config_web_fields VALUES (110, 'v_edit_man_chamber', 'chamber_function_type', NULL, 'string', 50, NULL, NULL, 'Function type', 'combo', 'man_type_function', 'function_type', 'function_type', 'SELECT * FROM man_type_function WHERE feature_type=''NODE'' AND (featurecat_id is null OR featurecat_id=''CHAMBER'');', true, 16);
INSERT INTO config_web_fields VALUES (111, 'v_edit_man_chamber', 'chamber_category_type', NULL, 'string', 50, NULL, NULL, 'Category type', 'combo', 'man_type_category', 'category_type', 'category_type', 'SELECT * FROM man_type_category WHERE feature_type=''NODE'' AND (featurecat_id is null OR featurecat_id=''CHAMBER'');', true, 17);
INSERT INTO config_web_fields VALUES (116, 'v_edit_man_chamber', 'chamber_buildercat_id', NULL, 'string', 30, NULL, NULL, 'Builder', 'combo', 'cat_builder', 'id', 'id', NULL, true, 22);
INSERT INTO config_web_fields VALUES (120, 'v_edit_man_chamber', 'chamber_ownercat_id', NULL, 'string', 150, NULL, NULL, 'Owner', 'combo', 'cat_owner', 'id', 'id', NULL, true, 26);
INSERT INTO config_web_fields VALUES (122, 'v_edit_man_chamber', 'epa_type', NULL, 'string', 30, NULL, NULL, 'Epa type', 'combo', 'inp_node_type', 'id', 'id', NULL, true, 28);
INSERT INTO config_web_fields VALUES (123, 'v_edit_man_chamber', 'chamber_address_01', NULL, 'string', 150, NULL, NULL, 'Address 1', 'text', NULL, NULL, NULL, NULL, true, 29);
INSERT INTO config_web_fields VALUES (124, 'v_edit_man_chamber', 'chamber_address_02', NULL, 'string', 150, NULL, NULL, 'Address 2', 'text', NULL, NULL, NULL, NULL, true, 30);
INSERT INTO config_web_fields VALUES (126, 'v_edit_man_chamber', 'chamber_descript', NULL, 'string', 256, NULL, NULL, 'Descript', 'text', NULL, NULL, NULL, NULL, true, 32);
INSERT INTO config_web_fields VALUES (125, 'v_edit_man_chamber', 'chamber_address_03', NULL, 'string', 150, NULL, NULL, 'Address 3', 'text', NULL, NULL, NULL, NULL, true, 31);
INSERT INTO config_web_fields VALUES (130, 'v_edit_man_chamber', 'chamber_length', NULL, 'double', NULL, NULL, '0.00', 'Length', 'text', NULL, NULL, NULL, NULL, true, 34);
INSERT INTO config_web_fields VALUES (132, 'v_edit_man_chamber', 'chamber_sander_depth', NULL, 'double', NULL, NULL, '0.00', 'Sander depth', 'text', NULL, NULL, NULL, NULL, true, 36);
INSERT INTO config_web_fields VALUES (133, 'v_edit_man_chamber', 'chamber_max_volume', NULL, 'double', NULL, NULL, '0.00', 'Max volume', 'text', NULL, NULL, NULL, NULL, true, 37);
INSERT INTO config_web_fields VALUES (134, 'v_edit_man_chamber', 'chamber_util_volume', NULL, 'double', NULL, NULL, '0.00', 'Util volume', 'text', NULL, NULL, NULL, NULL, true, 38);
INSERT INTO config_web_fields VALUES (143, 'v_edit_man_conduit', 'conduit_custom_y2', NULL, 'double', NULL, NULL, '0.00', 'conduit_custom_y2', 'text', NULL, NULL, NULL, NULL, true, 5);
INSERT INTO config_web_fields VALUES (144, 'v_edit_man_conduit', 'conduit_elev1', NULL, 'double', NULL, NULL, '0.00', 'conduit_elev1', 'text', NULL, NULL, NULL, NULL, true, 6);
INSERT INTO config_web_fields VALUES (145, 'v_edit_man_conduit', 'conduit_elev2', NULL, 'double', NULL, NULL, '0.00', 'conduit_elev2', 'text', NULL, NULL, NULL, NULL, true, 7);
INSERT INTO config_web_fields VALUES (146, 'v_edit_man_conduit', 'conduit_custom_elev1', NULL, 'double', NULL, NULL, '0.00', 'conduit_custom_elev1', 'text', NULL, NULL, NULL, NULL, true, 8);
INSERT INTO config_web_fields VALUES (147, 'v_edit_man_conduit', 'conduit_custom_elev2', NULL, 'double', NULL, NULL, '0.00', 'conduit_custom_elev2', 'text', NULL, NULL, NULL, NULL, true, 9);
INSERT INTO config_web_fields VALUES (148, 'v_edit_man_conduit', 'arc_type', NULL, 'string', 30, NULL, NULL, 'Arc type', 'combo', 'arc_type', 'id', 'id', NULL, true, 10);
INSERT INTO config_web_fields VALUES (149, 'v_edit_man_conduit', 'arccat_id', NULL, 'string', 30, NULL, NULL, 'Arccat id', 'combo', 'cat_arc', 'id', 'id', NULL, true, 11);
INSERT INTO config_web_fields VALUES (150, 'v_edit_man_conduit', 'epa_type', NULL, 'string', 30, NULL, NULL, 'Epa type', 'combo', 'inp_arc_type', 'id', 'id', NULL, true, 12);
INSERT INTO config_web_fields VALUES (163, 'v_edit_man_conduit', 'conduit_fluid_type', NULL, 'string', 50, NULL, NULL, 'fluid type', 'text', 'man_type_fluid', 'fluid_type', 'fluid_type', 'SELECT * FROM man_type_fluid WHERE feature_type=''ARC'' AND (featurecat_id is null OR featurecat_id=''CONDUIT'');', true, 26);
INSERT INTO config_web_fields VALUES (154, 'v_edit_man_conduit', 'conduit_annotation', NULL, 'string', 256, NULL, NULL, 'annotation', 'text', NULL, NULL, NULL, NULL, true, 17);
INSERT INTO config_web_fields VALUES (155, 'v_edit_man_conduit', 'conduit_observ', NULL, 'string', 256, NULL, NULL, 'observ', 'text', NULL, NULL, NULL, NULL, true, 18);
INSERT INTO config_web_fields VALUES (156, 'v_edit_man_conduit', 'conduit_comment', NULL, 'string', 256, NULL, NULL, 'comment', 'text', NULL, NULL, NULL, NULL, true, 19);
INSERT INTO config_web_fields VALUES (157, 'v_edit_man_conduit', 'conduit_inverted_slope', NULL, 'boolean', NULL, NULL, NULL, 'inverted slope', 'checkbox', NULL, NULL, NULL, NULL, true, 20);
INSERT INTO config_web_fields VALUES (158, 'v_edit_man_conduit', 'conduit_custom_length', NULL, 'double', NULL, NULL, '0.00', 'conduit_custom_length', 'text', NULL, NULL, NULL, NULL, true, 21);
INSERT INTO config_web_fields VALUES (164, 'v_edit_man_conduit', 'conduit_location_type', NULL, 'string', 50, NULL, NULL, 'location type', 'text', 'man_type_location', 'location_type', 'location_type', 'SELECT * FROM man_type_location WHERE feature_type=''ARC'' AND (featurecat_id is null OR featurecat_id=''CONDUIT'');', true, 27);
INSERT INTO config_web_fields VALUES (162, 'v_edit_man_conduit', 'conduit_category_type', NULL, 'string', 50, NULL, NULL, 'category type', 'text', 'man_type_category', 'category_type', 'category_type', 'SELECT * FROM man_type_category WHERE feature_type=''ARC'' AND (featurecat_id is null OR featurecat_id=''CONDUIT'');', true, 25);
INSERT INTO config_web_fields VALUES (165, 'v_edit_man_conduit', 'conduit_workcat_id', NULL, 'string', 150, NULL, NULL, 'workcat', 'combo', 'cat_work', 'id', 'id', NULL, true, 28);
INSERT INTO config_web_fields VALUES (166, 'v_edit_man_conduit', 'conduit_workcat_id_end', NULL, 'string', 150, NULL, NULL, 'workcat end', 'combo', 'cat_work', 'id', 'id', NULL, true, 29);
INSERT INTO config_web_fields VALUES (167, 'v_edit_man_conduit', 'conduit_buildercat_id', NULL, 'string', 150, NULL, NULL, 'builder', 'combo', 'cat_builder', 'id', 'id', NULL, true, 30);
INSERT INTO config_web_fields VALUES (168, 'v_edit_man_conduit', 'conduit_enddate', NULL, 'date', NULL, NULL, NULL, 'enddate', 'date', NULL, NULL, NULL, NULL, true, 32);
INSERT INTO config_web_fields VALUES (169, 'v_edit_man_conduit', 'conduit_ownercat_id', NULL, 'string', 30, NULL, NULL, 'owner', 'combo', 'cat_owner', 'id', 'id', NULL, true, 33);
INSERT INTO config_web_fields VALUES (172, 'v_edit_man_conduit', 'conduit_address_01', NULL, 'string', 250, NULL, NULL, 'address 1', 'text', NULL, NULL, NULL, NULL, true, 36);
INSERT INTO config_web_fields VALUES (173, 'v_edit_man_conduit', 'conduit_address_02', NULL, 'string', 250, NULL, NULL, 'address 2', 'text', NULL, NULL, NULL, NULL, true, 37);
INSERT INTO config_web_fields VALUES (176, 'v_edit_man_conduit', 'verified', NULL, 'string', 30, NULL, NULL, 'verified', 'combo', 'value_verified', 'id', 'id', NULL, true, 40);
INSERT INTO config_web_fields VALUES (171, 'v_edit_man_conduit', 'conduit_streetaxis_id', NULL, 'string', 16, NULL, NULL, 'streetaxis', 'combo', 'ext_streetaxis', 'id', 'name', NULL, true, 35);
INSERT INTO config_web_fields VALUES (152, 'v_edit_man_conduit', 'state', NULL, 'string', NULL, NULL, NULL, 'state', 'combo', 'value_state', 'id', 'name', NULL, true, 14);
INSERT INTO config_web_fields VALUES (153, 'v_edit_man_conduit', 'state_type', NULL, 'string', NULL, NULL, NULL, 'state type', 'combo', 'value_state_type', 'id', 'name', NULL, true, 15);
INSERT INTO config_web_fields VALUES (151, 'v_edit_man_conduit', 'sector_id', NULL, 'string', NULL, NULL, NULL, 'Sector', 'combo', 'sector', 'sector_id', 'name', NULL, true, 13);
INSERT INTO config_web_fields VALUES (170, 'v_edit_man_conduit', 'conduit_muni_id', NULL, 'string', NULL, NULL, NULL, 'municipality', 'combo', 'ext_municipality', 'muni_id', 'name', NULL, true, 34);

