/*
This file is part of Giswater 3
The program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This version of Giswater is provided by Giswater Association
*/


SET search_path = "SCHEMA_NAME", public, pg_catalog;


INSERT INTO cat_users VALUES (999, current_user);



INSERT INTO config (id, node_proximity, arc_searchnodes, node2arc, connec_proximity, nodeinsert_arcendpoint, 
		orphannode_delete, vnode_update_tolerance, nodetype_change_enabled, 		
		samenode_init_end_control, node_proximity_control, connec_proximity_control, 
		node_duplicated_tolerance, connec_duplicated_tolerance, audit_function_control, arc_searchnodes_control, insert_double_geometry, buffer_value)
		VALUES ('1', 0.10000000000000001, 0.1, 0.5, 0.10000000000000001, false, false, 0.5, false, true, true, true, 0.001, 0.001, true, true, false, 1);




INSERT INTO config_param_system VALUES (29, 'inventory_update_date', '2017-01-01', 'date', 'om', NULL);
INSERT INTO config_param_system VALUES (30, 'geom_slp_direction', 'FALSE', 'boolean', 'topology', 'Ony for UD');
INSERT INTO config_param_system VALUES (27, 'state_topocontrol', 'TRUE', 'boolean', 'topology', 'Only for WS');
INSERT INTO config_param_system VALUES (31, 'link_search_button', '0,1', 'float', 'edit', NULL);
INSERT INTO config_param_system VALUES (34, 'rev_arc_y1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (36, 'rev_arc_geom1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (35, 'rev_arc_y2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (33, 'rev_node_depth_tol', '0', 'float', 'review', 'Only for WS');
INSERT INTO config_param_system VALUES (32, 'rev_node_elevation_tol', '0', 'float', 'review', 'Only for WS');
INSERT INTO config_param_system VALUES (37, 'rev_arc_geom2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (38, 'rev_node_top_elev_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (39, 'rev_node_ymax_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (40, 'rev_node_geom1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (41, 'rev_node_geom2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (42, 'rev_connec_y1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (44, 'rev_connec_geom1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (43, 'rev_connec_y2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (45, 'rev_connec_geom2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (46, 'rev_gully_top_elev_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (48, 'rev_gully_sandbox_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (50, 'rev_gully_connec_geom2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (51, 'rev_gully_units_tol', '1', 'integer', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (49, 'rev_gully_connec_geom1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (47, 'rev_gully_ymax_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (52, 'link_searchbuffer', 'true', 'boolean', 'topology', NULL);
INSERT INTO config_param_system VALUES (53, 'proximity_buffer', '50', 'double precision', NULL, NULL);
INSERT INTO config_param_system VALUES (18, 'street_layer', 'v_ext_streetaxis', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (19, 'street_field_code', 'id', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (20, 'street_field_name', 'name', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (21, 'portal_layer', 'v_ext_address', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (22, 'portal_field_code', 'streetaxis_id', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (23, 'portal_field_number', 'postnumber', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (6, 'expl_field_name', 'name', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (4, 'expl_layer', 'ext_municipality', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (13, 'network_field_arc_code', 'code', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (10, 'network_layer_element', 'element', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (15, 'network_field_element_code', 'code', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (16, 'network_field_gully_code', 'code', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (8, 'network_layer_arc', 'v_edit_arc', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (9, 'network_layer_connec', 'v_edit_connec', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (12, 'network_layer_node', 'v_edit_node', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (14, 'network_field_connec_code', 'code', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (17, 'network_field_node_code', 'code', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (11, 'network_layer_gully', 'v_edit_gully', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (7, 'scale_zoom', '500', 'integer', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (24, 'portal_field_postal', 'postcode', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (25, 'street_field_expl', 'muni_id', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (5, 'expl_field_code', 'muni_id', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (26, 'module_om_rehabit', 'TRUE', 'boolean', 'om', NULL);
INSERT INTO config_param_system VALUES (2, 'om_visit_absolute_path', 'c:/', 'varchar', 'path', NULL);
INSERT INTO config_param_system VALUES (1, 'doc_absolute_path', NULL, 'varchar', 'path', NULL);
INSERT INTO config_param_system VALUES (3, 'custom_giswater_folder', NULL, 'varchar', 'path', NULL);
INSERT INTO config_param_system VALUES (54, 'edit_arc_divide_automatic_control', 'TRUE', 'boolean', 'edit', NULL);
INSERT INTO config_param_system VALUES (55, 'edit_enable_arc_nodes_update', 'FALSE', 'boolean', 'edit', NULL);
INSERT INTO config_param_system VALUES (56, 'hydrometer_link_absolute_path', NULL, 'text', 'rtc', NULL);




	

INSERT INTO config_client_forms VALUES (7960, 'node form', 'utils', 'v_ui_element_x_node', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7970, 'node form', 'utils', 'v_ui_element_x_node', 'node_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7980, 'node form', 'utils', 'v_ui_element_x_node', 'element_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7990, 'node form', 'utils', 'v_ui_element_x_node', 'elementcat_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8000, 'node form', 'utils', 'v_ui_element_x_node', 'num_elements', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8010, 'node form', 'utils', 'v_ui_element_x_node', 'state', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8020, 'node form', 'utils', 'v_ui_element_x_node', 'state_type', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8030, 'node form', 'utils', 'v_ui_element_x_node', 'observ', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8040, 'node form', 'utils', 'v_ui_element_x_node', 'comment', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8050, 'node form', 'utils', 'v_ui_element_x_node', 'builtdate', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8060, 'node form', 'utils', 'v_ui_element_x_node', 'enddate', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8070, 'node form', 'utils', 'v_ui_element_x_node', 'link', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8080, 'node form', 'utils', 'v_ui_element_x_node', 'publish', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8090, 'node form', 'utils', 'v_ui_element_x_node', 'inventory', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8091, 'node form', 'utils', 'v_ui_element_x_node', 'descript', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8100, 'node form', 'utils', 'v_ui_doc_x_node', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8110, 'node form', 'utils', 'v_ui_doc_x_node', 'node_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8120, 'node form', 'utils', 'v_ui_doc_x_node', 'doc_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8130, 'node form', 'utils', 'v_ui_doc_x_node', 'doc_type', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8140, 'node form', 'utils', 'v_ui_doc_x_node', 'path', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8150, 'node form', 'utils', 'v_ui_doc_x_node', 'observ', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8160, 'node form', 'utils', 'v_ui_doc_x_node', 'date', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8170, 'node form', 'utils', 'v_ui_doc_x_node', 'user_name', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8180, 'node form', 'utils', 'v_ui_om_visit_x_node', 'event_id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8190, 'node form', 'utils', 'v_ui_om_visit_x_node', 'visit_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8200, 'node form', 'utils', 'v_ui_om_visit_x_node', 'code', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8210, 'node form', 'utils', 'v_ui_om_visit_x_node', 'visitcat_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8220, 'node form', 'utils', 'v_ui_om_visit_x_node', 'visit_start', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8230, 'node form', 'utils', 'v_ui_om_visit_x_node', 'visit_end', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8240, 'node form', 'utils', 'v_ui_om_visit_x_node', 'user_name', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8250, 'node form', 'utils', 'v_ui_om_visit_x_node', 'is_done', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8270, 'node form', 'utils', 'v_ui_om_visit_x_node', 'node_id', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8280, 'node form', 'utils', 'v_ui_om_visit_x_node', 'parameter_id', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8290, 'node form', 'utils', 'v_ui_om_visit_x_node', 'parameter_type', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8300, 'node form', 'utils', 'v_ui_om_visit_x_node', 'feature_type', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8310, 'node form', 'utils', 'v_ui_om_visit_x_node', 'form_type', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8390, 'node form', 'utils', 'v_ui_scada_x_node', 'scada_id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8400, 'node form', 'utils', 'v_ui_scada_x_node', 'node_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8410, 'node form', 'utils', 'v_ui_scada_x_node_values', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8420, 'node form', 'utils', 'v_ui_scada_x_node_values', 'scada_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8430, 'node form', 'utils', 'v_ui_scada_x_node_values', 'node_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8440, 'node form', 'utils', 'v_ui_scada_x_node_values', 'value', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8450, 'node form', 'utils', 'v_ui_scada_x_node_values', 'status', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8460, 'node form', 'utils', 'v_ui_scada_x_node_values', 'timestamp', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9660, 'node form', 'ws', 'v_ui_node_x_relations', 'parent_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9670, 'node form', 'ws', 'v_ui_node_x_relations', 'nodetype_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9680, 'node form', 'ws', 'v_ui_node_x_relations', 'nodecat_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9690, 'node form', 'ws', 'v_ui_node_x_relations', 'node_id', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9700, 'node form', 'ws', 'v_ui_node_x_relations', 'code', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9710, 'node form', 'ws', 'v_ui_node_x_relations', 'sys_type', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9950, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'node_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9960, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'feature_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9970, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'feature_code', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9980, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'featurecat_id', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9990, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'arccat_id', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10000, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'depth', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10010, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'length', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10020, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'upstream_id', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10030, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'upstream_code', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10040, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'upstream_type', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10050, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'upstream_depth', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10060, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'sys_type', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10070, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'x', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10080, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'y', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8500, 'arc form', 'utils', 'v_ui_element_x_arc', 'elementcat_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8510, 'arc form', 'utils', 'v_ui_element_x_arc', 'num_elements', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8520, 'arc form', 'utils', 'v_ui_element_x_arc', 'state', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8530, 'arc form', 'utils', 'v_ui_element_x_arc', 'state_type', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8540, 'arc form', 'utils', 'v_ui_element_x_arc', 'observ', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8550, 'arc form', 'utils', 'v_ui_element_x_arc', 'comment', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8560, 'arc form', 'utils', 'v_ui_element_x_arc', 'builtdate', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8570, 'arc form', 'utils', 'v_ui_element_x_arc', 'enddate', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8580, 'arc form', 'utils', 'v_ui_element_x_arc', 'link', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8590, 'arc form', 'utils', 'v_ui_element_x_arc', 'publish', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8600, 'arc form', 'utils', 'v_ui_element_x_arc', 'inventory', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8601, 'arc form', 'utils', 'v_ui_element_x_arc', 'descript', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18570, 'arc form', 'utils', 'v_ui_arc_x_relations', 'arc_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18580, 'arc form', 'utils', 'v_ui_arc_x_relations', 'featurecat_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8330, 'node form', 'utils', 'v_ui_om_visit_x_node', 'xcoord', 17, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8340, 'node form', 'utils', 'v_ui_om_visit_x_node', 'ycoord', 18, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8350, 'node form', 'utils', 'v_ui_om_visit_x_node', 'compass', 19, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8370, 'node form', 'utils', 'v_ui_om_visit_x_node', 'gallery', 21, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8380, 'node form', 'utils', 'v_ui_om_visit_x_node', 'document', 22, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18560, 'arc form', 'utils', 'v_ui_arc_x_relations', 'rid', 1, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10090, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'rid', 1, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9940, 'node form', 'ud', 'v_ui_node_x_connection_upstream', 'rid', 1, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9650, 'node form', 'ws', 'v_ui_node_x_relations', 'rid', 1, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18590, 'arc form', 'utils', 'v_ui_arc_x_relations', 'catalog', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18600, 'arc form', 'utils', 'v_ui_arc_x_relations', 'feature_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18610, 'arc form', 'utils', 'v_ui_arc_x_relations', 'feature_code', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18620, 'arc form', 'utils', 'v_ui_arc_x_relations', 'sys_type', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18630, 'arc form', 'utils', 'v_ui_arc_x_relations', 'arc_state', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18640, 'arc form', 'utils', 'v_ui_arc_x_relations', 'feature_state', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18650, 'arc form', 'utils', 'v_ui_arc_x_relations', 'x', 9, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18660, 'arc form', 'utils', 'v_ui_arc_x_relations', 'y', 10, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8610, 'arc form', 'utils', 'v_ui_doc_x_arc', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8620, 'arc form', 'utils', 'v_ui_doc_x_arc', 'arc_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8630, 'arc form', 'utils', 'v_ui_doc_x_arc', 'doc_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8640, 'arc form', 'utils', 'v_ui_doc_x_arc', 'doc_type', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8650, 'arc form', 'utils', 'v_ui_doc_x_arc', 'path', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8660, 'arc form', 'utils', 'v_ui_doc_x_arc', 'observ', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8670, 'arc form', 'utils', 'v_ui_doc_x_arc', 'date', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8680, 'arc form', 'utils', 'v_ui_doc_x_arc', 'user_name', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8690, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'event_id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8700, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'visit_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8710, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'code', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8720, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'visitcat_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8730, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'visit_start', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8740, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'visit_end', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8750, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'user_name', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8760, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'is_done', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8780, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'arc_id', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8790, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'parameter_id', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8800, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'parameter_type', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8810, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'feature_type', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8820, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'form_type', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9920, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'start_date', 21, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9930, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'end_date', 22, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10380, 'gully form', 'ud', 'v_ui_doc_x_gully', 'path', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10390, 'gully form', 'ud', 'v_ui_doc_x_gully', 'observ', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10400, 'gully form', 'ud', 'v_ui_doc_x_gully', 'date', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10410, 'gully form', 'ud', 'v_ui_doc_x_gully', 'user_name', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10420, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'event_id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10430, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'visit_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10440, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'ext_code', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10450, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'visitcat_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10460, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'visit_start', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10470, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'visit_end', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10480, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'user_name', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10490, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'is_done', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10500, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'tstamp', 9, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10510, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'gully_id', 10, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10520, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'parameter_id', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10530, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'parameter_type', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10540, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'feature_type', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10550, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'form_type', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6640, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature', 'feature_type', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6650, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature', 'featurecat_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6660, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature', 'feature_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6670, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature', 'code', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6680, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature', 'expl_name', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6690, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature', 'workcat_id', 7, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6692, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature', 'expl_id', 8, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6710, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature_end', 'feature_type', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6720, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature_end', 'featurecat_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6730, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature_end', 'feature_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6740, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature_end', 'code', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6750, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature_end', 'expl_name', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6760, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature_end', 'workcat_id', 7, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6762, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature_end', 'expl_id', 8, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6770, 'om toolbar', 'utils', 'v_ui_om_visit', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6780, 'om toolbar', 'utils', 'v_ui_om_visit', 'visit_catalog', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6790, 'om toolbar', 'utils', 'v_ui_om_visit', 'ext_code', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6800, 'om toolbar', 'utils', 'v_ui_om_visit', 'startdate', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6810, 'om toolbar', 'utils', 'v_ui_om_visit', 'enddate', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6820, 'om toolbar', 'utils', 'v_ui_om_visit', 'user_name', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6830, 'om toolbar', 'utils', 'v_ui_om_visit', 'webclient_id', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6840, 'om toolbar', 'utils', 'v_ui_om_visit', 'exploitation', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6860, 'om toolbar', 'utils', 'v_ui_om_visit', 'descript', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6870, 'om toolbar', 'utils', 'v_ui_om_visit', 'is_done', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6880, 'om toolbar', 'utils', 'om_psector', 'psector_id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8840, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'xcoord', 17, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8850, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'ycoord', 18, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8860, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'compass', 19, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8870, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'event_code', 20, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8880, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'gallery', 21, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8890, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'document', 22, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9290, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'xcoord', 17, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9300, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'ycoord', 18, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10560, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'value', 16, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10570, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'xcoord', 17, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10580, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'ycoord', 18, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10590, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'compass', 19, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10610, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'gallery', 21, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10620, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'document', 22, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6890, 'om toolbar', 'utils', 'om_psector', 'name', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6900, 'om toolbar', 'utils', 'om_psector', 'psector_type', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6910, 'om toolbar', 'utils', 'om_psector', 'result_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6920, 'om toolbar', 'utils', 'om_psector', 'descript', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6930, 'om toolbar', 'utils', 'om_psector', 'expl_id', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6940, 'om toolbar', 'utils', 'om_psector', 'priority', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6700, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature_end', 'rid', 1, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6850, 'om toolbar', 'utils', 'v_ui_om_visit', 'the_geom', 9, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8770, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'tstamp', 9, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6950, 'om toolbar', 'utils', 'om_psector', 'text1', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6960, 'om toolbar', 'utils', 'om_psector', 'text2', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6970, 'om toolbar', 'utils', 'om_psector', 'observ', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6980, 'om toolbar', 'utils', 'om_psector', 'rotation', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6990, 'om toolbar', 'utils', 'om_psector', 'scale', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7000, 'om toolbar', 'utils', 'om_psector', 'sector_id', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7010, 'om toolbar', 'utils', 'om_psector', 'atlas_id', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7050, 'om toolbar', 'utils', 'om_psector', 'active', 18, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7070, 'edit toolbar', 'utils', 'doc', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7080, 'edit toolbar', 'utils', 'doc', 'doc_type', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7090, 'edit toolbar', 'utils', 'doc', 'path', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7100, 'edit toolbar', 'utils', 'doc', 'observ', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7110, 'edit toolbar', 'utils', 'doc', 'date', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7120, 'edit toolbar', 'utils', 'doc', 'user_name', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7140, 'edit toolbar', 'utils', 'element', 'element_id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7150, 'edit toolbar', 'utils', 'element', 'code', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7160, 'edit toolbar', 'utils', 'element', 'elementcat_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7170, 'edit toolbar', 'utils', 'element', 'serial_number', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7180, 'edit toolbar', 'utils', 'element', 'num_elements', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7190, 'edit toolbar', 'utils', 'element', 'state', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7200, 'edit toolbar', 'utils', 'element', 'state_type', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7210, 'edit toolbar', 'utils', 'element', 'observ', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7220, 'edit toolbar', 'utils', 'element', 'comment', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7230, 'edit toolbar', 'utils', 'element', 'function_type', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7240, 'edit toolbar', 'utils', 'element', 'category_type', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7250, 'edit toolbar', 'utils', 'element', 'fluid_type', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7260, 'edit toolbar', 'utils', 'element', 'location_type', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7270, 'edit toolbar', 'utils', 'element', 'workcat_id', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7280, 'edit toolbar', 'utils', 'element', 'workcat_id_end', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7290, 'edit toolbar', 'utils', 'element', 'buildercat_id', 16, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7300, 'edit toolbar', 'utils', 'element', 'builtdate', 17, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7310, 'edit toolbar', 'utils', 'element', 'enddate', 18, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7430, 'edit toolbar', 'utils', 'element', 'expl_id', 30, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7460, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7470, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'result_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7480, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'n_junction', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7490, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'n_reservoir', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7500, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'n_tank', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7510, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'n_pipe', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7520, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'n_pump', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7530, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'n_valve', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7540, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'head_form', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7550, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'hydra_time', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7560, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'hydra_acc', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7570, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'st_ch_freq', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7580, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'max_tr_ch', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7590, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'dam_li_thr', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7600, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'max_trials', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7610, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'q_analysis', 16, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7620, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'spec_grav', 17, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7630, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'r_kin_visc', 18, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7640, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'r_che_diff', 19, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7650, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'dem_multi', 20, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7660, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'total_dura', 21, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7670, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'exec_date', 22, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7680, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'q_timestep', 23, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7690, 'epa toolbar', 'utils', 'v_ui_rpt_cat_result', 'q_tolerance', 24, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7700, 'plan toolbar', 'utils', 'plan_psector', 'psector_id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7710, 'plan toolbar', 'utils', 'plan_psector', 'name', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7720, 'plan toolbar', 'utils', 'plan_psector', 'psector_type', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7730, 'plan toolbar', 'utils', 'plan_psector', 'descript', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7740, 'plan toolbar', 'utils', 'plan_psector', 'expl_id', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7750, 'plan toolbar', 'utils', 'plan_psector', 'priority', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7760, 'plan toolbar', 'utils', 'plan_psector', 'text1', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7770, 'plan toolbar', 'utils', 'plan_psector', 'text2', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7780, 'plan toolbar', 'utils', 'plan_psector', 'observ', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7790, 'plan toolbar', 'utils', 'plan_psector', 'rotation', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7800, 'plan toolbar', 'utils', 'plan_psector', 'scale', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7810, 'plan toolbar', 'utils', 'plan_psector', 'sector_id', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7820, 'plan toolbar', 'utils', 'plan_psector', 'atlas_id', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7860, 'plan toolbar', 'utils', 'plan_psector', 'active', 17, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7040, 'om toolbar', 'utils', 'om_psector', 'other', 17, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7030, 'om toolbar', 'utils', 'om_psector', 'vat', 16, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7130, 'edit toolbar', 'utils', 'doc', 'tstamp', 7, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7450, 'edit toolbar', 'utils', 'element', 'tstamp', 32, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7440, 'edit toolbar', 'utils', 'element', 'feature_type', 31, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7420, 'edit toolbar', 'utils', 'element', 'inventory', 29, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7410, 'edit toolbar', 'utils', 'element', 'publish', 28, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7400, 'edit toolbar', 'utils', 'element', 'undelete', 27, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7390, 'edit toolbar', 'utils', 'element', 'label_rotation', 26, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7380, 'edit toolbar', 'utils', 'element', 'label_y', 25, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7370, 'edit toolbar', 'utils', 'element', 'label_x', 24, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7360, 'edit toolbar', 'utils', 'element', 'the_geom', 23, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7350, 'edit toolbar', 'utils', 'element', 'verified', 22, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7330, 'edit toolbar', 'utils', 'element', 'rotation', 20, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7340, 'edit toolbar', 'utils', 'element', 'link', 21, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7320, 'edit toolbar', 'utils', 'element', 'ownercat_id', 19, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7870, 'plan toolbar', 'utils', 'plan_psector', 'the_geom', 18, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7850, 'plan toolbar', 'utils', 'plan_psector', 'other', 16, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7840, 'plan toolbar', 'utils', 'plan_psector', 'vat', 15, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7880, 'plan toolbar', 'utils', 'v_ui_om_result_cat', 'result_id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7890, 'plan toolbar', 'utils', 'v_ui_om_result_cat', 'name', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7900, 'plan toolbar', 'utils', 'v_ui_om_result_cat', 'result_type', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7910, 'plan toolbar', 'utils', 'v_ui_om_result_cat', 'pricecat_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7920, 'plan toolbar', 'utils', 'v_ui_om_result_cat', 'network_price_coeff', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7930, 'plan toolbar', 'utils', 'v_ui_om_result_cat', 'descript', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7950, 'plan toolbar', 'utils', 'v_ui_om_result_cat', 'cur_user', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8470, 'arc form', 'utils', 'v_ui_element_x_arc', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8480, 'arc form', 'utils', 'v_ui_element_x_arc', 'arc_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8490, 'arc form', 'utils', 'v_ui_element_x_arc', 'element_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8900, 'connec form', 'utils', 'v_ui_element_x_connec', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8910, 'connec form', 'utils', 'v_ui_element_x_connec', 'connec_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8920, 'connec form', 'utils', 'v_ui_element_x_connec', 'element_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8930, 'connec form', 'utils', 'v_ui_element_x_connec', 'elementcat_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8940, 'connec form', 'utils', 'v_ui_element_x_connec', 'num_elements', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8950, 'connec form', 'utils', 'v_ui_element_x_connec', 'state', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8960, 'connec form', 'utils', 'v_ui_element_x_connec', 'state_type', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8970, 'connec form', 'utils', 'v_ui_element_x_connec', 'observ', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8980, 'connec form', 'utils', 'v_ui_element_x_connec', 'comment', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8990, 'connec form', 'utils', 'v_ui_element_x_connec', 'builtdate', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9000, 'connec form', 'utils', 'v_ui_element_x_connec', 'enddate', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9010, 'connec form', 'utils', 'v_ui_element_x_connec', 'link', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9020, 'connec form', 'utils', 'v_ui_element_x_connec', 'publish', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9030, 'connec form', 'utils', 'v_ui_element_x_connec', 'inventory', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9031, 'connec form', 'utils', 'v_ui_element_x_connec', 'descript', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9040, 'connec form', 'utils', 'v_rtc_hydrometer_x_connec', 'connec_id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9050, 'connec form', 'utils', 'v_rtc_hydrometer_x_connec', 'n_hydrometer', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9060, 'connec form', 'utils', 'v_ui_doc_x_connec', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9070, 'connec form', 'utils', 'v_ui_doc_x_connec', 'connec_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9080, 'connec form', 'utils', 'v_ui_doc_x_connec', 'doc_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9090, 'connec form', 'utils', 'v_ui_doc_x_connec', 'doc_type', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9100, 'connec form', 'utils', 'v_ui_doc_x_connec', 'path', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9110, 'connec form', 'utils', 'v_ui_doc_x_connec', 'observ', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9120, 'connec form', 'utils', 'v_ui_doc_x_connec', 'date', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9130, 'connec form', 'utils', 'v_ui_doc_x_connec', 'user_name', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9140, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'event_id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9150, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'visit_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9160, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'code', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9170, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'visitcat_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9180, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'visit_start', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9190, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'visit_end', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9200, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'user_name', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9210, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'is_done', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9230, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'connec_id', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9240, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'parameter_id', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9250, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'parameter_type', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9260, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'feature_type', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9270, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'form_type', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9350, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9352, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'name', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9360, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'work_order', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9370, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'state', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9380, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'class', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9390, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'mincut_type', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9400, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'received_date', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9410, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'expl_id', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9412, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'macroexpl_id', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9430, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'muni_id', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9440, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'postcode', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9450, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'streetaxis_id', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9460, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'postnumber', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9470, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'anl_cause', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9480, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'anl_tstamp', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9490, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'anl_user', 16, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9500, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'anl_descript', 17, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9510, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'anl_feature_id', 18, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9520, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'anl_feature_type', 19, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9530, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'anl_the_geom', 20, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9540, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'forecast_start', 21, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9550, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'forecast_end', 22, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9560, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'assigned_to', 23, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9570, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'exec_start', 24, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9580, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'exec_end', 25, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9590, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'exec_user', 26, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9600, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'exec_descript', 27, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9610, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'exec_the_geom', 28, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9620, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'exec_from_plot', 29, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9630, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'exec_depth', 30, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9640, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'exec_appropiate', 31, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9220, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'tstamp', 9, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9420, 'om toolbar', 'ws', 'v_ui_anl_mincut_result_cat', 'macroexpl_id', 8, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9720, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9730, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'hydrometer_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9740, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'connec_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9750, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'result_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9760, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'work_order', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9770, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'mincut_state', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9780, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'mincut_class', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9790, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'mincut_type', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9800, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'received_date', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9810, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'anl_cause', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9820, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'anl_tstamp', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9830, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'anl_user', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9840, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'anl_descript', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9850, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'forecast_start', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9860, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'forecast_end', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9870, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'exec_start', 16, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9880, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'exec_end', 17, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9890, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'exec_user', 18, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9900, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'exec_descript', 19, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9910, 'connec form', 'ws', 'v_ui_mincut_hydrometer', 'exec_appropiate', 20, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10100, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'node_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10110, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'feature_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10120, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'feature_code', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10130, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'featurecat_id', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10140, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'arccat_id', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10150, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'depth', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10160, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'length', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10170, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'downstream_id', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10180, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'downstream_code', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10190, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'downstream_type', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10200, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'downstream_depth', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10210, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'sys_type', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10220, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'x', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10230, 'node form', 'ud', 'v_ui_node_x_connection_downstream', 'y', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10240, 'gully form', 'ud', 'v_ui_element_x_gully', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10250, 'gully form', 'ud', 'v_ui_element_x_gully', 'gully_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10260, 'gully form', 'ud', 'v_ui_element_x_gully', 'element_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10270, 'gully form', 'ud', 'v_ui_element_x_gully', 'elementcat_id', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10280, 'gully form', 'ud', 'v_ui_element_x_gully', 'num_elements', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10290, 'gully form', 'ud', 'v_ui_element_x_gully', 'state', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10300, 'gully form', 'ud', 'v_ui_element_x_gully', 'observ', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10310, 'gully form', 'ud', 'v_ui_element_x_gully', 'comment', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10320, 'gully form', 'ud', 'v_ui_element_x_gully', 'builtdate', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10330, 'gully form', 'ud', 'v_ui_element_x_gully', 'enddate', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19010, 'gully form', 'ud', 'v_ui_element_x_gully', 'descript', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10340, 'gully form', 'ud', 'v_ui_doc_x_gully', 'id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10350, 'gully form', 'ud', 'v_ui_doc_x_gully', 'gully_id', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10360, 'gully form', 'ud', 'v_ui_doc_x_gully', 'doc_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10370, 'gully form', 'ud', 'v_ui_doc_x_gully', 'doc_type', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (6630, 'basic toolbar', 'utils', 'v_ui_workcat_x_feature', 'rid', 1, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7060, 'om toolbar', 'utils', 'om_psector', 'the_geom', 19, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7020, 'om toolbar', 'utils', 'om_psector', 'gexpenses', 15, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7830, 'plan toolbar', 'utils', 'plan_psector', 'gexpenses', 14, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7940, 'plan toolbar', 'utils', 'v_ui_om_result_cat', 'tstamp', 7, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8260, 'node form', 'utils', 'v_ui_om_visit_x_node', 'tstamp', 9, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8830, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'value', 16, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9280, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'value', 16, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9310, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'compass', 19, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9320, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'event_code', 20, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9330, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'gallery', 21, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9340, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'document', 22, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8320, 'node form', 'utils', 'v_ui_om_visit_x_node', 'value', 16, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8360, 'node form', 'utils', 'v_ui_om_visit_x_node', 'event_code', 20, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18670, 'arc form', 'utils', 'v_ui_om_visit_x_arc', 'descript', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18680, 'connec form', 'utils', 'v_ui_om_visit_x_connec', 'descript', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18690, 'node form', 'utils', 'v_ui_om_visit_x_node', 'descript', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18700, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'descript', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10600, 'gully form', 'ud', 'v_ui_om_visit_x_gully', 'event_code', 20, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18900, 'node form', 'utils', 'v_plan_node', 'the_geom', 10, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18750, 'node form', 'utils', 'v_plan_node', 'node_id', 1, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18830, 'node form', 'utils', 'v_plan_node', 'node_type', 3, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18860, 'node form', 'utils', 'v_plan_node', 'epa_type', 6, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18940, 'node form', 'utils', 'v_plan_node', 'measurement', 14, true, 50, 'units', NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18840, 'node form', 'utils', 'v_plan_node', 'top_elev', 4, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18850, 'node form', 'utils', 'v_plan_node', 'elev', 5, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18870, 'node form', 'utils', 'v_plan_node', 'sector_id', 7, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18880, 'node form', 'utils', 'v_plan_node', 'state', 8, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18890, 'node form', 'utils', 'v_plan_node', 'annotation', 9, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18930, 'node form', 'utils', 'v_plan_node', 'cost', 13, true, 60, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18800, 'node form', 'utils', 'v_plan_node', 'nodecat_id', 2, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18950, 'node form', 'utils', 'v_plan_node', 'budget', 15, true, 70, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18910, 'node form', 'utils', 'v_plan_node', 'cost_unit', 11, false, 30, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18920, 'node form', 'utils', 'v_plan_node', 'descript', 12, true, 318, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18960, 'node form', 'utils', 'v_plan_node', 'expl_id', 16, false, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19038, 'connec form', 'utils', 'v_rtc_hydrometer', 'hydrometer_id', 1, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19039, 'connec form', 'utils', 'v_rtc_hydrometer', 'hydrometer_customer_code', 2, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19040, 'connec form', 'utils', 'v_rtc_hydrometer', 'connec_id', 3, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19041, 'connec form', 'utils', 'v_rtc_hydrometer', 'connec_customer_code', 4, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19042, 'connec form', 'utils', 'v_rtc_hydrometer', 'state', 5, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19043, 'connec form', 'utils', 'v_rtc_hydrometer', 'muni_name', 6, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19044, 'connec form', 'utils', 'v_rtc_hydrometer', 'expl_id', 7, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19045, 'connec form', 'utils', 'v_rtc_hydrometer', 'expl_name', 8, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19046, 'connec form', 'utils', 'v_rtc_hydrometer', 'plot_code', 9, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19047, 'connec form', 'utils', 'v_rtc_hydrometer', 'priority_id', 10, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19048, 'connec form', 'utils', 'v_rtc_hydrometer', 'catalog_id', 11, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19049, 'connec form', 'utils', 'v_rtc_hydrometer', 'category_id', 12, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19050, 'connec form', 'utils', 'v_rtc_hydrometer', 'hydro_number', 13, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19051, 'connec form', 'utils', 'v_rtc_hydrometer', 'hydro_man_date', 14, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19052, 'connec form', 'utils', 'v_rtc_hydrometer', 'crm_number', 15, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19053, 'connec form', 'utils', 'v_rtc_hydrometer', 'customer_name', 16, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19054, 'connec form', 'utils', 'v_rtc_hydrometer', 'address1', 17, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19055, 'connec form', 'utils', 'v_rtc_hydrometer', 'address2', 18, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19056, 'connec form', 'utils', 'v_rtc_hydrometer', 'address3', 19, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19057, 'connec form', 'utils', 'v_rtc_hydrometer', 'address2_1', 20, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19058, 'connec form', 'utils', 'v_rtc_hydrometer', 'address2_2', 21, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19059, 'connec form', 'utils', 'v_rtc_hydrometer', 'address2_3', 22, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19060, 'connec form', 'utils', 'v_rtc_hydrometer', 'm3_volume', 23, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19061, 'connec form', 'utils', 'v_rtc_hydrometer', 'start_date', 24, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19062, 'connec form', 'utils', 'v_rtc_hydrometer', 'end_date', 25, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19063, 'connec form', 'utils', 'v_rtc_hydrometer', 'update_date', 26, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19064, 'connec form', 'utils', 'v_rtc_hydrometer', 'hydrometer_link', 27, true, NULL, NULL, NULL, NULL, NULL, NULL);



--delete temporal version information needed for fk function;
DELETE FROM version;