/*
This file is part of Giswater 3
The program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This version of Giswater is provided by Giswater Association
*/


SET search_path = "SCHEMA_NAME", public, pg_catalog;


INSERT INTO cat_users VALUES ('postgres');


INSERT INTO config (id, node_proximity, arc_searchnodes, node2arc, connec_proximity, nodeinsert_arcendpoint, 
		orphannode_delete, vnode_update_tolerance, nodetype_change_enabled, 		
		samenode_init_end_control, node_proximity_control, connec_proximity_control, 
		node_duplicated_tolerance, connec_duplicated_tolerance, audit_function_control, arc_searchnodes_control, insert_double_geometry, buffer_value)
		VALUES ('1', 0.10000000000000001, 0.5, 0.5, 0.10000000000000001, false, false, 0.5, false, true, true, true, 0.001, 0.001, true, true, true, 1);




INSERT INTO config_param_system VALUES (42, 'inventory_update_date', '2017-01-01', 'date', 'om', NULL);
INSERT INTO config_param_system VALUES (43, 'geom_slp_direction', 'TRUE', 'boolean', 'topology', 'Ony for UD');
INSERT INTO config_param_system VALUES (40, 'state_topocontrol', 'TRUE', 'boolean', 'topology', 'Only for WS');
INSERT INTO config_param_system VALUES (44, 'link_search_button', '0,1', 'float', 'edit', NULL);
INSERT INTO config_param_system VALUES (47, 'rev_arc_y1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (49, 'rev_arc_geom1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (48, 'rev_arc_y2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (46, 'rev_node_depth_tol', '0', 'float', 'review', 'Only for WS');
INSERT INTO config_param_system VALUES (45, 'rev_node_elevation_tol', '0', 'float', 'review', 'Only for WS');
INSERT INTO config_param_system VALUES (50, 'rev_arc_geom2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (51, 'rev_node_top_elev_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (52, 'rev_node_ymax_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (53, 'rev_node_geom1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (54, 'rev_node_geom2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (55, 'rev_connec_y1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (57, 'rev_connec_geom1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (56, 'rev_connec_y2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (58, 'rev_connec_geom2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (59, 'rev_gully_top_elev_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (61, 'rev_gully_sandbox_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (63, 'rev_gully_connec_geom2_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (64, 'rev_gully_units_tol', '1', 'integer', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (62, 'rev_gully_connec_geom1_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (60, 'rev_gully_ymax_tol', '0', 'float', 'review', 'Only for UD');
INSERT INTO config_param_system VALUES (65, 'link_searchbuffer', 'true', 'boolean', 'topology', NULL);
INSERT INTO config_param_system VALUES (66, 'proximity_buffer', '50', 'double precision', NULL, NULL);
INSERT INTO config_param_system VALUES (31, 'street_layer', 'v_ext_streetaxis', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (32, 'street_field_code', 'id', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (33, 'street_field_name', 'name', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (34, 'portal_layer', 'v_ext_address', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (35, 'portal_field_code', 'streetaxis_id', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (36, 'portal_field_number', 'postnumber', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (9, 'expl_field_name', 'name', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (7, 'expl_layer', 'ext_municipality', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (16, 'network_field_arc_code', 'code', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (13, 'network_layer_element', 'element', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (18, 'network_field_element_code', 'code', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (19, 'network_field_gully_code', 'code', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (22, 'hydrometer_urban_propierties_field_code', 'connec_id', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (11, 'network_layer_arc', 'v_edit_arc', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (12, 'network_layer_connec', 'v_edit_connec', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (25, 'hydrometer_field_urban_propierties_code', 'connec_id', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (15, 'network_layer_node', 'v_edit_node', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (24, 'hydrometer_field_code', 'hydrometer_id', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (17, 'network_field_connec_code', 'code', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (23, 'hydrometer_layer', 'v_rtc_hydrometer', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (20, 'network_field_node_code', 'code', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (14, 'network_layer_gully', 'v_edit_gully', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (21, 'hydrometer_urban_propierties_layer', 'v_edit_connec', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (10, 'scale_zoom', '500', 'integer', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (37, 'portal_field_postal', 'postcode', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (38, 'street_field_expl', 'muni_id', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (8, 'expl_field_code', 'muni_id', 'varchar', 'searchplus', NULL);
INSERT INTO config_param_system VALUES (41, 'mincut_conflict_map', 'FALSE', 'boolean', 'mincut', NULL);
INSERT INTO config_param_system VALUES (39, 'module_om_rehabit', 'TRUE', 'boolean', 'om', NULL);
INSERT INTO config_param_system VALUES (4, 'om_visit_absolute_path', 'https://www.', 'varchar', 'path', NULL);
INSERT INTO config_param_system VALUES (2, 'doc_absolute_path', 'c:', 'varchar', 'path', NULL);
INSERT INTO config_param_system VALUES (5, 'custom_giswater_folder', 'c:/', 'varchar', 'path', NULL);
INSERT INTO config_param_system VALUES (68, 'edit_arc_divide_automatic_control', 'TRUE', 'boolean', 'edit', NULL);
INSERT INTO config_param_system VALUES (69, 'edit_enable_arc_nodes_update', 'FALSE', 'boolean', 'edit', NULL);


	
INSERT INTO config_client_forms VALUES (3867, 'v_ui_element_x_gully', 5, true, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3870, 'v_ui_element_x_gully', 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3872, 'v_ui_element_x_gully', 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3874, 'v_ui_element_x_gully', 8, true, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3876, 'v_ui_element_x_gully', 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3894, 'v_ui_element_x_connec', 3, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3896, 'v_ui_element_x_connec', 4, true, 196, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3898, 'v_ui_element_x_connec', 5, true, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3900, 'v_ui_element_x_connec', 6, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3902, 'v_ui_element_x_connec', 7, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3904, 'v_ui_element_x_connec', 8, true, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (13200, 'v_ui_om_visit_x_arc', 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (14200, 'v_ui_om_visit_x_arc', 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (16000, 'v_ui_om_visit_x_arc', 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (27000, 'v_ui_om_visit_x_node', 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (31000, 'v_ui_om_visit_x_node', 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (32000, 'v_ui_om_visit_x_connec', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (33000, 'v_ui_om_visit_x_connec', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (34000, 'v_ui_om_visit_x_connec', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (35000, 'v_ui_om_visit_x_connec', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (36000, 'v_ui_om_visit_x_connec', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (8200, 'v_ui_om_visit_x_arc', 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (38000, 'v_ui_om_visit_x_connec', 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (41000, 'v_ui_om_visit_x_connec', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (42000, 'v_ui_om_visit_x_connec', 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (43000, 'v_ui_om_visit_x_connec', 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (44000, 'v_ui_om_visit_x_connec', 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (4120, 'v_ui_om_visit_x_arc', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3670, 'v_ui_element_x_arc', 8, true, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3640, 'v_ui_element_x_arc', 5, true, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3630, 'v_ui_element_x_arc', 4, true, 196, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3620, 'v_ui_element_x_arc', 3, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3810, 'v_ui_element_x_node', 4, true, 196, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3800, 'v_ui_element_x_node', 3, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3820, 'v_ui_element_x_node', 5, true, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3830, 'v_ui_element_x_node', 6, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3850, 'v_ui_element_x_node', 8, true, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (4040, 'v_rtc_scada_value', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (4080, 'v_rtc_scada_value', 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (4030, 'v_rtc_scada_value', 1, true, 120, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (4110, 'v_ui_om_visit_x_arc', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3960, 'v_rtc_scada', 1, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3970, 'v_rtc_scada', 2, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3980, 'v_rtc_scada', 3, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (4130, 'v_ui_om_visit_x_arc', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (4060, 'v_rtc_scada_value', 4, true, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (4050, 'v_rtc_scada_value', 3, true, 130, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3990, 'v_rtc_scada', 4, true, 224, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (4200, 'v_ui_om_visit_x_arc', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (4070, 'v_rtc_scada_value', 5, true, 174, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (5200, 'v_ui_om_visit_x_arc', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (7200, 'v_ui_om_visit_x_arc', 6, true, 120, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (9200, 'v_ui_om_visit_x_arc', 8, true, 165, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (10200, 'v_ui_om_visit_x_arc', 9, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (11200, 'v_ui_om_visit_x_arc', 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (22000, 'v_ui_om_visit_x_node', 6, true, 120, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (24000, 'v_ui_om_visit_x_node', 8, true, 160, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (25000, 'v_ui_om_visit_x_node', 9, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (28000, 'v_ui_om_visit_x_node', 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (29000, 'v_ui_om_visit_x_node', 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (30000, 'v_ui_om_visit_x_node', 14, true, 80, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (37000, 'v_ui_om_visit_x_connec', 6, true, 120, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3000, 'v_ui_doc_x_node', 5, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2950, 'v_ui_doc_x_arc', 9, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3100, 'v_ui_doc_x_connec', 6, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3130, 'v_ui_doc_x_connec', 9, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3070, 'v_ui_doc_x_connec', 3, true, 300, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (39000, 'v_ui_om_visit_x_connec', 8, true, 171, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (40000, 'v_ui_om_visit_x_connec', 9, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (45000, 'v_ui_om_visit_x_connec', 14, true, 90, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (46000, 'v_ui_om_visit_x_connec', 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (52000, 'v_ui_om_visit_x_gully', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (54000, 'v_ui_om_visit_x_gully', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (55000, 'v_ui_om_visit_x_gully', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (62000, 'v_ui_om_visit_x_gully', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (63000, 'v_ui_om_visit_x_gully', 6, true, 120, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (64000, 'v_ui_om_visit_x_gully', 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (65000, 'v_ui_om_visit_x_gully', 8, true, 171, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (66000, 'v_ui_om_visit_x_gully', 9, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (67000, 'v_ui_om_visit_x_gully', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (68000, 'v_ui_om_visit_x_gully', 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (69000, 'v_ui_om_visit_x_gully', 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (70000, 'v_ui_om_visit_x_gully', 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (71000, 'v_ui_om_visit_x_gully', 14, true, 90, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (72000, 'v_ui_om_visit_x_gully', 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (730, 'v_ui_doc_x_gully', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (740, 'v_ui_doc_x_gully', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (750, 'v_ui_doc_x_gully', 3, true, 300, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (760, 'v_ui_doc_x_gully', 4, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (770, 'v_ui_doc_x_gully', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (780, 'v_ui_doc_x_gully', 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (790, 'v_ui_doc_x_gully', 7, true, 81, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (800, 'v_ui_doc_x_gully', 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (810, 'v_ui_doc_x_gully', 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3862, 'v_ui_element_x_gully', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3863, 'v_ui_element_x_gully', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3864, 'v_ui_element_x_gully', 3, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3866, 'v_ui_element_x_gully', 4, true, 196, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3650, 'v_ui_element_x_arc', 6, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3840, 'v_ui_element_x_node', 7, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3610, 'v_ui_element_x_arc', 2, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3790, 'v_ui_element_x_node', 2, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3660, 'v_ui_element_x_arc', 7, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2890, 'v_ui_doc_x_arc', 3, true, 300, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3600, 'v_ui_element_x_arc', 1, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3780, 'v_ui_element_x_node', 1, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3680, 'v_ui_element_x_arc', 9, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3860, 'v_ui_element_x_node', 9, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3110, 'v_ui_doc_x_connec', 7, true, 81, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3080, 'v_ui_doc_x_connec', 4, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3060, 'v_ui_doc_x_connec', 2, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3050, 'v_ui_doc_x_connec', 1, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2940, 'v_ui_doc_x_arc', 8, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3090, 'v_ui_doc_x_connec', 5, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3120, 'v_ui_doc_x_connec', 8, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3270, 'v_edit_rtc_hydro_data_x_connec', 5, NULL, 140, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3280, 'v_edit_rtc_hydro_data_x_connec', 6, NULL, 140, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3230, 'v_edit_rtc_hydro_data_x_connec', 1, NULL, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3240, 'v_edit_rtc_hydro_data_x_connec', 2, NULL, 130, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3260, 'v_edit_rtc_hydro_data_x_connec', 4, NULL, 125, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2900, 'v_ui_doc_x_arc', 4, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2880, 'v_ui_doc_x_arc', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2870, 'v_ui_doc_x_arc', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2910, 'v_ui_doc_x_arc', 5, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2920, 'v_ui_doc_x_arc', 6, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2930, 'v_ui_doc_x_arc', 7, true, 81, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2970, 'v_ui_doc_x_node', 2, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2960, 'v_ui_doc_x_node', 1, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3250, 'v_edit_rtc_hydro_data_x_connec', 3, true, 125, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3292, 'v_edit_rtc_hydro_data_x_connec', 8, true, 120, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3294, 'v_edit_rtc_hydro_data_x_connec', 9, true, 120, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3290, 'v_edit_rtc_hydro_data_x_connec', 7, true, 160, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3300, 'v_rtc_hydrometer', 1, true, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3310, 'v_rtc_hydrometer', 2, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3330, 'v_rtc_hydrometer', 4, NULL, 130, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3350, 'v_rtc_hydrometer', 6, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3370, 'v_rtc_hydrometer', 8, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3380, 'v_rtc_hydrometer', 9, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3390, 'v_rtc_hydrometer', 10, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3400, 'v_rtc_hydrometer', 11, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3410, 'v_rtc_hydrometer', 12, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2990, 'v_ui_doc_x_node', 4, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3420, 'v_rtc_hydrometer', 13, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3320, 'v_rtc_hydrometer', 3, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3430, 'v_rtc_hydrometer', 14, NULL, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3360, 'v_rtc_hydrometer', 7, true, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3340, 'v_rtc_hydrometer', 5, true, 175, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3010, 'v_ui_doc_x_node', 6, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3030, 'v_ui_doc_x_node', 8, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3040, 'v_ui_doc_x_node', 9, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3020, 'v_ui_doc_x_node', 7, true, 81, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (2980, 'v_ui_doc_x_node', 3, true, 300, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (15000, 'v_ui_om_visit_x_arc', 14, true, 85, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (17000, 'v_ui_om_visit_x_node', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (18000, 'v_ui_om_visit_x_node', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (19000, 'v_ui_om_visit_x_node', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (20000, 'v_ui_om_visit_x_node', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (21000, 'v_ui_om_visit_x_node', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (23000, 'v_ui_om_visit_x_node', 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (26000, 'v_ui_om_visit_x_node', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (60000, 'v_ui_om_visit_x_gully', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3890, 'v_ui_element_x_connec', 1, NULL, 150, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3892, 'v_ui_element_x_connec', 2, NULL, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (3906, 'v_ui_element_x_connec', 9, NULL, 100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_client_forms VALUES (4100, 'v_ui_om_visit_x_arc', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

