/*
This file is part of Giswater
The program is free software: you can redistribute it and/or modify it under the terms of the GNU
General Public License as published by the Free Software Foundation, either version 3 of the License,
or (at your option) any later version.
*/

SET search_path = "SCHEMA_NAME", public, pg_catalog;

UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'v_ext_municipality', 've_municipality') WHERE dv_querytext LIKE '%v_ext_municipality%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'v_ext_streetaxis', 've_streetaxis') WHERE dv_querytext LIKE '%v_ext_streetaxis%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_municipality', 'v_municipality') WHERE dv_querytext LIKE '%ext_municipality%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_streetaxis', 'v_streetaxis') WHERE dv_querytext LIKE '%ext_streetaxis%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_address', 'v_address') WHERE dv_querytext LIKE '%ext_address%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_region', 'v_region') WHERE dv_querytext LIKE '%ext_region%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_province', 'v_province') WHERE dv_querytext LIKE '%ext_province%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_district', 'v_district') WHERE dv_querytext LIKE '%ext_district%';

UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'v_ext_municipality', 've_municipality')::json WHERE widgetcontrols::text LIKE '%v_ext_municipality%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'v_ext_streetaxis', 've_streetaxis')::json WHERE widgetcontrols::text LIKE '%v_ext_streetaxis%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_municipality', 'v_municipality')::json WHERE widgetcontrols::text LIKE '%ext_municipality%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_streetaxis', 'v_streetaxis')::json WHERE widgetcontrols::text LIKE '%ext_streetaxis%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_address', 'v_address')::json WHERE widgetcontrols::text LIKE '%ext_address%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_region', 'v_region')::json WHERE widgetcontrols::text LIKE '%ext_region%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_province', 'v_province')::json WHERE widgetcontrols::text LIKE '%ext_province%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_district', 'v_district')::json WHERE widgetcontrols::text LIKE '%ext_district%';

UPDATE config_form_fields SET iseditable = false where formname ilike 've_node_%' and columnname = 'state';
UPDATE config_form_fields SET iseditable = false where formname ilike 've_arc_%' and columnname = 'state';
UPDATE config_form_fields SET iseditable = false where formname ilike 've_connec_%' and columnname = 'state';
UPDATE config_form_fields SET iseditable = false where formname ilike 've_link_%' and columnname = 'state';

UPDATE config_form_fields SET hidden = TRUE WHERE formname = 've_node_pump' AND columnname = 'expl_visibility';

UPDATE config_form_fields SET layoutorder = 14 WHERE formname = 've_element' AND columnname = 'rotation';
UPDATE config_form_fields SET layoutorder = 15 WHERE formname = 've_element' AND columnname = 'model_id';

UPDATE config_form_fields SET dv_querytext='SELECT function_type AS id, function_type AS idval FROM man_type_function WHERE active AND (featurecat_id IS NULL AND ''ELEMENT''=ANY(feature_type))' WHERE formname='ve_element' AND formtype='form_feature' AND columnname='function_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT function_type AS id, function_type AS idval FROM man_type_function WHERE active AND (featurecat_id IS NULL AND ''CONNEC''=ANY(feature_type))' WHERE formname='ve_connec' AND formtype='form_feature' AND columnname='function_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT function_type AS id, function_type AS idval FROM man_type_function WHERE active AND (featurecat_id IS NULL AND ''NODE''=ANY(feature_type))' WHERE formname='ve_node' AND formtype='form_feature' AND columnname='function_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT function_type AS id, function_type AS idval FROM man_type_function WHERE active AND (featurecat_id IS NULL AND ''ARC''=ANY(feature_type))' WHERE formname='ve_arc' AND formtype='form_feature' AND columnname='function_type' AND tabname='tab_data';

UPDATE config_form_fields SET dv_querytext='SELECT category_type AS id, category_type AS idval FROM man_type_category WHERE active AND (featurecat_id IS NULL AND ''ARC''=ANY(feature_type))' WHERE formname='ve_arc' AND formtype='form_feature' AND columnname='category_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT category_type AS id, category_type AS idval FROM man_type_category WHERE active AND (featurecat_id IS NULL AND ''CONNEC''=ANY(feature_type))' WHERE formname='ve_connec' AND formtype='form_feature' AND columnname='category_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT category_type AS id, category_type AS idval FROM man_type_category WHERE active AND (featurecat_id IS NULL AND ''ELEMENT''=ANY(feature_type))' WHERE formname='ve_element' AND formtype='form_feature' AND columnname='category_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT category_type AS id, category_type AS idval FROM man_type_category WHERE active AND (featurecat_id IS NULL AND ''NODE''=ANY(feature_type))' WHERE formname='ve_node' AND formtype='form_feature' AND columnname='category_type' AND tabname='tab_data';

UPDATE config_form_fields SET dv_querytext='SELECT location_type AS id, location_type AS idval FROM man_type_location WHERE active AND (featurecat_id IS NULL AND ''ARC''=ANY(feature_type))' WHERE formname='ve_arc' AND formtype='form_feature' AND columnname='location_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT location_type AS id, location_type AS idval FROM man_type_location WHERE active AND (featurecat_id IS NULL AND ''CONNEC''=ANY(feature_type))' WHERE formname='ve_connec' AND formtype='form_feature' AND columnname='location_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT location_type AS id, location_type AS idval FROM man_type_location WHERE active AND (featurecat_id IS NULL AND ''ELEMENT''=ANY(feature_type))' WHERE formname='ve_element' AND formtype='form_feature' AND columnname='location_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT location_type AS id, location_type AS idval FROM man_type_location WHERE active AND (featurecat_id IS NULL AND ''NODE''=ANY(feature_type))' WHERE formname='ve_node' AND formtype='form_feature' AND columnname='location_type' AND tabname='tab_data';

UPDATE config_form_fields SET dv_querytext='SELECT fluid_type AS id, fluid_type AS idval FROM man_type_fluid WHERE active AND (featurecat_id IS NULL AND ''ARC''=ANY(feature_type))' WHERE formname='ve_arc' AND formtype='form_feature' AND columnname='fluid_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT fluid_type AS id, fluid_type AS idval FROM man_type_fluid WHERE active AND (featurecat_id IS NULL AND ''CONNEC''=ANY(feature_type))' WHERE formname='ve_connec' AND formtype='form_feature' AND columnname='fluid_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT fluid_type AS id, fluid_type AS idval FROM man_type_fluid WHERE active AND (featurecat_id IS NULL AND ''ELEMENT''=ANY(feature_type))' WHERE formname='ve_element' AND formtype='form_feature' AND columnname='fluid_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT fluid_type AS id, fluid_type AS idval FROM man_type_fluid WHERE active AND (featurecat_id IS NULL AND ''NODE''=ANY(feature_type))' WHERE formname='ve_node' AND formtype='form_feature' AND columnname='fluid_type' AND tabname='tab_data';

UPDATE config_form_fields
SET dv_querytext='SELECT crmzone_id AS id, name AS idval FROM crmzone WHERE crmzone_id IS NOT NULL AND active'
WHERE formname ILIKE 've_connec%' AND formtype='form_feature' AND columnname='crmzone_id' AND tabname='tab_data';

UPDATE config_form_fields SET dv_querytext = 'SELECT id, id as idval FROM cat_element WHERE active IS true'
WHERE formname = 've_element' AND columnname = 'elementcat_id';
	
UPDATE config_form_fields t SET dv_querytext = a.dv_querytext FROM (
    SELECT CONCAT('SELECT id, id as idval FROM cat_element WHERE active IS true AND element_type = ', quote_literal(upper(split_part(formname, '_', 3)))) AS dv_querytext, formname
    FROM config_form_fields WHERE formname ilike 've_element_%' AND dv_querytext IS NOT NULL AND columnname = 'elementcat_id'
)a WHERE t.formname = a.formname and t.columnname = 'elementcat_id';


UPDATE config_form_fields SET layoutorder = layoutorder+1 WHERE layoutname = 'lyt_epa_data_2' AND formname IN ('ve_epa_valve', 've_epa_shortpipe', 've_epa_pump', 've_epa_pump_additional');

INSERT INTO config_form_fields(formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, iseditable) VALUES('ve_epa_pump', 'form_feature', 'tab_epa', 'nodarc_id', 'lyt_epa_data_2', 1, 'string', 'text', 'Nodarc id:', 'Nodarc id', false) ON CONFLICT DO NOTHING;
INSERT INTO config_form_fields(formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, iseditable) VALUES('ve_epa_pump_additional', 'form_feature', 'tab_epa', 'nodarc_id', 'lyt_epa_data_2', 1, 'string', 'text', 'Nodarc id:', 'Nodarc id', false) ON CONFLICT DO NOTHING;
INSERT INTO config_form_fields(formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, iseditable) VALUES('ve_epa_shortpipe', 'form_feature', 'tab_epa', 'nodarc_id', 'lyt_epa_data_2', 1, 'string', 'text', 'Nodarc id:', 'Nodarc id', false) ON CONFLICT DO NOTHING;
INSERT INTO config_form_fields(formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, iseditable) VALUES('ve_epa_valve', 'form_feature', 'tab_epa', 'nodarc_id', 'lyt_epa_data_2', 1, 'string', 'text', 'Nodarc id:', 'Nodarc id', false) ON CONFLICT DO NOTHING;

INSERT INTO config_form_fields (formname,formtype,tabname,columnname,layoutname,layoutorder,"datatype",widgettype,"label",tooltip,placeholder,ismandatory,isparent,iseditable,isautoupdate,isfilter,dv_querytext,dv_orderby_id,dv_isnullvalue,dv_parent_id,dv_querytext_filterc,stylesheet,widgetcontrols,widgetfunction,linkedobject,hidden,web_layoutorder) VALUES
	 ('ve_connec_samplepoint','form_feature','tab_data','sector_id','lyt_bot_1',1,'integer','combo','Sector id:','Sector_id - Hydraulic sector identifier related to the primary key of sector table',NULL,false,false,true,false,NULL,'SELECT sector_id as id,name as idval FROM sector WHERE sector_id IS NOT NULL AND active IS TRUE ',true,false,NULL,NULL,'{"label":"color:blue; font-weight:bold;"}','{"setMultiline": false, "labelPosition": "top", "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "valueColumn": "name", "filterExpression": null}}',NULL,NULL,false,5),
	 ('ve_connec_samplepoint','form_feature','tab_data','dma_id','lyt_bot_1',2,'integer','combo','Dma','Dma_id',NULL,false,false,true,false,NULL,'SELECT dma_id as id, name as idval FROM dma WHERE dma_id = 0 UNION SELECT dma_id as id, name as idval FROM dma WHERE dma_id IS NOT NULL AND active IS TRUE ',true,false,'expl_id',' AND dma.expl_id',NULL,'{"setMultiline": false, "labelPosition": "top", "valueRelation": {"layer": "ve_dma", "activated": true, "keyColumn": "dma_id", "nullValue": false, "valueColumn": "name", "filterExpression": null}}',NULL,NULL,false,6),
	 ('ve_connec_samplepoint','form_feature','tab_data','state','lyt_bot_1',3,'integer','combo','State:','State - Domain value of connect''s state.',NULL,false,true,false,false,NULL,'WITH psector_value AS (
  		SELECT value::integer AS psector_value 
  		FROM config_param_user 
  		WHERE parameter = ''plan_psector_current'' AND cur_user = current_user),
	 tg_op_value AS (
  		SELECT value::text AS tg_op_value 
  		FROM config_param_user 
  		WHERE parameter = ''utils_transaction_mode'' AND cur_user = current_user)  
SELECT id::integer as id, name as idval
FROM value_state 
WHERE id IS NOT NULL 
AND CASE 
  WHEN (SELECT tg_op_value FROM tg_op_value)!=''INSERT'' THEN id IN (0,1,2)
  WHEN (SELECT tg_op_value FROM tg_op_value) =''INSERT'' AND (SELECT psector_value FROM psector_value) IS NOT NULL THEN id = 2 
  ELSE id < 2 
END',true,false,NULL,NULL,NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,false,7),
	 ('ve_connec_samplepoint','form_feature','tab_data','state_type','lyt_bot_1',4,'integer','combo','State type:','State_type - The state type of the element. It allows to obtain more detail of the state. To select from those available depending on the chosen state',NULL,false,false,true,false,NULL,'SELECT id, name as idval FROM value_state_type WHERE id IS NOT NULL',true,false,'state',' AND value_state_type.state',NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,false,8),
	 ('ve_connec_samplepoint','form_feature','tab_data','code','lyt_data_1',1,'text','text','Code:','Code',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,9),
	 ('ve_connec_samplepoint','form_feature','tab_data','top_elev','lyt_data_1',2,'double','text','Top elevation:','Top_elev - Elevation of the connec in ft or m.',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,10),
	 ('ve_connec_samplepoint','form_feature','tab_data','depth','lyt_data_1',3,'double','text','Depth:','Depth - Depth of the element in meters',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,11),
	 ('ve_connec_samplepoint','form_feature','tab_data','sys_type','lyt_data_1',4,'string','text','Sys type:','Sys_type',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,12),
	 ('ve_connec_samplepoint','form_feature','tab_data','datasource','lyt_data_1',5,'integer','combo','Datasource:','Datasource',NULL,false,false,true,false,NULL,'SELECT id, idval FROM edit_typevalue WHERE typevalue = ''value_datasource''',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,13),
	 ('ve_connec_samplepoint','form_feature','tab_data','cat_matcat_id','lyt_data_1',6,'string','text','Cat matcat id:','Cat_matcat_id',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,14),
	 ('ve_connec_samplepoint','form_feature','tab_data','connec_length','lyt_data_1',7,'double','text','Connec length:','Connec_length - Length of the connection',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,15),
	 ('ve_connec_samplepoint','form_feature','tab_data','cat_pnom','lyt_data_1',8,'string','text','Cat pnom:','Cat_pnom',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,16),
	 ('ve_connec_samplepoint','form_feature','tab_data','cat_dnom','lyt_data_1',9,'string','text','Cat dnom:','Cat_dnom',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,17),
	 ('ve_connec_samplepoint','form_feature','tab_data','workcat_id','lyt_data_1',10,'string','typeahead','Workcat id:','Workcat_id',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_work WHERE id IS NOT NULL AND active IS TRUE ',NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,'action_workcat',false,18),
	 ('ve_connec_samplepoint','form_feature','tab_data','builtdate','lyt_data_1',11,'date','datetime','Builtdate:','Builtdate',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,19),
	 ('ve_connec_samplepoint','form_feature','tab_data','ownercat_id','lyt_data_1',12,'string','combo','Owner:','Ownercat_id - id of the owner related to connect.',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_owner WHERE id IS NOT NULL AND active IS TRUE ',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,20),
	 ('ve_connec_samplepoint','form_feature','tab_data','workcat_id_end','lyt_data_1',13,'string','typeahead','Workcat id end:','Workcat_id_end - id of the  end of construction work.','Only when state is obsolete',false,false,true,false,NULL,'SELECT id, id as idval FROM cat_work WHERE id IS NOT NULL AND active IS TRUE ',NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,21),
	 ('ve_connec_samplepoint','form_feature','tab_data','enddate','lyt_data_1',14,'date','datetime','Enddate:','Enddate',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,22),
	 ('ve_connec_samplepoint','form_feature','tab_data','minsector_id','lyt_data_1',15,'integer','text','Minsector id:','Minsector_id',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,23),
	 ('ve_connec_samplepoint','form_feature','tab_data','macrodqa_id','lyt_data_1',16,'integer','combo','Macrodqa id:','Macrodqa id',NULL,false,false,false,false,NULL,'SELECT macrodqa_id as id, name as idval FROM macrodqa WHERE macrodqa_id IS NOT NULL  AND active IS TRUE ',true,false,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,24),
	 ('ve_connec_samplepoint','form_feature','tab_data','dqa_id','lyt_data_1',17,'integer','combo','Dqa:','Dqa_id',NULL,false,false,false,false,NULL,'SELECT dqa_id as id, name as idval FROM dqa WHERE dqa_id IS NOT NULL  AND active IS TRUE ',true,false,NULL,NULL,NULL,'{"setMultiline": false, "valueRelation":{"nullValue":false, "layer": "ve_dqa", "activated": true, "keyColumn": "dqa_id", "valueColumn": "name", "filterExpression": null}}',NULL,NULL,false,25),
	 ('ve_connec_samplepoint','form_feature','tab_data','staticpressure','lyt_data_1',18,'integer','text','Staticpressure:','Staticpressure',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,26),
	 ('ve_connec_samplepoint','form_feature','tab_data','macrodma_id','lyt_data_1',19,'integer','text','Macrodma id:','Macrodma_id',NULL,false,false,false,false,NULL,'SELECT macrodma_id as id, name as idval FROM macrodma where macrodma_id is not null  AND active IS TRUE ',NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,27),
	 ('ve_connec_samplepoint','form_feature','tab_data','macrosector_id','lyt_data_1',20,'integer','combo','Macrosector id:','Macrosector_id',NULL,false,false,false,false,NULL,'SELECT macrosector_id as id, name as idval FROM macrosector where macrosector_id is not null AND active IS TRUE ',true,false,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,28),
	 ('ve_connec_samplepoint','form_feature','tab_data','link','lyt_data_1',21,'string','hyperlink','Link:','Link',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}','{"functionName": "open_url"}','action_link',false,29),
	 ('ve_connec_samplepoint','form_feature','tab_data','n_hydrometer','lyt_data_1',22,'integer','text','N hydrometer:','N_hydrometer',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,30),
	 ('ve_connec_samplepoint','form_feature','tab_data','om_state','lyt_data_1',27,'string','text','Om state:','Om_state',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,35),
	 ('ve_connec_samplepoint','form_feature','tab_data','conserv_state','lyt_data_1',28,'string','text','Conserv state:','Conserv_state',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,36),
	 ('ve_connec_samplepoint','form_feature','tab_data','access_type','lyt_data_1',29,'string','text','Access type:','Access_type',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,37),
	 ('ve_connec_samplepoint','form_feature','tab_data','placement_type','lyt_data_1',30,'string','text','Placement Type:','Placement Type',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,38),
	 ('ve_connec_samplepoint','form_feature','tab_data','priority','lyt_data_1',31,'string','text','Priority:','Priority',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,39),
	 ('ve_connec_samplepoint','form_feature','tab_data','crmzone_name','lyt_data_1',35,'string','text','Crmzone name:','Crmzone_name',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,43),
	 ('ve_connec_samplepoint','form_feature','tab_data','plot_code','lyt_data_1',36,'text','text','Plot code:','Plot_code',NULL,false,NULL,true,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,44),
	 ('ve_connec_samplepoint','form_feature','tab_data','serial_number','lyt_data_1',39,'text','text','Serial number:','Serial_number',NULL,false,NULL,true,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,45),
	 ('ve_connec_samplepoint','form_feature','tab_data','label_quadrant','lyt_data_1',40,'text','combo','Label quadrant:','Label_quadrant',NULL,false,NULL,true,NULL,NULL,'select id, idval from edit_typevalue where typevalue = ''label_quadrant''',NULL,true,NULL,NULL,NULL,NULL,NULL,NULL,false,46),
	 ('ve_connec_samplepoint','form_feature','tab_data','cat_dint','lyt_data_1',43,'string','text','Cat dint:','Cat_dint',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,49),
	 ('ve_connec_samplepoint','form_feature','tab_data','supplyzone_id','lyt_data_1',44,'text','text','Supplyzone id:','Supplyzone_id',NULL,false,NULL,true,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,50),
	 ('ve_connec_samplepoint','form_feature','tab_data','n_inhabitants','lyt_data_1',49,'integer','text','N inhabitants:','N_inhabitants',NULL,false,NULL,true,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,55),
	 ('ve_connec_samplepoint','form_feature','tab_data','lock_level','lyt_data_1',50,'integer','combo','Lock level:','Lock_level',NULL,false,NULL,true,NULL,NULL,'SELECT id, idval FROM edit_typevalue WHERE typevalue = ''value_lock_level''',true,true,NULL,NULL,NULL,NULL,NULL,NULL,false,56),
	 ('ve_connec_samplepoint','form_feature','tab_data','block_code','lyt_data_1',51,'text','text','Block code:','Block_code',NULL,false,NULL,true,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,57),
	 ('ve_connec_samplepoint','form_feature','tab_data','cabinet','lyt_data_1',52,'string','text','cabinet',NULL,NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','lab_code','lyt_data_1',53,'string','text','lab_code',NULL,NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','place_name','lyt_data_1',54,'string','text','place_name',NULL,NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','macroexpl_id','lyt_data_1',NULL,'text','text','Macroexploitation:','Macroexpl_id',NULL,true,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,59),
	 ('ve_connec_samplepoint','form_feature','tab_data','customer_code','lyt_data_2',1,'string','text','Customer code:','Customer_code - Account code',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,60),
	 ('ve_connec_samplepoint','form_feature','tab_data','soilcat_id','lyt_data_2',2,'string','combo','Soilcat id:','Soilcat_id - id of the soil related to the connect.',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_soil WHERE id IS NOT NULL AND active IS TRUE ',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,61),
	 ('ve_connec_samplepoint','form_feature','tab_data','function_type','lyt_data_2',5,'string','combo','Function type:','Function_type',NULL,false,false,true,false,NULL,'SELECT function_type as id, function_type as idval FROM man_type_function WHERE ((featurecat_id is null AND ''CONNEC''=ANY(feature_type)) ) AND active IS TRUE  OR ''SAMPLEPOINT'' = ANY(featurecat_id::text[])',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,64),
	 ('ve_connec_samplepoint','form_feature','tab_data','category_type','lyt_data_2',6,'string','combo','Category type:','Category_type',NULL,false,false,true,false,NULL,'SELECT category_type as id, category_type as idval FROM man_type_category WHERE ((featurecat_id is null AND ''CONNEC''=ANY(feature_type))) AND active IS TRUE  OR ''SAMPLEPOINT'' = ANY(featurecat_id::text[])',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,65),
	 ('ve_connec_samplepoint','form_feature','tab_data','fluid_type','lyt_data_2',7,'string','combo','Fluid type:','Fluid_type - Tipo de fluido a escoger en el desplegable personalizado por el usuario en la tabla man_type_fluid',NULL,false,false,false,false,NULL,'SELECT fluid_type as id, fluid_type as idval FROM man_type_fluid WHERE ((featurecat_id is null AND ''CONNEC''=ANY(feature_type)) ) AND active IS TRUE  OR ''SAMPLEPOINT'' = ANY(featurecat_id::text[])',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,66),
	 ('ve_connec_samplepoint','form_feature','tab_data','location_type','lyt_data_2',8,'string','combo','Location type:','Location_type',NULL,false,false,true,false,NULL,'SELECT location_type as id, location_type as idval FROM man_type_location WHERE ((featurecat_id is null AND ''CONNEC''=ANY(feature_type)) ) AND active IS TRUE  OR ''SAMPLEPOINT'' = ANY(featurecat_id::text[])',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,67),
	 ('ve_connec_samplepoint','form_feature','tab_data','comment','lyt_data_2',9,'string','text','Comment:','Comment - Optional field to add comments about the element',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,68),
	 ('ve_connec_samplepoint','form_feature','tab_data','num_value','lyt_data_2',10,'double','text','Number value:','Number value',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,69),
	 ('ve_connec_samplepoint','form_feature','tab_data','label','lyt_data_2',11,'string','text','Catalog label:','Label - Label from the catalog of connecs, therefore it will not be editable in the form',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,70),
	 ('ve_connec_samplepoint','form_feature','tab_data','label_x','lyt_data_2',12,'string','text','Label x:','Label_x - X coordinate of the label''s location',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,71),
	 ('ve_connec_samplepoint','form_feature','tab_data','label_y','lyt_data_2',13,'string','text','Label y:','Label_y',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,72),
	 ('ve_connec_samplepoint','form_feature','tab_data','label_rotation','lyt_data_2',14,'double','text','Label rotation:','Label_rotation - Angle of rotation of the label',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,73),
	 ('ve_connec_samplepoint','form_feature','tab_data','rotation','lyt_data_2',15,'double','text','Rotation:','Rotation',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,74),
	 ('ve_connec_samplepoint','form_feature','tab_data','publish','lyt_data_2',16,'boolean','check','Publish:','Publish - To set if the element is published or should be',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,75),
	 ('ve_connec_samplepoint','form_feature','tab_data','svg','lyt_data_2',17,'string','text','Svg:','Svg - In case of using svg symbology, the path to the file containing the symbology is shown',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,76),
	 ('ve_connec_samplepoint','form_feature','tab_data','inventory','lyt_data_2',18,'boolean','check','Inventory:','Inventory',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,77),
	 ('ve_connec_samplepoint','form_feature','tab_data','verified','lyt_data_2',19,'integer','combo','Verified:','Verified',NULL,false,false,true,false,NULL,'SELECT id, idval FROM edit_typevalue WHERE typevalue = ''value_verified''',true,true,NULL,NULL,NULL,'{"setMultiline": false}',NULL,NULL,false,78),
	 ('ve_connec_samplepoint','form_feature','tab_data','presszone_id','lyt_data_2',20,'integer','combo','Presszone:','Presszonecat_id - Related to the pressure zone catalog',NULL,false,false,true,false,NULL,'SELECT presszone.presszone_id as id, name as idval FROM presszone WHERE presszone_id=''0'' UNION SELECT presszone.presszone_id AS id, presszone.name AS idval FROM presszone WHERE presszone_id IS NOT NULL AND active IS TRUE ',true,false,'expl_id',' AND presszone.expl_id',NULL,'{"setMultiline": false, "valueRelation": {"layer": "ve_presszone", "activated": true, "keyColumn": "presszone_id", "nullValue": false, "valueColumn": "name", "filterExpression": null}}',NULL,NULL,false,79),
	 ('ve_connec_samplepoint','form_feature','tab_data','expl_id','lyt_data_2',23,'integer','combo','Exploitation id:','Expl_id - Exploitation to which the element belongs. If the configuration is not changed, the program automatically selects it based on the geometry',NULL,false,true,true,false,NULL,'SELECT expl_id as id, name as idval FROM exploitation WHERE expl_id IS NOT NULL',true,false,NULL,NULL,'{"label":"color:green; font-weight:bold;"}','{"setMultiline": false, "valueRelation": {"layer": "ve_exploitation", "activated": true, "keyColumn": "expl_id", "nullValue": false, "valueColumn": "name", "filterExpression": null}}',NULL,NULL,false,82),
	 ('ve_connec_samplepoint','form_feature','tab_data','workcat_id_plan','lyt_data_2',24,'string','typeahead','Workcat id plan:','Workcat_id_plan',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_work WHERE id IS NOT NULL',NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,83),
	 ('ve_connec_samplepoint','form_feature','tab_data','asset_id','lyt_data_2',25,'string','text','Asset id:','Asset_id',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,84),
	 ('ve_connec_samplepoint','form_feature','tab_data','press_max','lyt_data_2',26,'numeric','text','Press max:','Press_max',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,85),
	 ('ve_connec_samplepoint','form_feature','tab_data','press_min','lyt_data_2',27,'numeric','text','Press min:','Press_min',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,86),
	 ('ve_connec_samplepoint','form_feature','tab_data','press_avg','lyt_data_2',28,'numeric','text','Press avg:','Press_avg',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,87),
	 ('ve_connec_samplepoint','form_feature','tab_data','crmzone_id','lyt_data_2',30,'string','combo','Crmzone id:','Crmzone_id',NULL,false,false,true,false,NULL,'SELECT crmzone_id AS id, name AS idval FROM crmzone WHERE crmzone_id IS NOT NULL AND active',true,true,NULL,NULL,NULL,NULL,NULL,NULL,false,89),
	 ('ve_connec_samplepoint','form_feature','tab_data','brand_id','lyt_data_2',34,'text','combo','Brand:','Brand_id',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_brand WHERE ''SAMPLEPOINT'' = ANY(featurecat_id::text[]) OR featurecat_id IS NULL',NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,91),
	 ('ve_connec_samplepoint','form_feature','tab_data','model_id','lyt_data_2',35,'text','combo','Model:','Model_id',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_brand_model WHERE ''SAMPLEPOINT'' = ANY(featurecat_id::text[]) OR featurecat_id IS NULL',NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,92),
	 ('ve_connec_samplepoint','form_feature','tab_data','expl_visibility','lyt_data_2',43,'text','text','Expl id visibility:','Expl_id visibility',NULL,false,false,true,false,NULL,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0',NULL,NULL,NULL,NULL,NULL,'{"setMultiline": false}',NULL,NULL,false,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','uncertain','lyt_data_2',44,'boolean','check','Uncertain:','Uncertain',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline": false}',NULL,NULL,true,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','sys_code','lyt_data_2',45,'text','text','Sys code:','Sys code',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline": false}',NULL,NULL,true,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','uuid','lyt_data_2',46,'text','text','Uuid:','Uuid',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline": false}',NULL,NULL,true,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','xyz_date','lyt_data_2',47,'date','text','Xyz date:','Xyz date',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline": false}',NULL,NULL,true,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','muni_id','lyt_data_3',1,'integer','combo','Municipality:','Muni_id - Municipality to which the element belongs. If the configuration is not modified, the program automatically selects it based on the geometry',NULL,false,true,true,false,NULL,'SELECT muni_id as id, name as idval from ve_municipality WHERE muni_id IS NOT NULL',true,false,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,93),
	 ('ve_connec_samplepoint','form_feature','tab_data','postcode','lyt_data_3',2,'string','text','Postcode:','Postcode - Postal code of the municipality',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,94),
	 ('ve_connec_samplepoint','form_feature','tab_data','district_id','lyt_data_3',3,'integer','combo','District:','District_id - identifier of the neighborhood with which the element is linked. To choose from those available in the drop-down (it is filtered according to the selected municipality)',NULL,false,false,true,false,NULL,'SELECT a.district_id AS id, a.name AS idval FROM v_district a JOIN v_municipality m USING (muni_id) WHERE district_id IS NOT NULL ',NULL,true,'muni_id',' AND m.muni_id',NULL,'{"setMultiline":false}',NULL,NULL,false,95),
	 ('ve_connec_samplepoint','form_feature','tab_data','streetaxis_id','lyt_data_3',4,'string','typeahead','Streetname:','Streetname',NULL,false,false,true,false,NULL,'SELECT id AS id, a.descript AS idval FROM ve_streetaxis a JOIN v_municipality m USING (muni_id) WHERE id IS NOT NULL',NULL,true,'muni_id',' AND m.name',NULL,'{"setMultiline":false}',NULL,NULL,false,96),
	 ('ve_connec_samplepoint','form_feature','tab_data','postnumber','lyt_data_3',5,'integer','typeahead','Street number:','Postnumber - Street number',NULL,false,false,true,false,NULL,'SELECT a.postnumber AS id, a.postnumber AS idval FROM v_address a JOIN v_streetaxis m ON streetaxis_id=m.id WHERE a.id IS NOT NULL',NULL,NULL,'streetname',' AND m.name',NULL,'{"setMultiline":false}',NULL,NULL,false,97),
	 ('ve_connec_samplepoint','form_feature','tab_data','postcomplement','lyt_data_3',6,'string','text','Optional complement of the street number:','Postcomplement - Optional complement of the street number',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,98),
	 ('ve_connec_samplepoint','form_feature','tab_data','streetaxis2_id','lyt_data_3',7,'string','typeahead','Streetname2:','Streetname2',NULL,false,false,true,false,NULL,'SELECT id AS id, a.descript AS idval FROM ve_streetaxis a JOIN v_municipality m USING (muni_id) WHERE id IS NOT NULL',NULL,true,'muni_id',' AND m.name',NULL,'{"setMultiline":false}',NULL,NULL,false,99),
	 ('ve_connec_samplepoint','form_feature','tab_data','postnumber2','lyt_data_3',8,'integer','typeahead','Second street number:','Postnumber2 - Second street number',NULL,false,false,true,false,NULL,'SELECT a.postnumber AS id, a.postnumber AS idval FROM v_address a JOIN v_streetaxis m ON streetaxis_id=m.id WHERE a.id IS NOT NULL',NULL,NULL,'streetname2',' AND m.name',NULL,'{"setMultiline":false}',NULL,NULL,false,100),
	 ('ve_connec_samplepoint','form_feature','tab_data','postcomplement2','lyt_data_3',9,'string','text','Postcomplement2:','Postcomplement2',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,101),
	 ('ve_connec_samplepoint','form_feature','tab_data','region_id','lyt_data_3',10,'integer','combo','Region:','Region_id',NULL,false,false,false,false,NULL,'SELECT region_id as id, name as idval FROM v_region WHERE region_id IS NOT NULL',true,true,NULL,NULL,NULL,NULL,NULL,NULL,true,102),
	 ('ve_connec_samplepoint','form_feature','tab_data','province_id','lyt_data_3',11,'integer','combo','Province:','Province_id',NULL,false,false,false,false,NULL,'SELECT province_id as id, name as idval FROM v_province WHERE province_id IS NOT NULL',true,true,NULL,NULL,NULL,NULL,NULL,NULL,true,103),
	 ('ve_connec_samplepoint','form_feature','tab_data','pjoint_id','lyt_data_3',12,'string','text','Junction point id:','Pjoint_id - identifier of the connection point with the network',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,104),
	 ('ve_connec_samplepoint','form_feature','tab_data','pjoint_type','lyt_data_3',13,'string','text','Pjoint type:','Pjoint_type',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,105),
	 ('ve_connec_samplepoint','form_feature','tab_data','descript','lyt_data_3',14,'string','text','Descript:','Descript',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,106),
	 ('ve_connec_samplepoint','form_feature','tab_data','annotation','lyt_data_3',15,'string','text','Annotation:','Annotation - Annotations related to connec. Additional information',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,107),
	 ('ve_connec_samplepoint','form_feature','tab_data','observ','lyt_data_3',16,'string','text','Observation:','Observ - Observations related to connect. Additional information',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,108),
	 ('ve_connec_samplepoint','form_feature','tab_data','connec_id','lyt_none',1,'string','text','Connec id:','Connec_id - identifier of the connec. It is not necessary to enter it, it is an automatic serial',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,false,109),
	 ('ve_connec_samplepoint','form_feature','tab_data','connec_type','lyt_top_1',1,'string','text','Connec type:','Connec_type',NULL,false,true,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,false,1),
	 ('ve_connec_samplepoint','form_feature','tab_data','conneccat_id','lyt_top_1',2,'string','typeahead','Conneccat id:','Conneccat_id',NULL,true,false,true,false,NULL,'SELECT id, id as idval FROM cat_connec WHERE id IS NOT NULL AND active IS TRUE ',NULL,NULL,'connec_type',' AND connec_type',NULL,'{"setMultiline": false, "labelPosition": "top", "valueRelation": {"layer": "cat_connec", "activated": true, "keyColumn": "id", "nullValue": false, "valueColumn": "id", "filterExpression": null}}',NULL,'action_catalog',false,2),
	 ('ve_connec_samplepoint','form_feature','tab_data','arc_id','lyt_top_1',3,'string','typeahead','Arc id:','Arc identifier',NULL,false,false,false,false,NULL,'SELECT arc_id as id, arc_id as idval FROM arc WHERE arc_id IS NOT NULL',NULL,true,NULL,NULL,NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,false,3),
	 ('ve_connec_samplepoint','form_feature','tab_data','epa_type','lyt_top_1',4,'string','combo','Epa type:','Epa type',NULL,true,false,true,true,NULL,'SELECT id, id as idval FROM sys_feature_epa_type WHERE active IS TRUE AND feature_type = ''CONNEC''',true,false,NULL,NULL,NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,false,4),
	 ('ve_connec_samplepoint','form_feature','tab_data','dma_style',NULL,NULL,'text','text','Dma color:','Dma_style',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,110),
	 ('ve_connec_samplepoint','form_feature','tab_data','presszone_style',NULL,NULL,'text','text','Presszone color:','Presszone_style',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,114),
	 ('ve_connec_samplepoint','form_feature','tab_data','adate',NULL,NULL,'text','text','Adate:','Adate',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,112),
	 ('ve_connec_samplepoint','form_feature','tab_data','adescript',NULL,NULL,'text','text','Adescript:','Adescript',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,111),
	 ('ve_connec_samplepoint','form_feature','tab_data','accessibility',NULL,NULL,'integer','text','Accessibility:','Accessibility - Acceso al elemento',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,113);
