
/*
This file is part of Giswater 3
The program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This version of Giswater is provided by Giswater Association
*/


SET search_path = SCHEMA_NAME, public, pg_catalog;

--09/07/2019

INSERT INTO config_api_form_fields VALUES (100003, 'new_workcat', 'catalog', 'link', 1, 3, true, 'string', 'text', 'link:', NULL, NULL, 'Ex.:link', NULL, NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100005, 'new_workcat', 'catalog', 'workid_key_2', 1, 5, true, 'string', 'text', 'workid key 2:', NULL, NULL, 'Ex.:workid_key2', NULL, NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100006, 'new_workcat', 'catalog', 'builtdate', 1, 6, true, 'date', 'datepickertime', 'builtdate:', NULL, NULL, 'Ex.:builtdate', NULL, NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100002, 'new_workcat', 'catalog', 'descript', 1, 2, true, 'string', 'text', 'description:', NULL, NULL, 'Ex.:descript', NULL, NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100004, 'new_workcat', 'catalog', 'workid_key_1', 1, 4, true, 'string', 'text', 'workid key 1:', NULL, NULL, 'Ex.:workid_key1', NULL, NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100010, 'upsert_catalog_arc', 'catalog', 'id', 1, 4, true, 'string', 'combo', 'id:', NULL, NULL, 'Ex.:id', NULL, NULL, false, false, true, false, 'SELECT DISTINCT (id) AS id, id AS idval FROM cat_arc WHERE id IS NOT NULL', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100014, 'upsert_catalog_connec', 'catalog', 'id', 1, 4, true, 'string', 'combo', 'id:', NULL, NULL, 'Ex.:id', NULL, NULL, false, false, true, false, 'SELECT DISTINCT (id) AS id, id AS idval FROM cat_connec WHERE id IS NOT NULL', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100018, 'upsert_catalog_node', 'catalog', 'id', 1, 4, true, 'string', 'combo', 'id:', NULL, NULL, 'Ex.:id', NULL, NULL, false, false, true, false, 'SELECT DISTINCT (id) AS id, id AS idval FROM cat_node WHERE id IS NOT NULL', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100001, 'new_workcat', 'catalog', 'cat_work_id', 1, 1, true, 'string', 'typeahead', 'work id:', NULL, NULL, 'Ex.:work_id', NULL, NULL, false, false, true, false, 'SELECT DISTINCT id as id, id as idval FROM cat_work WHERE id IS NOT NULL ', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, '{"fieldToSearch":"id", "threshold":3, "noresultsMsg":"No results", "loadingMsg":"Searching"}', NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100007, 'upsert_catalog_arc', 'catalog', 'matcat_id', 1, 1, true, 'string', 'combo', 'material:', NULL, NULL, 'Ex.:material', NULL, NULL, false, true, true, false, 'SELECT DISTINCT(matcat_id) AS id,  matcat_id  AS idval FROM cat_arc WHERE id IS NOT NULL', NULL, NULL, NULL, NULL, 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100008, 'upsert_catalog_arc', 'catalog', 'shape', 1, 2, true, 'string', 'combo', 'shape:', NULL, NULL, 'Ex.:shape', NULL, NULL, false, false, true, false, 'SELECT DISTINCT(shape) AS id,  shape  AS idval FROM cat_arc WHERE id IS NOT NULL', NULL, NULL, 'matcat_id', ' AND cat_arc.matcat_id =  ', 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100009, 'upsert_catalog_arc', 'catalog', 'geom1', 1, 3, true, 'string', 'combo', 'geom1:', NULL, NULL, 'Ex.:geom1', NULL, NULL, false, false, true, false, 'SELECT DISTINCT(geom1) AS id,  geom1  AS idval FROM cat_arc WHERE id IS NOT NULL', NULL, NULL, 'matcat_id', ' AND cat_arc.matcat_id =  ', 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100011, 'upsert_catalog_connec', 'catalog', 'matcat_id', 1, 1, true, 'string', 'combo', 'material:', NULL, NULL, 'Ex.:material', NULL, NULL, false, true, true, false, 'SELECT DISTINCT(matcat_id) AS id,  matcat_id  AS idval FROM cat_connec WHERE id IS NOT NULL', NULL, NULL, NULL, NULL, 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100012, 'upsert_catalog_connec', 'catalog', 'shape', 1, 2, true, 'string', 'combo', 'shape:', NULL, NULL, 'Ex.:shape', NULL, NULL, false, false, true, false, 'SELECT DISTINCT(shape) AS id,  shape  AS idval FROM cat_connec WHERE id IS NOT NULL', NULL, NULL, 'matcat_id', ' AND cat_connec.matcat_id =  ', 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100013, 'upsert_catalog_connec', 'catalog', 'geom1', 1, 3, true, 'string', 'combo', 'geom1:', NULL, NULL, 'Ex.:geom1', NULL, NULL, false, false, true, false, 'SELECT DISTINCT(geom1) AS id,  geom1  AS idval FROM cat_connec WHERE id IS NOT NULL', NULL, NULL, 'matcat_id', ' AND cat_connec.matcat_id =  ', 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100015, 'upsert_catalog_node', 'catalog', 'matcat_id', 1, 1, true, 'string', 'combo', 'material:', NULL, NULL, 'Ex.:material', NULL, NULL, false, true, true, false, 'SELECT DISTINCT(matcat_id) AS id,  matcat_id  AS idval FROM cat_node WHERE id IS NOT NULL', NULL, NULL, NULL, NULL, 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100016, 'upsert_catalog_node', 'catalog', 'shape', 1, 2, true, 'string', 'combo', 'shape:', NULL, NULL, 'Ex.:shape', NULL, NULL, false, false, true, false, 'SELECT DISTINCT(shape) AS id,  shape  AS idval FROM cat_node WHERE id IS NOT NULL', NULL, NULL, 'matcat_id', ' AND cat_node.matcat_id =  ', 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (100017, 'upsert_catalog_node', 'catalog', 'geom1', 1, 3, true, 'string', 'combo', 'geom1:', NULL, NULL, 'Ex.:geom1', NULL, NULL, false, false, true, false, 'SELECT DISTINCT(geom1) AS id,  geom1  AS idval FROM cat_node WHERE id IS NOT NULL', NULL, NULL, 'matcat_id', ' AND cat_node.matcat_id =  ', 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102724, 'search', 'form', 'generic_search', 1, NULL, NULL, 'string', 'nowidget', 'Cerca:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102731, 'search', 'form', 'psector_search', 1, NULL, NULL, 'string', 'nowidget', 'Psector:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102729, 'search', 'form', 'workcat_search', 1, NULL, NULL, 'string', 'nowidget', 'Expedient:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102730, 'search', 'form', 'psector_expl', 1, NULL, NULL, 'string', 'nowidget', 'Explotació:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102732, 'search', 'form', 'visit_search', 1, NULL, NULL, 'string', 'nowidget', 'Visita:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102725, 'search', 'form', 'add_muni', 1, NULL, NULL, 'string', 'nowidget', 'Municipi:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102726, 'search', 'form', 'add_street', 1, NULL, NULL, 'string', 'nowidget', 'Carrer:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102727, 'search', 'form', 'hydro_expl', 1, NULL, NULL, 'string', 'nowidget', 'Explotació:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102728, 'search', 'form', 'hydro_search', 1, NULL, NULL, 'string', 'nowidget', 'Abonat:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102733, 'search', 'form', 'add_postnumber', 1, NULL, NULL, 'string', 'nowidget', 'Núm.:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102722, 'search', 'form', 'net_type', 1, NULL, NULL, 'string', 'nowidget', 'Tipus:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102723, 'search', 'form', 'net_code', 1, NULL, NULL, 'string', 'typeahead', 'Codi:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102710, 'infoplan', 'form', 'frame1', 1, 3, true, 'string', 'formDivider', 'frame1:', NULL, NULL, NULL, NULL, NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102711, 'infoplan', 'form', 'initial_cost', 1, 4, true, 'string', 'label', 'Total PEM:', NULL, NULL, NULL, NULL, NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102713, 'infoplan', 'form', 'frame2', 1, 6, true, 'string', 'formDivider', 'frame2:', NULL, NULL, NULL, NULL, NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102712, 'infoplan', 'form', 'other_cost', 1, 5, true, 'string', 'label', 'VAT:', NULL, NULL, NULL, NULL, NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (102714, 'infoplan', 'form', 'intermediate_cost', 1, 7, true, 'string', 'label', 'Total:', NULL, NULL, NULL, NULL, NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (1, 'upsert_catalog_grate', 'catalog', 'id', 1, 4, true, 'string', 'combo', 'id:', NULL, NULL, 'Ex.:id', NULL, NULL, false, false, true, false, 'SELECT DISTINCT (id) AS id, id AS idval FROM cat_grate WHERE id IS NOT NULL', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (2, 'upsert_catalog_grate', 'catalog', 'matcat_id', 1, 1, true, 'string', 'combo', 'material:', NULL, NULL, 'Ex.:material', NULL, NULL, false, true, true, false, 'SELECT DISTINCT(matcat_id) AS id,  matcat_id  AS idval FROM cat_grate WHERE id IS NOT NULL', NULL, NULL, NULL, NULL, 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (3, 'upsert_catalog_grate', 'catalog', 'shape', 1, 2, true, 'string', 'combo', 'shape:', NULL, NULL, 'Ex.:shape', NULL, NULL, false, false, true, false, 'SELECT DISTINCT(shape) AS id,  shape  AS idval FROM cat_grate WHERE id IS NOT NULL', NULL, NULL, 'matcat_id', ' AND cat_grate.matcat_id =  ', 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
INSERT INTO config_api_form_fields VALUES (4, 'upsert_catalog_grate', 'catalog', 'geom1', 1, 3, true, 'string', 'combo', 'geom1:', NULL, NULL, 'Ex.:geom1', NULL, NULL, false, false, true, false, 'SELECT DISTINCT(geom1) AS id,  geom1  AS idval FROM cat_grate WHERE id IS NOT NULL', NULL, NULL, 'matcat_id', ' AND cat_grate.matcat_id =  ', 'get_catalog_id', NULL, true, NULL, NULL, NULL, NULL, 'layout_data_1', NULL, NULL);
