/*
This file is part of Giswater 3
The program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This version of Giswater is provided by Giswater Association
*/

SET search_path = "galia", public, pg_catalog;


INSERT INTO anl_dwf_type_catastro_uses VALUES ('CPR', 'Comercio Perfumeria ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CRL', 'Comercio Relojeria ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CSP', 'Comercio Supermerc. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CTJ', 'Comercio Tejidos ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('E', 'Enseñanza ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('EBL', 'Ens. Biblioteca ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('EBS', 'Ens. Basica ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ECL', 'Ens. Casa Cultura ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('EIN', 'Ens. Instituto ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('EMS', 'Ens. Museo ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('EPR', 'Ens. Profesional ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('EUN', 'Ens. Universidad ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IIM', 'Ind. Quimica ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IMD', 'Ind. Madera', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('G', 'Hotel ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GC1', 'Hotel Cafe 1T ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GC2', 'Hotel Cafe 2T ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GC3', 'Hotel Cafe 3T ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GC4', 'Hotel Cafe 4T ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GC5', 'Hotel Cafe 5T ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GH1', 'Hotel Hotel 1E ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GH2', 'Hotel Hotel 2E ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GH3', 'Hotel Hotel 3E ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GH4', 'Hotel Hotel 4E ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GH5', 'Hotel Hotel 5E ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GPL', 'Hotel Apt.Luj. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GP1', 'Hotel Apt.Luj.1C ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GP2', 'Hotel Apt.Luj.2C ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GP3', 'Hotel Apt.Luj.3C ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GR1', 'Hotel Rest. 1T ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GR2', 'Hotel Rest. 2T ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GR3', 'Hotel Rest. 3T ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GR4', 'Hotel Rest. 4T ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GR5', 'Hotel Rest. 5T ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GS1', 'Hostal p S1 (Hotel) ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GS2', 'Hostal p S2 (Hotel) ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GS3', 'Hostal p S3 (Hotel) ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GTL', 'Hotel Col.Luj. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GT1', 'Hotel Col.Luj.1C ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GT2', 'Hotel Col.Luj.2C ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('GT3', 'Hotel Col.Luj.3C ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('I', 'Industria ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IAG', 'Ind. Agropecuaria ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IAL', 'Ind. Alimentacion ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IAR', 'Ind. Agricola ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IBB', 'Ind. Bebida ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IBR', 'Ind. Barro ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ICN', 'Ind. Construccion ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ICT', 'Ind. Canter.(Minas) ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IEL', 'Ind. Electricidad ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O99', 'Ofic. Otras activ ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('P', 'Publico', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IMN', 'Ind. Manufacturada ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IMT', 'Ind. Metalica ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IMU', 'Ind. Maquinaria ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IPL', 'Ind. Plasticos ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IPP', 'Ind. Papel ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IPS', 'Ind. Pesca ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IPT', 'Ind. Petroleo ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ITB', 'Ind. Tabaco ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ITX', 'Ind. Textil ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('IVD', 'Ind. Vidrio ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('JAM', 'Almazaras ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('JAS', 'Aserraderos ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('JBD', 'Bodegas ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('JCH', 'Champiñoneras ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('JGR', 'Granjas ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('JIN', 'Invernaderos ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('K', 'Deportivo ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('KDP', 'Deportiv. Deporte ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('KES', 'Deportiv. Estad. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('KPL', 'Deportiv. Polid. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('KPS', 'Deportiv. Piscina ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('M', 'Suelo sin edificar ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O', 'Oficina ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O02', 'Ofic. Superior ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O03', 'Ofic. Medio ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O06', 'Ofic. (Med.,Abog.) ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O07', 'Ofic. ATS,... ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O11', 'Ofic. Profesores ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O13', 'Ofic. Prof.Univer. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O15', 'Ofic. Escritores ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O16', 'Ofic. Artes Plast. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O17', 'Ofic. Musicos ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O43', 'Ofic. Vend. y Viaj. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O44', 'Ofic. Agentes ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O75', 'Ofic. Tejedores ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O79', 'Ofic. Sastres ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O81', 'Ofic. Carpinteros ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('O88', 'Ofic. Joyeros ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YSC', 'Otros Socorro ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YSP', 'Soportal 50% ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZMA', 'Minas cielo abto. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZME', 'Muelles y embarc. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZPC', 'Piscifact., cetareas ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZRS', 'Otros Residencia ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZSA', 'Otros Sindicato Loca ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZSC', 'Otros Socorro ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZSL', 'Silos, dep. solid. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZSN', 'Otros Sanatorio ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZSO', 'Otros Sindicato Prov ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZVR', 'Vertederos', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('A', 'Almacenamiento ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('AAL', 'Almacen ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('AAP', 'Almacen (Apar.) ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('AES', 'Almacen (Est.) ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('BCR', 'Caseta riego ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('BCT', 'Caseta transform. ', false, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('BIG', 'Inst. ganaderas ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('C', 'Comercio ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CAT', 'Comercio Automoviles ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CBZ', 'Comercio Bazar ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CCE', 'Comercio Menor ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CCL', 'Comercio Calzado ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CCR', 'Comercio Carniceria ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CDM', 'Comercio (Pers/Dom) ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CDR', 'Comercio Drogueria ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CFN', 'Comercio Financiero ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CFR', 'Comercio Farmacia ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CFT', 'Comercio Fontaner. ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CGL', 'Comercio Galerias ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CIM', 'Comercio Imprenta ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CJY', 'Comercio Joyeria ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CLB', 'Comercio Libreria ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CMB', 'Comercio Muebles ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('CPA', 'Comercio Por Mayor ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YSL', 'Silos, dep. solid ', false, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YSN', 'Otros Sanatorio ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('V', 'Vivienda ', true, 200, 'hab');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YSO', 'Otros Sindicato Prov', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('PAA', 'Pub. Ayto. 20.000 h ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('PAD', 'Pub. Audiencia ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('PAE', 'Pub. Ayto. +20.000 h ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('PCB', 'Pub. Cabildo ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('PDL', 'Pub. Delegacion ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('PGB', 'Pub. Gobierno ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('PJA', 'Juzgado Comarcal ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('PJO', 'Juzgado Provincial ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('R', 'Religioso ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('RBS', 'Religioso Basilica ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('RCP', 'Religioso Capilla ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('RCT', 'Religioso Catedral ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('RER', 'Religioso Ermita ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('RPR', 'Religioso Parroquia ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('RSN', 'Religioso Santuario ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('T', 'Espectaculos ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('TAD', 'Espect. Auditorio ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('TCM', 'Espect. Cine ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('TCN', 'Espect.Cine no decor ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('TSL', 'Espect. Sala ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('TTT', 'Espect. Teatro ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('Y', 'Otros Usos ', false, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YAM', 'Otros Ambulatorio ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YCA', 'Otros Casino 20.000h ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YCB', 'Otros Club ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YCE', 'Otros Casino +20.000 ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YCL', 'Otros Clinica ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YDG', 'Depositos de gases ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YDL', 'Dep liquid, tanques ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YDS', 'Otros Dispensario ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YGR', 'Otros Guarderia ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YHG', 'Otros Higiene ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YHS', 'Otros Hospital ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YJD', 'Jardin priv 100% ', false, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YPO', 'Porche 100% ', false, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YRS', 'Otros Residencia ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YSA', 'Otros Sindicato Loca', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YOU', 'Obras de urbanización ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YTD', 'Terraza desc. 100% ', false, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('YTZ', 'Terraza cubta. 100% ', false, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('Z', 'Otros Usos ', false, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZAM', 'Otros Ambulatorio ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZBE', 'Balsas, estanques ', false, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZCA', 'Otros Casino 20.000h ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZCB', 'Otros Club ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZCE', 'Otros Casino +20.000 ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZCL', 'Otros Clinica ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZCT', 'Canteras ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZDE', 'Depuradoras ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZDG', 'Depositos de gases ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZDL', 'Dep. liquid, tanques ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZDS', 'Otros Dispensario ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZGR', 'Otros Guarderia ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZGV', 'Graveras ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZHG', 'Otros Higiene ', true, 0, 'm2');
INSERT INTO anl_dwf_type_catastro_uses VALUES ('ZHS', 'Otros Hospital ', true, 0, 'm2');