/*
This file is part of Giswater
The program is free software: you can redistribute it and/or modify it under the terms of the GNU
General Public License as published by the Free Software Foundation, either version 3 of the License,
or (at your option) any later version.
*/


SET search_path = SCHEMA_NAME, public, pg_catalog;


INSERT INTO cat_role VALUES ('role_cm_admin');
INSERT INTO cat_role VALUES ('role_cm_org');
INSERT INTO cat_role VALUES ('role_cm_team');

/*
INSERT INTO sys_table VALUES ('cat_team', 'Catalog of teams', 'role_om', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'lot_plugin') ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_table VALUES ('om_campaign_lot', 'Table with all lots that took place', 'role_om', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'lot_plugin') ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_table VALUES ('selector_lot', 'Selector of lots', 'role_basic', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'lot_plugin') ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_table VALUES ('om_campaign_lot_x_arc', 'Table of arcs related to lots', 'role_om', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'lot_plugin') ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_table VALUES ('om_campaign_lot_x_connec', 'Table of connecs related to lots', 'role_om', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'lot_plugin') ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_table VALUES ('om_campaign_lot_x_node', 'Table of nodes related to lots', 'role_om', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'lot_plugin') ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_table VALUES ('config_visit_class_x_workorder', 'Table of visit classes related to its workorders', 'role_om', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'lot_plugin') ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_table VALUES ('ext_workorder_type', 'Table of workorders related to its types', 'role_om', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'lot_plugin') ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_table VALUES ('ext_workorder_class', 'Table of workorders related to its classes', 'role_om', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'lot_plugin') ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_table VALUES ('ext_workorder', 'External table of workorders', 'role_om', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'lot_plugin') ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_table VALUES ('om_team_x_user', 'Relation between teams and their users', 'role_om', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'lot_plugin') ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_table VALUES ('om_visit_lot_x_gully', 'Table of gullys related to lots', 'role_om', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;


INSERT INTO sys_function VALUES (2898, 'gw_fct_getlot', 'lot_manage', 'function', 'json', 'json', 'Function to provide lot form', 'role_om', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_function VALUES (2862, 'gw_fct_setlot', 'lot_manage', 'function', 'json', 'json', 'Set lot', 'role_om', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_function VALUES (2640, 'gw_fct_getvisitmanager', 'lot_manage', 'function', 'json', 'json', 'To call visit from user', 'role_om', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_function VALUES (2882, 'gw_fct_setvisitmanager', 'lot_manage', 'function', 'json', 'json', 'Function to manage visit manager', 'role_om', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_function VALUES (2997, 'gw_fct_lot_psector_geom', 'lot_manage', 'function', 'json', 'json', 'Function to set the_geom of the psector after its insert', 'role_om', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_function VALUES (2838, 'gw_trg_edit_cat_team', 'utils', 'trigger function', NULL, NULL, 'Makes editable v_edit_cat_team', 'role_om', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_function VALUES (2842, 'gw_trg_edit_lot_x_user', 'utils', 'trigger function', NULL, NULL, 'Makes editable v_om_lot_x_user', 'role_om', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_function VALUES (2834, 'gw_trg_edit_team_x_user', 'utils', 'trigger function', NULL, NULL, 'Makes editable v_om_team_x_user', 'role_om', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_function VALUES (2836, 'gw_trg_edit_team_x_visitclass', 'utils', 'trigger function', NULL, NULL, 'Makes editable v_om_team_x_visitclass', 'role_om', NULL, NULL) ON CONFLICT (id) DO NOTHING;
*/


INSERT into config_param_system values ('basic_selector_tab_lot',
'{"table":"temp_om_campaign_lot","selector":"selector_lot","table_id":"lot_id","selector_id":"lot_id","label":"lot_id, '' - '', name","orderBy":"lot_id","manageAll":true,"typeaheadFilter":" AND lower(concat(lot_id, '' - '', name))","query_filter":"AND active is true ","typeaheadForced":true,"selectionMode":"keepPreviousUsingShift"}',
'Variable to configura all options related to search for the specificic tab','Selector variables',null, null, true, null, 'utils', null, null, 'json','text');


INSERT into config_param_system values ('basic_selector_tab_campaign',
'{"table":"temp_om_campaign","selector":"selector_campaign","table_id":"campaign_id","selector_id":"campaign_id","label":"campaign_id, '' - '', name","orderBy":"campaign_id","manageAll":true,"query_filter":"","typeaheadFilter":" AND lower(concat(id'' - '', name))","selectionMode":"keepPreviousUsingShift", "orderbyCheck":false}',
'Variable to configura all options related to search for the specificic tab','Selector variables',null, null, true, null, 'utils', null, null, 'json','text');

INSERT into config_form_tabs values ('selector_campaign','tab_campaign','Campaign','Campaign','role_basic',null, null, 1, '{4}');
INSERT into config_form_tabs values ('selector_campaign','tab_lot','Lot','Lot','role_basic', null, null, 2,'{4}');

INSERT INTO sys_typevalue (typevalue, id, idval, addparam) VALUES('layout_name_typevalue', 'lyt_buttons', 'lyt_buttons', '{
  "lytOrientation": "horizontal"
}'::json);

INSERT INTO sys_typevalue VALUES ('campaign_type', 1, 'REVIEW', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_type', 2, 'VISIT', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;

INSERT INTO sys_typevalue VALUES ('campaign_status', 1, 'PLANIFYING', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_status', 2, 'PLANIFIED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_status', 3, 'ASSIGNED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_status', 4, 'ON GOING', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_status', 5, 'STAND-BY', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_status', 6, 'EXECUTED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_status', 7, 'REJECTED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_status', 8, 'READY-TO-ACCEPT', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_status', 9, 'ACCEPTED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_status', 10, 'CANCELED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;

INSERT INTO sys_typevalue VALUES ('lot_status', 1, 'PLANIFYING', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_status', 2, 'PLANIFIED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_status', 3, 'ASSIGNED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_status', 4, 'ON GOING', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_status', 5, 'STAND-BY', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_status', 6, 'EXECUTED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_status', 7, 'REJECTED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_status', 8, 'READY-TO-ACCEPT', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_status', 9, 'ACCEPTED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_status', 10, 'CANCELED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;

INSERT INTO sys_typevalue VALUES ('campaign_feature_status', 1, 'PLANIFIED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_feature_status', 2, 'NOT VISITED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_feature_status', 3, 'VISITED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_feature_status', 4, 'VISIT AGAIN', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_feature_status', 5, 'ACCEPTED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('campaign_feature_status', 6, 'CANCELED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;

INSERT INTO sys_typevalue VALUES ('lot_feature_status', 1, 'PLANIFIED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_feature_status', 2, 'NOT VISITED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_feature_status', 3, 'VISITED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_feature_status', 4, 'VISIT AGAIN', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_feature_status', 5, 'ACCEPTED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;
INSERT INTO sys_typevalue VALUES ('lot_feature_status', 6, 'CANCELED', NULL, NULL) ON CONFLICT (typevalue, id) DO NOTHING;

INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'campaign_id', 'lyt_data_1', 1, 'integer', 'text', 'Campaign Id:', 'Id', NULL, false, false, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'name', 'lyt_data_1', 2, 'string', 'text', 'Name:', 'Name', NULL, true, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'startdate', 'lyt_data_1', 3, 'date', 'datetime', 'Planified start:', 'Planified start', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'enddate', 'lyt_data_1', 4, 'date', 'datetime', 'Planified end:', 'Planified end', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'real_startdate', 'lyt_data_1', 5, 'date', 'datetime', 'Real start:', 'Real start', NULL, false, false, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'real_enddate', 'lyt_data_1', 6, 'date', 'datetime', 'Real end:', 'Real end', NULL, false, false, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'reviewclass_id', 'lyt_data_1', 7, 'string', 'combo', 'Reviewclass:', 'Reviewclass', NULL, false, false, true, false, NULL, 'SELECT id, idval FROM cm.om_reviewclass WHERE active = true', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'active', 'lyt_data_1', 8, 'boolean', 'check', 'Active:', 'Active', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'organization_id', 'lyt_data_1', 9, 'string', 'combo', 'Organization:', 'Organization', NULL, false, false, true, false, NULL, 'SELECT organization_id as id, orgname as idval FROM cm.cat_organization WHERE active = true', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'duration', 'lyt_data_1', 10, 'string', 'text', 'Duration:', 'Duration', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'status', 'lyt_data_1', 11, 'string', 'combo', 'Status:', 'Status', NULL, false, false, true, false, NULL, 'SELECT id, idval FROM sys_typevalue WHERE typevalue=''campaign_status''', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'rotation', 'lyt_data_1', 12, 'integer', 'text', 'Rotation:', 'Rotation', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'exercise', 'lyt_data_1', 13, 'integer', 'text', 'Exercise:', 'Exercise', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'serie', 'lyt_data_1', 14, 'string', 'text', 'Serie:', 'Serie', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'address', 'lyt_data_1', 15, 'string', 'text', 'Address:', 'Address', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_review', 'form_feature', 'tab_data', 'description', 'lyt_data_1', 16, 'string', 'textarea', 'Description:', 'Description', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);

INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'lot_id', 'lyt_data_1', 1, 'integer', 'text', 'Lot Id:', 'Id', NULL, false, false, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'name', 'lyt_data_1', 2, 'string', 'text', 'Name:', 'Name', NULL, true, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'startdate', 'lyt_data_1', 3, 'date', 'datetime', 'Planified start:', 'Planified start', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'enddate', 'lyt_data_1', 4, 'date', 'datetime', 'Planified end:', 'Planified end', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'real_startdate', 'lyt_data_1', 5, 'date', 'datetime', 'Real start:', 'Real start', NULL, false, false, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'real_enddate', 'lyt_data_1', 6, 'date', 'datetime', 'Real end:', 'Real end', NULL, false, false, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'visitclass_id', 'lyt_data_1', 7, 'string', 'combo', 'Visitclass:', 'Visitclass', NULL, false, false, true, false, NULL, 'SELECT id, idval FROM cm.om_visitclass WHERE active = true', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'active', 'lyt_data_1', 8, 'boolean', 'check', 'Active:', 'Active', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'organization_id', 'lyt_data_1', 9, 'string', 'combo', 'Organization:', 'Organization', NULL, false, false, true, false, NULL, 'SELECT organization_id as id, orgname as idval FROM cm.cat_organization WHERE active = true', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'duration', 'lyt_data_1', 10, 'string', 'text', 'Duration:', 'Duration', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'status', 'lyt_data_1', 11, 'string', 'combo', 'Status:', 'Status', NULL, false, false, true, false, NULL, 'SELECT id, idval FROM sys_typevalue WHERE typevalue=''campaign_status''', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'rotation', 'lyt_data_1', 12, 'integer', 'text', 'Rotation:', 'Rotation', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'exercise', 'lyt_data_1', 13, 'integer', 'text', 'Exercise:', 'Exercise', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'serie', 'lyt_data_1', 14, 'string', 'text', 'Serie:', 'Serie', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'address', 'lyt_data_1', 15, 'string', 'text', 'Address:', 'Address', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('campaign_visit', 'form_feature', 'tab_data', 'description', 'lyt_data_1', 16, 'string', 'textarea', 'Description:', 'Description', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);

INSERT INTO config_param_user ("parameter", value, cur_user) VALUES('utils_formlabel_show_columname', 'false', 'postgres');
INSERT INTO config_param_user ("parameter", value, cur_user) VALUES('edit_municipality_vdefault', NULL, 'postgres');
INSERT INTO config_param_user ("parameter", value, cur_user) VALUES('utils_debug_mode', 'false', 'postgres');



-- Create organization dialog
INSERT INTO sys_typevalue (typevalue, id, idval, descript, addparam) VALUES('formtype_typevalue', 'create_organization', 'create_organization', NULL, NULL);
INSERT INTO sys_typevalue (typevalue, id, idval, descript, addparam) VALUES('layout_name_typevalue', 'lyt_create_org_1', 'lyt_create_org_1', NULL, '{"lytOrientation": "vertical"}'::json);

INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_organization', 'tab_none', 'btn_accept', 'lyt_buttons', 1, NULL, 'button', '', 'Accept', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{
  "text": "Accept"
}'::json, '{
  "functionName": "upsert_organization",
  "module": "lot"
}'::json, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_organization', 'tab_none', 'name', 'lyt_create_org_1', 0, 'text', 'text', 'Name:', 'Name', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_organization', 'tab_none', 'spacer_1', 'lyt_buttons', 0, NULL, 'hspacer', '', NULL, NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_organization', 'tab_none', 'btn_close', 'lyt_buttons', 2, NULL, 'button', '', 'Close', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{
  "text": "Close"
}'::json, '{
  "functionName": "close",
  "module": "lot"
}'::json, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_organization', 'tab_none', 'active', 'lyt_create_org_1', 3, 'text', 'check', 'Active:', 'Active', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_organization', 'tab_none', 'descript', 'lyt_create_org_1', 1, 'text', 'text', 'Description:', 'Description', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_organization', 'tab_none', 'code', 'lyt_create_org_1', 2, 'text', 'text', 'Code:', 'Code', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);

-- Create team dialog
INSERT INTO sys_typevalue (typevalue, id, idval, descript, addparam) VALUES('formtype_typevalue', 'create_team', 'create_team', NULL, NULL);
INSERT INTO sys_typevalue (typevalue, id, idval, descript, addparam) VALUES('layout_name_typevalue', 'lyt_create_team_1', 'lyt_create_team_1', NULL, '{"lytOrientation": "vertical"}'::json);

INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_team', 'tab_none', 'active', 'lyt_create_team_1', 5, 'text', 'check', 'Active:', 'Active', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_team', 'tab_none', 'btn_accept', 'lyt_buttons', 1, NULL, 'button', '', 'Accept', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{
  "text": "Accept"
}'::json, '{
  "functionName": "upsert_team",
  "module": "lot"
}'::json, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_team', 'tab_none', 'btn_close', 'lyt_buttons', 2, NULL, 'button', '', 'Close', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{
  "text": "Close"
}'::json, '{
  "functionName": "close",
  "module": "lot"
}'::json, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_team', 'tab_none', 'code', 'lyt_create_team_1', 2, 'text', 'text', 'Code:', 'Code', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_team', 'tab_none', 'descript', 'lyt_create_team_1', 1, 'text', 'text', 'Description:', 'Description', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_team', 'tab_none', 'name', 'lyt_create_team_1', 0, 'text', 'text', 'Name:', 'Name', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_team', 'tab_none', 'org_id', 'lyt_create_team_1', 3, 'text', 'combo', 'Organization:', 'Organization', NULL, false, false, true, false, false, 'SELECT organization_id AS id, orgname AS idval FROM cm.cat_organization WHERE organization_id IS NOT NULL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_team', 'tab_none', 'role_id', 'lyt_create_team_1', 4, 'text', 'combo', 'Role:', 'Role', NULL, false, false, true, false, false, 'SELECT role_id AS id, role_id AS idval FROM cm.cat_role WHERE role_id IS NOT NULL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_team', 'tab_none', 'spacer_1', 'lyt_buttons', 0, NULL, 'hspacer', '', NULL, NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);

-- Create user dialog
INSERT INTO sys_typevalue (typevalue, id, idval, descript, addparam) VALUES('formtype_typevalue', 'create_user', 'create_user', NULL, NULL);
INSERT INTO sys_typevalue (typevalue, id, idval, descript, addparam) VALUES('layout_name_typevalue', 'lyt_create_user_1', 'lyt_create_user_1', NULL, '{"lytOrientation": "vertical"}'::json);

INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_user', 'tab_none', 'active', 'lyt_create_user_1', 6, 'text', 'check', 'Active:', 'Active', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_user', 'tab_none', 'btn_accept', 'lyt_buttons', 1, NULL, 'button', '', 'Accept', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{
  "text": "Accept"
}'::json, '{
  "functionName": "upsert_user",
  "module": "lot"
}'::json, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_user', 'tab_none', 'btn_close', 'lyt_buttons', 2, NULL, 'button', '', 'Close', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{
  "text": "Close"
}'::json, '{
  "functionName": "close",
  "module": "lot"
}'::json, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_user', 'tab_none', 'code', 'lyt_create_user_1', 3, 'text', 'text', 'Code:', 'Code', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_user', 'tab_none', 'descript', 'lyt_create_user_1', 4, 'text', 'text', 'Description:', 'Description', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_user', 'tab_none', 'fullname', 'lyt_create_user_1', 2, 'text', 'text', 'Full name:', 'Full name', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_user', 'tab_none', 'loginname', 'lyt_create_user_1', 0, 'text', 'text', 'Login name:', 'Login name', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_user', 'tab_none', 'spacer_1', 'lyt_buttons', 0, NULL, 'hspacer', '', NULL, NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_user', 'tab_none', 'team_id', 'lyt_create_user_1', 5, 'text', 'combo', 'Team:', 'Team', NULL, false, false, true, false, false, 'SELECT team_id AS id, teamname AS idval FROM cm.cat_team WHERE team_id IS NOT NULL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('generic', 'create_user', 'tab_none', 'username', 'lyt_create_user_1', 1, 'text', 'text', 'User name:', 'User name', NULL, false, false, true, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0);

INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'wo', 'lyt_data_1', 1, 'string', 'combo', 'WO:', 'WO', NULL, false, false, true, false, NULL, 'SELECT workorder_id as id, workorder_name as idval FROM workorder ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'wo_type', 'lyt_data_1', 2, 'string', 'text', 'WO Type:', 'WO Type', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'action_type', 'lyt_data_1', 3, 'string', 'text', 'Action type:', 'Action type', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'adress', 'lyt_data_1', 4, 'string', 'text', 'Adress:', 'Adress', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'observations', 'lyt_data_1', 5, 'string', 'textarea', 'Observations:', 'Observations', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'lot_id', 'lyt_data_2', 1, 'string', 'text', 'Lot id:', 'Id', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'name', 'lyt_data_2', 2, 'string', 'text', 'Name:', 'Name', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'startdate', 'lyt_data_2', 3, 'date', 'datetime', 'Planified start:', 'Planified start', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'enddate', 'lyt_data_2', 4, 'date', 'datetime', 'Planified end:', 'Planified end', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'real_startdate', 'lyt_data_2', 5, 'date', 'datetime', 'Real start:', 'Real start', NULL, false, false, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'real_enddate', 'lyt_data_2', 6, 'date', 'datetime', 'Real end:', 'Real end', NULL, false, false, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'campaign_id', 'lyt_data_2', 7, 'text', 'combo', 'Campaign id:', 'Campaign id', NULL, false, false, true, false, NULL, 'SELECT DISTINCT c.campaign_id AS id, c.name AS idval
FROM cm.om_campaign c
JOIN cm.cat_team t ON t.organization_id = c.organization_id
JOIN cm.cat_user u ON u.team_id = t.team_id
WHERE c.active IS TRUE
  AND u.active IS TRUE
  AND u.username = current_user', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'workorder_id', 'lyt_data_2', 8, 'text', 'combo', 'Workorder id:', 'Workorder id', NULL, false, false, true, false, NULL, 'SELECT workorder_id as id, workorder_name as idval FROM workorder', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'active', 'lyt_data_2', 9, 'boolean', 'check', 'Active:', 'Active', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'user', 'lyt_data_2', 10, 'string', 'text', 'User:', 'User', NULL, false, false, false, false, NULL, 'SELECT current_user', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'team', 'lyt_data_2', 11, 'string', 'combo', 'Team:', 'Team', NULL, false, false, true, false, NULL, 'SELECT DISTINCT(cat_team.team_id) as id, teamname as idval FROM cat_team WHERE active is TRUE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'status', 'lyt_data_2', 12, 'string', 'combo', 'Status:', 'Status', NULL, false, false, true, false, NULL, 'SELECT id, idval FROM sys_typevalue WHERE typevalue = ''lot_status''', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder) VALUES('lot', 'form_feature', 'tab_data', 'description', 'lyt_data_2', 13, 'string', 'textarea', 'Description:', 'Description', NULL, false, false, true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL);
