/*
This file is part of Giswater
The program is free software: you can redistribute it and/or modify it under the terms of the GNU
General Public License as published by the Free Software Foundation, either version 3 of the License,
or (at your option) any later version.
*/

SET search_path = "SCHEMA_NAME", public, pg_catalog;

UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'v_ext_municipality', 've_municipality') WHERE dv_querytext LIKE '%v_ext_municipality%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'v_ext_streetaxis', 've_streetaxis') WHERE dv_querytext LIKE '%v_ext_streetaxis%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_municipality', 'v_municipality') WHERE dv_querytext LIKE '%ext_municipality%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_streetaxis', 'v_streetaxis') WHERE dv_querytext LIKE '%ext_streetaxis%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_address', 'v_address') WHERE dv_querytext LIKE '%ext_address%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_region', 'v_region') WHERE dv_querytext LIKE '%ext_region%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_province', 'v_province') WHERE dv_querytext LIKE '%ext_province%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_district', 'v_district') WHERE dv_querytext LIKE '%ext_district%';
UPDATE config_form_fields SET dv_querytext = replace(dv_querytext, 'ext_type_street', 'v_type_street') WHERE dv_querytext LIKE '%ext_type_street%';

UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'v_ext_municipality', 've_municipality')::json WHERE widgetcontrols::text LIKE '%v_ext_municipality%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'v_ext_streetaxis', 've_streetaxis')::json WHERE widgetcontrols::text LIKE '%v_ext_streetaxis%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_municipality', 'v_municipality')::json WHERE widgetcontrols::text LIKE '%ext_municipality%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_streetaxis', 'v_streetaxis')::json WHERE widgetcontrols::text LIKE '%ext_streetaxis%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_address', 'v_address')::json WHERE widgetcontrols::text LIKE '%ext_address%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_region', 'v_region')::json WHERE widgetcontrols::text LIKE '%ext_region%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_province', 'v_province')::json WHERE widgetcontrols::text LIKE '%ext_province%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_district', 'v_district')::json WHERE widgetcontrols::text LIKE '%ext_district%';
UPDATE config_form_fields SET widgetcontrols = replace(widgetcontrols::text, 'ext_type_street', 'v_type_street')::json WHERE widgetcontrols::text LIKE '%ext_type_street%';

UPDATE config_form_fields SET iseditable = false where formname ilike 've_node_%' and columnname = 'state';
UPDATE config_form_fields SET iseditable = false where formname ilike 've_arc_%' and columnname = 'state';
UPDATE config_form_fields SET iseditable = false where formname ilike 've_connec_%' and columnname = 'state';
UPDATE config_form_fields SET iseditable = false where formname ilike 've_link_%' and columnname = 'state';
UPDATE config_form_fields SET iseditable = false where formname ilike 've_gully_%' and columnname = 'state';

UPDATE config_form_fields SET dv_querytext='SELECT function_type AS id, function_type AS idval FROM man_type_function WHERE active AND (featurecat_id IS NULL AND ''ELEMENT''=ANY(feature_type))' WHERE formname='ve_element' AND formtype='form_feature' AND columnname='function_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT function_type AS id, function_type AS idval FROM man_type_function WHERE active AND (featurecat_id IS NULL AND ''ARC''=ANY(feature_type))' WHERE formname='ve_arc' AND formtype='form_feature' AND columnname='function_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT function_type AS id, function_type AS idval FROM man_type_function WHERE active AND (featurecat_id IS NULL AND ''CONNEC''=ANY(feature_type))' WHERE formname='ve_connec' AND formtype='form_feature' AND columnname='function_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT function_type AS id, function_type AS idval FROM man_type_function WHERE active AND (featurecat_id IS NULL AND ''NODE''=ANY(feature_type))' WHERE formname='ve_node' AND formtype='form_feature' AND columnname='function_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT function_type AS id, function_type AS idval FROM man_type_function WHERE active AND (featurecat_id IS NULL AND ''GULLY''=ANY(feature_type)))' WHERE formname='ve_gully' AND formtype='form_feature' AND columnname='function_type' AND tabname='tab_data';

UPDATE config_form_fields SET dv_querytext='SELECT category_type AS id, category_type AS idval FROM man_type_category WHERE active AND (featurecat_id IS NULL AND ''ARC''=ANY(feature_type))' WHERE formname='ve_arc' AND formtype='form_feature' AND columnname='category_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT category_type AS id, category_type AS idval FROM man_type_category WHERE active AND (featurecat_id IS NULL AND ''CONNEC''=ANY(feature_type))' WHERE formname='ve_connec' AND formtype='form_feature' AND columnname='category_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT category_type AS id, category_type AS idval FROM man_type_category WHERE active AND (featurecat_id IS NULL AND ''ELEMENT''=ANY(feature_type))' WHERE formname='ve_element' AND formtype='form_feature' AND columnname='category_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT category_type AS id, category_type AS idval FROM man_type_category WHERE active AND (featurecat_id IS NULL AND ''NODE''=ANY(feature_type))' WHERE formname='ve_node' AND formtype='form_feature' AND columnname='category_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT category_type AS id, category_type AS idval FROM man_type_category WHERE active AND (featurecat_id IS NULL AND ''GULLY''=ANY(feature_type))' WHERE formname='ve_gully' AND formtype='form_feature' AND columnname='category_type' AND tabname='tab_data';

UPDATE config_form_fields SET dv_querytext='SELECT location_type AS id, location_type AS idval FROM man_type_location WHERE active AND (featurecat_id IS NULL AND ''ARC''=ANY(feature_type))' WHERE formname='ve_arc' AND formtype='form_feature' AND columnname='location_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT location_type AS id, location_type AS idval FROM man_type_location WHERE active AND (featurecat_id IS NULL AND ''CONNEC''=ANY(feature_type))' WHERE formname='ve_connec' AND formtype='form_feature' AND columnname='location_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT location_type AS id, location_type AS idval FROM man_type_location WHERE active AND (featurecat_id IS NULL AND ''ELEMENT''=ANY(feature_type))' WHERE formname='ve_element' AND formtype='form_feature' AND columnname='location_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT location_type AS id, location_type AS idval FROM man_type_location WHERE active AND (featurecat_id IS NULL AND ''NODE''=ANY(feature_type))' WHERE formname='ve_node' AND formtype='form_feature' AND columnname='location_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT location_type AS id, location_type AS idval FROM man_type_location WHERE active AND (featurecat_id IS NULL AND ''GULLY''=ANY(feature_type))' WHERE formname='ve_gully' AND formtype='form_feature' AND columnname='location_type' AND tabname='tab_data';

UPDATE config_form_fields SET dv_querytext='SELECT id, idval FROM om_typevalue WHERE typevalue = ''fluid_type''' WHERE formname='ve_element' AND formtype='form_feature' AND columnname='fluid_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT id, idval FROM om_typevalue WHERE typevalue = ''fluid_type''' WHERE formname='ve_arc' AND formtype='form_feature' AND columnname='fluid_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT id, idval FROM om_typevalue WHERE typevalue = ''fluid_type''' WHERE formname='ve_node' AND formtype='form_feature' AND columnname='fluid_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT id, idval FROM om_typevalue WHERE typevalue = ''fluid_type''' WHERE formname='ve_connec' AND formtype='form_feature' AND columnname='fluid_type' AND tabname='tab_data';
UPDATE config_form_fields SET dv_querytext='SELECT id, idval FROM om_typevalue WHERE typevalue = ''fluid_type''' WHERE formname='ve_gully' AND formtype='form_feature' AND columnname='fluid_type' AND tabname='tab_data';

UPDATE config_form_fields SET dv_querytext = 'SELECT id, id as idval FROM cat_element WHERE active IS true'
WHERE formname = 've_element' AND columnname = 'elementcat_id';

UPDATE config_form_fields t SET dv_querytext = a.dv_querytext FROM (
    SELECT CONCAT('SELECT id, id as idval FROM cat_element WHERE active IS true AND element_type = ', quote_literal(upper(split_part(formname, '_', 3)))) AS dv_querytext, formname
    FROM config_form_fields WHERE formname ilike 've_element_%' AND dv_querytext IS NOT NULL AND columnname = 'elementcat_id'
)a WHERE t.formname = a.formname and t.columnname = 'elementcat_id';

INSERT INTO config_form_fields (formname,formtype,tabname,columnname,layoutname,layoutorder,"datatype",widgettype,"label",tooltip,placeholder,ismandatory,isparent,iseditable,isautoupdate,isfilter,dv_querytext,dv_orderby_id,dv_isnullvalue,dv_parent_id,dv_querytext_filterc,stylesheet,widgetcontrols,widgetfunction,linkedobject,hidden,web_layoutorder) VALUES
	 ('ve_connec_samplepoint','form_feature','tab_data','sector_id','lyt_bot_1',1,'integer','combo','Sector id:','Sector_id - Hydraulic sector identifier related to the primary key of sector table',NULL,false,false,true,false,NULL,'SELECT sector_id as id,name as idval FROM sector WHERE sector_id IS NOT NULL AND active IS TRUE ',true,false,NULL,NULL,'{"label":"color:blue; font-weight:bold;"}','{"setMultiline": false, "labelPosition": "top", "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "valueColumn": "name", "filterExpression": null}}',NULL,NULL,false,4),
	 ('ve_connec_samplepoint','form_feature','tab_data','dwfzone_id','lyt_bot_1',2,'integer','combo','Dwfzone','Dwfzone_id',NULL,false,false,true,false,NULL,'SELECT dwfzone_id as id, name as idval FROM dwfzone WHERE dwfzone_id = 0 UNION SELECT dwfzone_id as id, name as idval FROM dwfzone WHERE dwfzone_id IS NOT NULL AND active IS TRUE',true,false,'expl_id',' AND dwfzone.expl_id',NULL,'{"setMultiline": false, "labelPosition": "top", "valueRelation": {"layer": "ve_dma", "activated": true, "keyColumn": "dma_id", "nullValue": false, "valueColumn": "name", "filterExpression": null}}',NULL,NULL,false,5),
	 ('ve_connec_samplepoint','form_feature','tab_data','state','lyt_bot_1',3,'smallint','combo','State:','State - Domain value of connect''s state.',NULL,false,true,false,false,NULL,'WITH psector_value AS (
  		SELECT value::integer AS psector_value
  		FROM config_param_user
  		WHERE parameter = ''plan_psector_current'' AND cur_user = current_user),
	 tg_op_value AS (
  		SELECT value::text AS tg_op_value
  		FROM config_param_user
  		WHERE parameter = ''utils_transaction_mode'' AND cur_user = current_user)
SELECT id::integer as id, name as idval
FROM value_state
WHERE id IS NOT NULL
AND CASE
  WHEN (SELECT tg_op_value FROM tg_op_value)!=''INSERT'' THEN id IN (0,1,2)
  WHEN (SELECT tg_op_value FROM tg_op_value) =''INSERT'' AND (SELECT psector_value FROM psector_value) IS NOT NULL THEN id = 2
  ELSE id < 2
END',true,false,NULL,NULL,NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,false,6),
	 ('ve_connec_samplepoint','form_feature','tab_data','state_type','lyt_bot_1',4,'smallint','combo','State type:','State_type - The state type of the element. It allows to obtain more detail of the state. To select from those available depending on the chosen state',NULL,false,false,true,false,NULL,'SELECT id, name as idval FROM value_state_type WHERE id IS NOT NULL',true,false,'state',' AND value_state_type.state',NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,false,7),
	 ('ve_connec_samplepoint','form_feature','tab_data','code','lyt_data_1',1,'string','text','Code:','Code',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,8),
	 ('ve_connec_samplepoint','form_feature','tab_data','customer_code','lyt_data_1',2,'string','text','Customer code:','Customer_code - Account code',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,9),
	 ('ve_connec_samplepoint','form_feature','tab_data','dma_id','lyt_data_1',3,'integer','text','Dma','Dma_id',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,10),
	 ('ve_connec_samplepoint','form_feature','tab_data','top_elev','lyt_data_1',4,'double','text','Top elevation:','Top_elev - Elevation of the connec in ft or m.',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,11),
	 ('ve_connec_samplepoint','form_feature','tab_data','y1','lyt_data_1',5,'double','text','Y1:','Y1 - Depth at the point of connection with the building',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,12),
	 ('ve_connec_samplepoint','form_feature','tab_data','y2','lyt_data_1',6,'double','text','Y2:','Y2 - Depth at the point of connection to the public network',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,13),
	 ('ve_connec_samplepoint','form_feature','tab_data','private_conneccat_id','lyt_data_1',7,'string','text','Private conneccat id:','Private_conneccat_id',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline": false, "valueRelation":{"nullValue":false, "layer": "cat_connec", "activated": true, "keyColumn": "id", "valueColumn": "id", "filterExpression": null}}',NULL,NULL,false,14),
	 ('ve_connec_samplepoint','form_feature','tab_data','matcat_id','lyt_data_1',8,'string','combo','Matcat id:','Matcat_id',NULL,false,false,true,false,NULL,'SELECT id, id AS idval FROM cat_material WHERE ''ARC'' = ANY(feature_type)',NULL,true,NULL,NULL,NULL,'{"setMultiline": false, "valueRelation":{"nullValue":false, "layer": "cat_material", "activated": true, "keyColumn": "id", "valueColumn": "descript", "filterExpression": null}}',NULL,NULL,false,15),
	 ('ve_connec_samplepoint','form_feature','tab_data','demand','lyt_data_1',9,'double','text','Demand:','Demand',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,16),
	 ('ve_connec_samplepoint','form_feature','tab_data','connec_depth','lyt_data_1',10,'double','text','Connec depth:','Connec_depth',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,17),
	 ('ve_connec_samplepoint','form_feature','tab_data','connec_length','lyt_data_1',11,'double','text','Connec length:','Connec_length - Length of the connection',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,18),
	 ('ve_connec_samplepoint','form_feature','tab_data','workcat_id','lyt_data_1',12,'string','typeahead','Workcat id:','Workcat_id',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_work WHERE id IS NOT NULL AND active IS TRUE ',NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,19),
	 ('ve_connec_samplepoint','form_feature','tab_data','diagonal','lyt_data_1',13,'string','text','Diagonal:','Diagonal',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,20),
	 ('ve_connec_samplepoint','form_feature','tab_data','accessibility','lyt_data_1',14,'boolean','check','Accessibility:','Accessibility - Acceso al elemento',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,21),
	 ('ve_connec_samplepoint','form_feature','tab_data','builtdate','lyt_data_1',15,'date','datetime','Builtdate:','Builtdate',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,22),
	 ('ve_connec_samplepoint','form_feature','tab_data','ownercat_id','lyt_data_1',16,'string','combo','Owner:','Ownercat_id - id of the owner related to connect.',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_owner WHERE id IS NOT NULL AND active IS TRUE ',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,23),
	 ('ve_connec_samplepoint','form_feature','tab_data','enddate','lyt_data_1',17,'date','datetime','Enddate:','Enddate',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,24),
	 ('ve_connec_samplepoint','form_feature','tab_data','macrodma_id','lyt_data_1',18,'integer','text','Macrodma id:','Macrodma_id',NULL,false,false,true,false,NULL,'SELECT macroomzone_id as id, name as idval FROM macroomzone where macroomzone_id is not null AND active IS TRUE ',NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,25),
	 ('ve_connec_samplepoint','form_feature','tab_data','num_value','lyt_data_1',19,'double','text','Number value:','Number value',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,26),
	 ('ve_connec_samplepoint','form_feature','tab_data','macrosector_id','lyt_data_1',20,'integer','text','Macrosector id:','Macrosector_id',NULL,false,false,false,false,NULL,NULL,true,false,NULL,NULL,NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,true,27),
	 ('ve_connec_samplepoint','form_feature','tab_data','cabinet','lyt_data_1',21,'string','text','cabinet',NULL,NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','lab_code','lyt_data_1',22,'string','text','lab_code',NULL,NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','place_name','lyt_data_1',23,'string','text','place_name',NULL,NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','macroexpl_id','lyt_data_1',NULL,'text','text','Macroexploitation:','Macroexpl_id',NULL,true,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,29),
	 ('ve_connec_samplepoint','form_feature','tab_data','tstamp','lyt_data_1',NULL,'text','text','Insert tstamp:','Tstamp - Fecha de inserción del elemento a la base de datos',NULL,true,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,28),
	 ('ve_connec_samplepoint','form_feature','tab_data','soilcat_id','lyt_data_2',1,'string','combo','Soilcat id:','Soilcat_id - id of the soil related to the connect.',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_soil WHERE id IS NOT NULL AND active IS TRUE ',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,30),
	 ('ve_connec_samplepoint','form_feature','tab_data','featurecat_id','lyt_data_2',2,'string','text','Featurecat id:','Featurecat_id - Type of feature to which the connec is connected',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,31),
	 ('ve_connec_samplepoint','form_feature','tab_data','feature_id','lyt_data_2',3,'string','text','Feature id:','Feature_id',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,32),
	 ('ve_connec_samplepoint','form_feature','tab_data','category_type','lyt_data_2',4,'string','combo','Category type:','Category_type',NULL,false,false,true,false,NULL,'SELECT category_type as id, category_type as idval FROM man_type_category WHERE ((featurecat_id is null AND ''CONNEC''=ANY(feature_type))) AND active IS TRUE  OR ''SAMPLEPOINT'' = ANY(featurecat_id::text[])',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,33),
	 ('ve_connec_samplepoint','form_feature','tab_data','function_type','lyt_data_2',5,'string','combo','Function type:','Function_type',NULL,false,false,true,false,NULL,'SELECT function_type as id, function_type as idval FROM man_type_function WHERE ((featurecat_id is null AND ''CONNEC''=ANY(feature_type)) ) AND active IS TRUE  OR ''SAMPLEPOINT'' = ANY(featurecat_id::text[])',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,34),
	 ('ve_connec_samplepoint','form_feature','tab_data','fluid_type','lyt_data_2',6,'string','combo','Fluid type:','Fluid_type - Tipo de fluido a escoger en el desplegable personalizado por el usuario en la tabla man_type_fluid',NULL,true,false,true,false,NULL,'SELECT id, idval FROM om_typevalue WHERE typevalue = ''fluid_type''',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,35),
	 ('ve_connec_samplepoint','form_feature','tab_data','location_type','lyt_data_2',7,'string','combo','Location type:','Location_type',NULL,false,false,true,false,NULL,'SELECT location_type as id, location_type as idval FROM man_type_location WHERE ((featurecat_id is null AND ''CONNEC''=ANY(feature_type)) ) AND active IS TRUE  OR ''SAMPLEPOINT'' = ANY(featurecat_id::text[])',true,true,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,36),
	 ('ve_connec_samplepoint','form_feature','tab_data','comment','lyt_data_2',8,'string','text','Comment:','Comment - Optional field to add comments about the element',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,37),
	 ('ve_connec_samplepoint','form_feature','tab_data','svg','lyt_data_2',9,'string','text','Svg:','Svg - In case of using svg symbology, the path to the file containing the symbology is shown',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,38),
	 ('ve_connec_samplepoint','form_feature','tab_data','rotation','lyt_data_2',10,'double','text','Rotation:','Rotation',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,39),
	 ('ve_connec_samplepoint','form_feature','tab_data','label','lyt_data_2',11,'string','text','Catalog label:','Label - Label from the catalog of connecs, therefore it will not be editable in the form',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,40),
	 ('ve_connec_samplepoint','form_feature','tab_data','label_x','lyt_data_2',12,'string','text','Label x:','Label_x - X coordinate of the label''s location',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,41),
	 ('ve_connec_samplepoint','form_feature','tab_data','label_y','lyt_data_2',13,'string','text','Label y:','Label_y',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,42),
	 ('ve_connec_samplepoint','form_feature','tab_data','label_rotation','lyt_data_2',14,'double','text','Label rotation:','Label_rotation - Angle of rotation of the label',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,43),
	 ('ve_connec_samplepoint','form_feature','tab_data','publish','lyt_data_2',15,'boolean','check','Publish:','Publish - To set if the element is published or should be',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,44),
	 ('ve_connec_samplepoint','form_feature','tab_data','inventory','lyt_data_2',16,'boolean','check','Inventory:','Inventory',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,45),
	 ('ve_connec_samplepoint','form_feature','tab_data','uncertain','lyt_data_2',17,'boolean','check','Uncertain:','Uncertain - To set if the element''s location is uncertain',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,46),
	 ('ve_connec_samplepoint','form_feature','tab_data','verified','lyt_data_2',18,'integer','combo','Verified:','Verified',NULL,false,false,true,false,NULL,'SELECT id, idval FROM edit_typevalue WHERE typevalue = ''value_verified''',true,true,NULL,NULL,NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,true,47),
	 ('ve_connec_samplepoint','form_feature','tab_data','expl_id','lyt_data_2',19,'integer','combo','Exploitation id:','Expl_id - Exploitation to which the element belongs. If the configuration is not changed, the program automatically selects it based on the geometry',NULL,false,true,true,false,NULL,'SELECT expl_id as id, name as idval FROM exploitation WHERE expl_id IS NOT NULL',true,false,NULL,NULL,'{"label":"color:green; font-weight:bold;"}','{"setMultiline": false, "valueRelation": {"layer": "ve_exploitation", "activated": true, "keyColumn": "expl_id", "nullValue": false, "valueColumn": "name", "filterExpression": null}}',NULL,NULL,false,48),
	 ('ve_connec_samplepoint','form_feature','tab_data','workcat_id_end','lyt_data_2',20,'string','typeahead','Workcat id end:','Workcat_id_end - id of the  end of construction work.','Only when state is obsolete',false,false,true,false,NULL,'SELECT id, id as idval FROM cat_work WHERE id IS NOT NULL AND active IS TRUE ',NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,49),
	 ('ve_connec_samplepoint','form_feature','tab_data','workcat_id_plan','lyt_data_2',21,'string','typeahead','Workcat id plan:','Workcat_id_plan',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_work WHERE id IS NOT NULL',NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,50),
	 ('ve_connec_samplepoint','form_feature','tab_data','asset_id','lyt_data_2',22,'string','text','Asset id:','Asset_id',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,51),
	 ('ve_connec_samplepoint','form_feature','tab_data','expl_id2','lyt_data_2',23,'integer','combo','Exploitation 2:','Expl_id2',NULL,false,false,true,false,NULL,'SELECT expl_id as id, name as idval FROM exploitation WHERE expl_id IS NOT NULL and expl_id !=0',true,true,NULL,NULL,NULL,NULL,NULL,NULL,true,52),
	 ('ve_connec_samplepoint','form_feature','tab_data','adate','lyt_data_2',24,'string','text','Adate:','Adate',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,53),
	 ('ve_connec_samplepoint','form_feature','tab_data','adescript','lyt_data_2',25,'string','text','Adescript:','Adescript',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,54),
	 ('ve_connec_samplepoint','form_feature','tab_data','placement_type','lyt_data_2',26,'string','text','Placement Type:','Placement Type',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,55),
	 ('ve_connec_samplepoint','form_feature','tab_data','brand_id','lyt_data_2',29,'text','combo','Brand:','Brand_id',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_brand WHERE ''CJOIN'' = ANY(featurecat_id::text[]) OR featurecat_id IS NULL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,56),
	 ('ve_connec_samplepoint','form_feature','tab_data','model_id','lyt_data_2',30,'text','combo','Model id:','Model_id',NULL,false,false,true,false,NULL,'SELECT id, id as idval FROM cat_brand_model WHERE ''CJOIN'' = ANY(featurecat_id::text[]) OR featurecat_id IS NULL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,57),
	 ('ve_connec_samplepoint','form_feature','tab_data','expl_visibility','lyt_data_2',43,'text','text','Expl id visibility:','Expl_id visibility',NULL,false,false,true,false,NULL,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0',NULL,NULL,NULL,NULL,NULL,'{"setMultiline": false}',NULL,NULL,false,NULL),
	 ('ve_connec_samplepoint','form_feature','tab_data','muni_id','lyt_data_3',1,'integer','combo','Municipality:','Muni_id - Municipality to which the element belongs. If the configuration is not modified, the program automatically selects it based on the geometry',NULL,false,true,true,false,NULL,'SELECT muni_id as id, name as idval from ve_municipality WHERE muni_id IS NOT NULL',true,false,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,58),
	 ('ve_connec_samplepoint','form_feature','tab_data','postcode','lyt_data_3',2,'string','text','Postcode:','Postcode - Postal code of the municipality',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,59),
	 ('ve_connec_samplepoint','form_feature','tab_data','streetname','lyt_data_3',3,'string','typeahead','Street:','Streetname - Street identifier.',NULL,false,false,true,false,NULL,'SELECT id AS id, a.descript AS idval FROM ve_streetaxis a JOIN v_municipality m USING (muni_id) WHERE id IS NOT NULL',NULL,true,'muni_id',' AND m.name',NULL,'{"setMultiline":false}',NULL,NULL,false,60),
	 ('ve_connec_samplepoint','form_feature','tab_data','postcomplement','lyt_data_3',4,'string','text','Optional complement of the street number:','Postcomplement - Optional complement of the street number',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,61),
	 ('ve_connec_samplepoint','form_feature','tab_data','postnumber','lyt_data_3',5,'integer','typeahead','Street number:','Postnumber - Street number',NULL,false,false,true,false,NULL,'SELECT a.postnumber AS id, a.postnumber AS idval FROM v_address a JOIN v_streetaxis m ON streetaxis_id=m.id WHERE a.id IS NOT NULL',NULL,NULL,'streetname',' AND m.name',NULL,'{"setMultiline":false}',NULL,NULL,false,62),
	 ('ve_connec_samplepoint','form_feature','tab_data','postnumber2','lyt_data_3',6,'integer','typeahead','Second street number:','Postnumber2 - Second street number',NULL,false,false,true,false,NULL,'SELECT a.postnumber AS id, a.postnumber AS idval FROM v_address a JOIN v_streetaxis m ON streetaxis_id=m.id WHERE a.id IS NOT NULL',NULL,NULL,'streetname2',' AND m.name',NULL,'{"setMultiline":false}',NULL,NULL,false,63),
	 ('ve_connec_samplepoint','form_feature','tab_data','streetname2','lyt_data_3',7,'string','typeahead','Street 2:','Streetname2 - Second street identifier.',NULL,false,false,true,false,NULL,'SELECT id AS id, a.descript AS idval FROM ve_streetaxis a JOIN v_municipality m USING (muni_id) WHERE id IS NOT NULL',NULL,true,'muni_id',' AND m.name',NULL,'{"setMultiline":false}',NULL,NULL,false,64),
	 ('ve_connec_samplepoint','form_feature','tab_data','postcomplement2','lyt_data_3',8,'string','text','Postcomplement2:','Postcomplement2',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,65),
	 ('ve_connec_samplepoint','form_feature','tab_data','region_id','lyt_data_3',9,'integer','combo','Region:','Region_id',NULL,false,false,false,false,NULL,'SELECT region_id as id, name as idval FROM v_region WHERE region_id IS NOT NULL',true,true,NULL,NULL,NULL,NULL,NULL,NULL,true,66),
	 ('ve_connec_samplepoint','form_feature','tab_data','province_id','lyt_data_3',10,'integer','combo','Province:','Province_id',NULL,false,false,false,false,NULL,'SELECT province_id as id, name as idval FROM v_province WHERE province_id IS NOT NULL',true,true,NULL,NULL,NULL,NULL,NULL,NULL,true,67),
	 ('ve_connec_samplepoint','form_feature','tab_data','pjoint_id','lyt_data_3',11,'string','text','Junction point id:','Pjoint_id - identifier of the connection point with the network',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,68),
	 ('ve_connec_samplepoint','form_feature','tab_data','pjoint_type','lyt_data_3',12,'string','text','Pjoint type:','Pjoint_type',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,69),
	 ('ve_connec_samplepoint','form_feature','tab_data','descript','lyt_data_3',13,'string','text','Descript:','Descript',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,70),
	 ('ve_connec_samplepoint','form_feature','tab_data','annotation','lyt_data_3',14,'string','text','Annotation:','Annotation - Annotations related to connec. Additional information',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,71),
	 ('ve_connec_samplepoint','form_feature','tab_data','observ','lyt_data_3',15,'string','text','Observation:','Observ - Observations related to connect. Additional information',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,false,72),
	 ('ve_connec_samplepoint','form_feature','tab_data','lastupdate','lyt_data_3',16,'date','text','Last update:','Lastupdate - Last time this element was updated',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,73),
	 ('ve_connec_samplepoint','form_feature','tab_data','lastupdate_user','lyt_data_3',17,'string','text','Last update user:','Lastupdate_user - Last user who updated this item',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,74),
	 ('ve_connec_samplepoint','form_feature','tab_data','link','lyt_data_3',18,'text','hyperlink','Link:','Link',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}','{"functionName": "open_url"}','action_link',false,75),
	 ('ve_connec_samplepoint','form_feature','tab_data','plot_code','lyt_data_3',19,'string','text','Plot code:','Plot_code',NULL,false,false,true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline":false}',NULL,NULL,true,76),
	 ('ve_connec_samplepoint','form_feature','tab_data','district_id','lyt_data_3',NULL,'integer','combo','District:','District_id - identifier of the neighborhood with which the element is linked. To choose from those available in the drop-down (it is filtered according to the selected municipality)',NULL,false,false,true,false,NULL,'SELECT a.district_id AS id, a.name AS idval FROM v_district a JOIN v_municipality m USING (muni_id) WHERE district_id IS NOT NULL ',NULL,true,'muni_id',' AND m.muni_id',NULL,'{"setMultiline":false}',NULL,NULL,true,77),
	 ('ve_connec_samplepoint','form_feature','tab_data','connec_id','lyt_none',1,'string','text','Connec id:','Connec_id - identifier of the connec. It is not necessary to enter it, it is an automatic serial',NULL,false,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,false,78),
	 ('ve_connec_samplepoint','form_feature','tab_data','connec_type','lyt_top_1',1,'string','combo','Connec type:','Connec_type',NULL,true,true,false,false,NULL,'SELECT id, id as idval FROM cat_feature_connec WHERE id IS NOT NULL',true,false,NULL,NULL,NULL,'{"setMultiline": false, "labelPosition": "top", "valueRelation": {"layer": "ve_cat_feature_connec", "activated": true, "keyColumn": "id", "nullValue": false, "valueColumn": "id", "filterExpression": null}}',NULL,NULL,false,1),
	 ('ve_connec_samplepoint','form_feature','tab_data','conneccat_id','lyt_top_1',2,'string','typeahead','Conneccat id:','Conneccat_id',NULL,true,false,true,false,NULL,'SELECT id, id as idval FROM cat_connec WHERE id IS NOT NULL AND active IS TRUE ',NULL,NULL,'connec_type',' AND cat_connec.connec_type IS NULL OR cat_connec.connec_type',NULL,'{"setMultiline": false, "labelPosition": "top", "valueRelation": {"layer": "cat_connec", "activated": true, "keyColumn": "id", "nullValue": false, "valueColumn": "id", "filterExpression": null}}',NULL,NULL,false,2),
	 ('ve_connec_samplepoint','form_feature','tab_data','arc_id','lyt_top_1',3,'string','typeahead','Arc id:','Arc identifier',NULL,false,false,false,false,NULL,'SELECT arc_id as id, arc_id as idval FROM arc WHERE arc_id IS NOT NULL',NULL,true,NULL,NULL,NULL,'{"setMultiline": false, "labelPosition": "top"}',NULL,NULL,false,3);

INSERT INTO config_form_fields (formname, formtype, tabname, columnname, layoutname, layoutorder, "datatype", widgettype, "label", tooltip, placeholder, ismandatory, isparent, iseditable, isautoupdate, isfilter, dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id, dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction, linkedobject, hidden, web_layoutorder)
VALUES
('ve_node_adaptation', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_air_valve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_bypass_register', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_check_valve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_clorinathor', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_control_register', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_curve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_endline', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_expantank', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_filter', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_fl_contr_valve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_flexunion', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_flowmeter', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_gen_purp_valve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_green_valve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_hydrant', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_junction', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_manhole', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_netelement', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_netsamplepoint', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_outfall_valve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_pr_break_valve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_pr_reduc_valve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_pr_susta_valve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_pressure_meter', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_pump', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_reduction', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_register', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_shutoff_valve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_source', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_t', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_tank', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_throttle_valve', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_valve_register', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_water_connection', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_waterwell', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_wtp', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_x', 'form_feature', 'tab_data', 'sector_visibility', 'lyt_data_2', 49, 'text', 'multiple_option', 'Sector id visibility:', 'Sector id visibility:', NULL, false, false, true, false, NULL, 'select sector_id AS id, name AS idval from ve_sector where sector_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_sector", "activated": true, "keyColumn": "sector_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_adaptation', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_air_valve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_bypass_register', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_check_valve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_clorinathor', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_control_register', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_curve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_endline', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_expantank', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_filter', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_fl_contr_valve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_flexunion', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_flowmeter', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_gen_purp_valve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_green_valve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_hydrant', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_junction', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_manhole', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_netelement', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_netsamplepoint', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_outfall_valve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_pr_break_valve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_pr_reduc_valve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_pr_susta_valve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_pressure_meter', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_pump', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_reduction', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_register', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_shutoff_valve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_source', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_t', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_tank', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_throttle_valve', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_valve_register', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_water_connection', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_waterwell', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_wtp', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL),
('ve_node_x', 'form_feature', 'tab_data', 'muni_visibility', 'lyt_data_2', 50, 'text', 'multiple_option', 'Muni id visibility:', 'Muni id visibility:', NULL, false, false, true, false, NULL, 'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0', NULL, NULL, NULL, NULL, NULL, '{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json, NULL, NULL, false, NULL)
ON CONFLICT DO NOTHING;

INSERT INTO config_form_fields (formname,formtype,tabname,columnname,layoutname,layoutorder,"datatype",widgettype,"label",tooltip,ismandatory,isparent,iseditable,dv_querytext,widgetcontrols,hidden)
VALUES
('ve_element','form_feature','tab_data','expl_visibility','lyt_data_3',2,'text','multiple_option','Expl id visibility:','Expl id visibility:',false,false,true,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element','form_feature','tab_data','sector_visibility','lyt_data_3',3,'text','multiple_option','Sector id visibility:','Sector id visibility:',false,false,true,'select sector_id AS id, name AS idval from ve_sector where sector_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element','form_feature','tab_data','muni_visibility','lyt_data_3',4,'text','multiple_option','Muni id visibility:','Muni id visibility:',false,false,true,'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_epump','form_feature','tab_data','expl_visibility','lyt_data_3',2,'text','multiple_option','Expl id visibility:','Expl id visibility:',false,false,true,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_epump','form_feature','tab_data','sector_visibility','lyt_data_3',3,'text','multiple_option','Sector id visibility:','Sector id visibility:',false,false,true,'select sector_id AS id, name AS idval from ve_sector where sector_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_epump','form_feature','tab_data','muni_visibility','lyt_data_3',4,'text','multiple_option','Muni id visibility:','Muni id visibility:',false,false,true,'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eorifice','form_feature','tab_data','expl_visibility','lyt_data_3',2,'text','multiple_option','Expl id visibility:','Expl id visibility:',false,false,true,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eorifice','form_feature','tab_data','sector_visibility','lyt_data_3',3,'text','multiple_option','Sector id visibility:','Sector id visibility:',false,false,true,'select sector_id AS id, name AS idval from ve_sector where sector_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eorifice','form_feature','tab_data','muni_visibility','lyt_data_3',4,'text','multiple_option','Muni id visibility:','Muni id visibility:',false,false,true,'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eoutlet','form_feature','tab_data','expl_visibility','lyt_data_3',2,'text','multiple_option','Expl id visibility:','Expl id visibility:',false,false,true,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eoutlet','form_feature','tab_data','sector_visibility','lyt_data_3',3,'text','multiple_option','Sector id visibility:','Sector id visibility:',false,false,true,'select sector_id AS id, name AS idval from ve_sector where sector_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eoutlet','form_feature','tab_data','muni_visibility','lyt_data_3',4,'text','multiple_option','Muni id visibility:','Muni id visibility:',false,false,true,'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eweir','form_feature','tab_data','expl_visibility','lyt_data_3',2,'text','multiple_option','Expl id visibility:','Expl id visibility:',false,false,true,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eweir','form_feature','tab_data','sector_visibility','lyt_data_3',3,'text','multiple_option','Sector id visibility:','Sector id visibility:',false,false,true,'select sector_id AS id, name AS idval from ve_sector where sector_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eweir','form_feature','tab_data','muni_visibility','lyt_data_3',4,'text','multiple_option','Muni id visibility:','Muni id visibility:',false,false,true,'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_ecover','form_feature','tab_data','expl_visibility','lyt_data_3',2,'text','multiple_option','Expl id visibility:','Expl id visibility:',false,false,true,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_ecover','form_feature','tab_data','sector_visibility','lyt_data_3',3,'text','multiple_option','Sector id visibility:','Sector id visibility:',false,false,true,'select sector_id AS id, name AS idval from ve_sector where sector_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_ecover','form_feature','tab_data','muni_visibility','lyt_data_3',4,'text','multiple_option','Muni id visibility:','Muni id visibility:',false,false,true,'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_egate','form_feature','tab_data','expl_visibility','lyt_data_3',2,'text','multiple_option','Expl id visibility:','Expl id visibility:',false,false,true,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_egate','form_feature','tab_data','sector_visibility','lyt_data_3',3,'text','multiple_option','Sector id visibility:','Sector id visibility:',false,false,true,'select sector_id AS id, name AS idval from ve_sector where sector_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_egate','form_feature','tab_data','muni_visibility','lyt_data_3',4,'text','multiple_option','Muni id visibility:','Muni id visibility:',false,false,true,'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eiot_sensor','form_feature','tab_data','expl_visibility','lyt_data_3',2,'text','multiple_option','Expl id visibility:','Expl id visibility:',false,false,true,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eiot_sensor','form_feature','tab_data','sector_visibility','lyt_data_3',3,'text','multiple_option','Sector id visibility:','Sector id visibility:',false,false,true,'select sector_id AS id, name AS idval from ve_sector where sector_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eiot_sensor','form_feature','tab_data','muni_visibility','lyt_data_3',4,'text','multiple_option','Muni id visibility:','Muni id visibility:',false,false,true,'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_estep','form_feature','tab_data','expl_visibility','lyt_data_3',2,'text','multiple_option','Expl id visibility:','Expl id visibility:',false,false,true,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_estep','form_feature','tab_data','sector_visibility','lyt_data_3',3,'text','multiple_option','Sector id visibility:','Sector id visibility:',false,false,true,'select sector_id AS id, name AS idval from ve_sector where sector_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_estep','form_feature','tab_data','muni_visibility','lyt_data_3',4,'text','multiple_option','Muni id visibility:','Muni id visibility:',false,false,true,'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eprotector','form_feature','tab_data','expl_visibility','lyt_data_3',2,'text','multiple_option','Expl id visibility:','Expl id visibility:',false,false,true,'select expl_id AS id, name AS idval from ve_exploitation where expl_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eprotector','form_feature','tab_data','sector_visibility','lyt_data_3',3,'text','multiple_option','Sector id visibility:','Sector id visibility:',false,false,true,'select sector_id AS id, name AS idval from ve_sector where sector_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false),
('ve_element_eprotector','form_feature','tab_data','muni_visibility','lyt_data_3',4,'text','multiple_option','Muni id visibility:','Muni id visibility:',false,false,true,'select muni_id AS id, name AS idval from ve_municipality where muni_id > 0','{"setMultiline": false, "valueRelation": {"layer": "ve_municipality", "activated": true, "keyColumn": "muni_id", "nullValue": false, "allowMulti": true, "nofColumns": 2, "valueColumn": "name", "filterExpression": null}}'::json,false)
ON CONFLICT DO NOTHING;

UPDATE config_form_fields
SET layoutorder=5
WHERE formname ILIKE 've_element%' AND formtype='form_feature' AND columnname='observ' AND tabname='tab_data';
