/*
This file is part of Giswater 3
The program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This version of Giswater is provided by Giswater Association
*/


SET search_path = SCHEMA_NAME, public, pg_catalog;



-- 2019/03/27
UPDATE sys_feature_type SET parentlayer = 'v_edit_gully' WHERE id='GULLY';

--2019/04/04
DELETE FROM audit_cat_param_user;


INSERT INTO audit_cat_param_user VALUES ('epa_outfall_type_vdefault', 'config', 'Default value for EPA outfall type parameter', 'role_epa', NULL, NULL, 'Outfall type:', 'SELECT id , idval FROM inp_typevalue  WHERE typevalue = ''inp_typevalue_outfall''', NULL, true, 6, 3, 'ws', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('epa_junction_y0_vdefault', 'config', 'Default value for EPA junction y0 parameter', 'role_epa', NULL, NULL, 'Junction y0:', NULL, NULL, true, 6, 2, 'ws', false, NULL, NULL, NULL, false, 'double', 'spinbox', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('epa_conduit_q0_vdefault', 'config', 'Default value for EPA conduit q0 parameter', 'role_epa', NULL, NULL, 'Conduit q0:', NULL, NULL, true, 6, 1, 'ws', false, NULL, NULL, NULL, false, 'double', 'spinbox', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('arccat_vdefault', 'config', 'Default value of arc catalog', 'role_edit', NULL, NULL, 'Arc catalog:', 'SELECT cat_arc.id AS id, cat_arc.id as idval FROM cat_arc WHERE id IS NOT NULL', NULL, true, 10, 1, 'utils', false, NULL, 'arccat_id', NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('epa_rgage_scf_vdefault', 'config', 'Default value for EPA raingage scf parameter', 'role_epa', NULL, NULL, 'Raingage scf:', NULL, NULL, true, 6, 4, 'ws', false, NULL, NULL, NULL, false, 'double', 'spinbox', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('enddate_vdefault', 'config', 'Default value of feature''s enddate', 'role_edit', NULL, NULL, 'End date:', NULL, NULL, true, 3, 6, 'utils', false, NULL, 'enddate', NULL, false, 'date', 'datepickertime', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('psector_other_vdefault', 'config', 'Default value of psector other parameter', 'role_master', NULL, NULL, 'Psector other:', NULL, NULL, true, 7, 8, 'utils', false, NULL, NULL, NULL, false, 'double', 'spinbox', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('pavement_vdefault', 'config', 'Default value of pavement catalog', 'role_edit', NULL, NULL, 'Pavement catalog:', 'SELECT cat_pavement.id AS id, cat_pavement.id as idval FROM cat_pavement WHERE id IS NOT NULL', NULL, true, 5, 2, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('edit_connect_force_automatic_connect2network', 'config', 'If true, link will be automatically generated when inserting a new connec', 'role_edit', NULL, NULL, 'Connect connecs to network:', NULL, NULL, true, 8, 6, 'utils', false, NULL, NULL, NULL, false, 'boolean', 'check', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('edit_link_connecrotation_update', 'config', 'If true, the label and symbol of connec will be rotated using the angle of link', 'role_edit', NULL, NULL, 'Disable connec rotation on update:', NULL, NULL, true, 8, 5, 'utils', false, NULL, NULL, NULL, false, 'boolean', 'check', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('nodecat_vdefault', 'config', 'Default value of node catalog', 'role_edit', NULL, NULL, 'Node catalog:', 'SELECT cat_node.id AS id, cat_node.id as idval FROM cat_node WHERE id IS NOT NULL', NULL, true, 9, 2, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('connecat_vdefault', 'config', 'Default value of connec catalog', 'role_edit', NULL, NULL, 'Connec catalog:', 'SELECT cat_connec.id AS id, cat_connec.id as idval FROM cat_connec WHERE id IS NOT NULL', NULL, true, 12, 1, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('ownercat_vdefault', 'config', 'Default value of owner catalog', 'role_edit', NULL, NULL, 'Owner catalog:', 'SELECT cat_owner.id AS id, cat_owner.id as idval FROM cat_owner WHERE id IS NOT NULL', NULL, true, 5, 4, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('psector_type_vdefault', 'config', 'Default value of psector type', 'role_master', NULL, NULL, 'Psector type:', 'SELECT plan_psector_cat_type.id AS id, plan_psector_cat_type.name as idval FROM plan_psector_cat_type WHERE id IS NOT NULL', NULL, true, 7, 1, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_ignore_groundwater', 'epaoptions', 'Value of head tolerance, which is set to YES if groundwater calculations should be ignored when a project file contains aquifer objects. ', 'role_epa', NULL, 'IGNORE_GROUNDWATER', 'Ignore groundwater:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_yesno''', NULL, true, 2, 7, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'NO', 'grl_general_2', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_flow_routing', 'epaoptions', 'Value of  flow routing,which determines which method is used to route flows through the drainage system', 'role_epa', NULL, 'FLOW_ROUTING', 'Flow routing:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_options_fr''', NULL, true, 1, 2, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'DYNWAVE', 'grl_general_1', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('psector_rotation_vdefault', 'config', 'Default value of psector rotation', 'role_master', NULL, NULL, 'Psector rotation:', NULL, NULL, true, 7, 5, 'utils', false, NULL, NULL, NULL, false, 'double', 'spinbox', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('builtdate_vdefault', 'config', 'Default value of feature''s builtdate', 'role_edit', NULL, NULL, 'Builtdate:', NULL, NULL, true, 3, 5, 'utils', false, NULL, 'builtdate', NULL, false, 'date', 'datepickertime', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('cf_keep_opened_edition', 'config', 'If true, keeps opened the QGIS edition after inserting the feature. If false, QGIS edition closes automatically', 'role_edit', NULL, NULL, 'Keep opened edition:', NULL, NULL, true, 8, 2, 'utils', false, NULL, NULL, NULL, false, 'boolean', 'check', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('parameter_vdefault', 'config', 'Default value of parameter of an event', 'role_om', NULL, NULL, 'Parameter:', 'SELECT om_visit_parameter.id AS id, om_visit_parameter.id AS idval FROM om_visit_parameter WHERE id IS NOT NULL', NULL, true, 2, 2, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('edit_arc_division_dsbl', 'config', 'If true, arc won''t be divided into two after inserting a new node over the existing arc', 'role_edit', NULL, NULL, 'Disable arc division on node insert:', NULL, NULL, true, 8, 3, 'utils', false, NULL, NULL, NULL, false, 'boolean', 'check', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('plan_arc_vdivision_dsbl', 'config', 'If false, when you insert a planified node over an arc, this will be divided with two planified new arcs. This parameter is related to edit_arc_division_dsbl', 'role_master', NULL, NULL, 'Dissable arc vdiv on node insert:', NULL, NULL, true, 7, 10, 'utils', false, NULL, NULL, NULL, false, 'boolean', 'check', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('psector_vdefault', 'config', 'Default value of psector parameter', 'role_master', NULL, NULL, 'Psector (Alternative):', 'SELECT plan_psector.psector_id AS id,  plan_psector.name as idval FROM plan_psector WHERE psector_id IS NOT NULL', NULL, true, 7, 2, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('psector_gexpenses_vdefault', 'config', 'Default value of psector general expenses parameter', 'role_master', NULL, NULL, 'Psector gexpenses:', NULL, NULL, true, 7, 6, 'utils', false, NULL, NULL, NULL, false, 'double', 'spinbox', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('cad_tools_base_layer_vdefault', NULL, 'Selected layer will be the only one which allows snapping using CAD tools', 'role_edit', NULL, NULL, 'CAD tools base layer:', NULL, NULL, false, NULL, NULL, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('edit_noderotation_update_dissbl', 'config', 'If true, the automatic rotation calculation on the nodes is disabled. Used for an absolute manual update of rotation field', 'role_edit', NULL, NULL, 'Disable node rotation on update:', NULL, NULL, true, 8, 4, 'utils', false, NULL, NULL, NULL, false, 'boolean', 'check', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_report_start_date', 'epaoptions', 'Value of report start date, which is the date when reporting of results is to begin', 'role_epa', NULL, 'REPORT_START_DATE', 'Report start date:', NULL, NULL, true, 13, 15, 'ud', false, NULL, NULL, NULL, false, 'date', 'datepickertime', true, NULL, '01/01/2017', 'grl_date_13', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_tempdir', 'epaoptions', 'Value of tempdir, which provides the name of a file directory (or folder) where SWMM writes its temporary files', 'role_epa', NULL, 'TEMPDIR', 'Tempdir:', NULL, NULL, true, 14, 31, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, NULL, 'grl_date_14', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_ignore_rainfall', 'epaoptions', 'Value of ignore rainfall, which is set to YES if all rainfall data and runoff calculations should be ignored', 'role_epa', NULL, 'IGNORE_RAINFALL', 'Ignore rainfall:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_yesno''', NULL, true, 2, 5, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'NO', 'grl_general_2', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_ignore_routing', 'epaoptions', 'Value of ignore routing, which is set to YES if only runoff should be computed even if the project contains drainage system links and nodes', 'role_epa', NULL, 'IGNORE_ROUTING', 'Ignore routing:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_yesno''', NULL, true, 2, 8, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'NO', 'grl_general_2', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_ignore_snowmelt', 'epaoptions', 'Value of ignore snowmelt, which is set to YES if snowmelt calculations should be ignored when a project file contains snow pack objects', 'role_epa', NULL, 'IGNORE_SNOWMELT', 'Ignore snowmelt:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_yesno''', NULL, true, 2, 6, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'NO', 'grl_general_2', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_link_offsets', 'epaoptions', 'Value of link offsets, which determines the convention used to specify the position of a link offset above the invert of its connecting node', 'role_epa', NULL, 'LINK_OFFSETS', 'Link offsets:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_options_lo''', NULL, true, 1, 3, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'ELEVATION', 'grl_general_1', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('virtual_polygon_vdefault', 'config', 'Default name od polygon virtual layer', 'role_edit', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, 'utils', false, NULL, NULL, NULL, false, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO audit_cat_param_user VALUES ('inp_options_infiltration', 'epaoptions', 'Value of infiltration, which selects a model for computing infiltration of rainfall into the upper soil zone of subcatchments', 'role_epa', NULL, 'INFILTRATION', 'Infiltration:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_options_in''', NULL, true, 2, 37, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'HORTON', 'grl_general_2', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_end_date', 'epaoptions', 'Value of end date, which is the date when the simulation is to end', 'role_epa', NULL, 'END_DATE', 'End date:', NULL, NULL, true, 13, 13, 'ud', false, NULL, NULL, NULL, false, 'date', 'datepickertime', true, NULL, '01/02/2017', 'grl_date_13', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_report_start_time', 'epaoptions', 'Value of report start time, which is the time of day on the report starting date when reporting is to begin', 'role_epa', NULL, 'REPORT_START_TIME', 'Report start time:', NULL, NULL, true, 13, 16, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, '00:00:00', 'grl_date_13', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_variable_step', 'epaoptions', 'Value of variable step, which is a safety factor applied to a variable time step computed for each time period under dynamic wave flow routing', 'role_epa', NULL, 'VARIABLE_STEP', 'Variable step:', NULL, NULL, true, 1, 25, 'ud', false, NULL, NULL, NULL, false, 'double', 'spinbox', true, NULL, NULL, 'grl_general_1', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_dry_step', 'epaoptions', 'Value of dry step, which is the time step length used for runoff computations (consisting essentially of pollutant buildup) during periods when there is no rainfall and no ponded water. ', 'role_epa', NULL, 'DRY_STEP', 'Dry step:', NULL, NULL, true, 13, 22, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, '01:00:00', 'grl_date_13', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_skip_steady_state', 'epaoptions', 'Value of skip steady state, which should be set to YES if flow routing computations should be skipped during steady state periods of a simulation during which the last set of computed flows will be used', 'role_epa', NULL, 'SKIP_STEADY_STATE', 'Skip steady state:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_yesno''', NULL, true, 1, 10, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'NO', 'grl_general_1', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_routing_step', 'epaoptions', 'Value of routing step, which is the time step length in seconds used for routing flows and water quality constituents through the conveyance system', 'role_epa', NULL, 'ROUTING_STEP', 'Routing step:', NULL, NULL, true, 14, 23, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, '00:00:02', 'grl_date_14', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_report_step', 'epaoptions', 'Value of report step, which is the time interval for reporting of computed results', 'role_epa', NULL, 'REPORT_STEP', 'Report step:', NULL, NULL, true, 13, 20, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, '00:05:00', 'grl_date_13', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_report_input', 'epaoptions', 'Value of input, which specifies whether or not a summary of the input data should be provided in the output report', 'role_epa', NULL, 'INPUT', 'Input:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_yesno''', NULL, true, 17, 1, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'YES', 'grl_reports_17', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_report_continuity', 'epaoptions', 'Value of continuity, which specifies whether continuity checks should be reported or not', 'role_epa', NULL, 'CONTINUITY', 'Continuity:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_yesno''', NULL, true, 17, 2, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'YES', 'grl_reports_17', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('state_vdefault', 'config', 'Value of state parameter', 'role_edit', NULL, NULL, 'State:', 'SELECT id AS id , name as idval  FROM value_state WHERE id IS NOT NULL', NULL, true, 3, 1, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('statetype_plan_vdefault', 'config', 'Default value of psector state type parameter', 'role_master', NULL, NULL, 'State type plan:', 'SELECT id as id, name as idval FROM value_state_type WHERE id IS NOT NULL AND state = 2', '', true, 7, 3, 'utils', false, NULL, 'state_type', NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('exploitation_vdefault', 'config', 'Default value of exploitation parameter', 'role_edit', NULL, NULL, 'Exploitation:', 'SELECT expl_id AS id , name as idval FROM exploitation WHERE expl_id IS NOT NULL', NULL, true, 4, 1, 'utils', true, NULL, 'expl_id', NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('from_date_vdefault', 'config', 'Default value of start date used in a date selector', 'role_basic', NULL, NULL, 'From date:', NULL, NULL, true, 1, 3, 'utils', false, NULL, NULL, NULL, false, 'date', 'datepickertime', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('to_date_vdefault', 'config', 'Default value of end date used in a date selector', 'role_basic', NULL, NULL, 'To date:', NULL, NULL, true, 1, 4, 'utils', false, NULL, NULL, NULL, false, 'date', 'datepickertime', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('document_type_vdefault', 'config', 'Default value of document type', 'role_basic', NULL, NULL, 'Document type:', 'SELECT doc_type.id AS id, doc_type.id AS idval FROM doc_type WHERE id IS NOT NULL', NULL, true, 1, 5, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('om_param_type_vdefault', 'config', 'Default value of parameter type of OM', 'role_om', NULL, NULL, 'Parameter type:', 'SELECT om_visit_parameter_type.id AS id, om_visit_parameter_type.id as idval FROM om_visit_parameter_type WHERE id IS NOT NULL', NULL, true, 2, 1, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('workcat_id_end_vdefault', 'config', 'Default value of workend catalog', 'role_edit', NULL, NULL, 'Workcat end id:', 'SELECT cat_work.id AS id,cat_work.id as idval FROM cat_work WHERE id IS NOT NULL', NULL, true, 3, 7, 'utils', false, NULL, 'workcat_id_end', '0', false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_ignore_quality', 'epaoptions', 'Value of ignore quality, which is set to YES if pollutant washoff, routing, and treatment should be ignored in a project that has pollutants defined', 'role_epa', NULL, 'IGNORE_QUALITY', 'Ignore quality:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_yesno''', NULL, true, 2, 9, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'NO', 'grl_general_2', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('virtual_line_vdefault', 'config', 'Default name od line virtual layer', 'role_edit', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, 'utils', false, NULL, NULL, NULL, false, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO audit_cat_param_user VALUES ('virtual_point_vdefault', 'config', 'Default name od point virtual layer', 'role_edit', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, 'utils', false, NULL, NULL, NULL, false, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO audit_cat_param_user VALUES ('edit_arc_downgrade_force', 'config', 'If true, allows to force arcs downgrade although they have other connected elements', 'role_edit', NULL, NULL, 'Force arc downgrade:', NULL, NULL, true, 8, 7, 'utils', false, NULL, NULL, NULL, false, 'boolean', 'check', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('dim_tooltip', 'config', 'If true, shows tooltip of selected node in order to capture it using dimensioning tool', 'role_edit', NULL, NULL, 'Dimensioning tooltip:', NULL, NULL, true, 8, 1, 'utils', false, NULL, NULL, NULL, false, 'boolean', 'check', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('statetype_end_vdefault', 'config', 'Default value of state type end parameter', 'role_edit', NULL, NULL, 'State type end:', 'SELECT id as id, name as idval FROM value_state_type WHERE id IS NOT NULL AND state = 0', NULL, true, 3, 3, 'utils', false, NULL, 'state_type', NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('statetype_vdefault', 'config', 'Default value of state type parameter', 'role_edit', NULL, NULL, 'State type:', 'SELECT id as id, name as idval FROM value_state_type WHERE id IS NOT NULL AND state = 1', NULL, true, 3, 2, 'utils', false, NULL, 'state_type', NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('workcat_vdefault', 'config', 'Default value of work catalog', 'role_edit', NULL, NULL, 'Workcat id:', 'SELECT cat_work.id AS id,cat_work.id as idval FROM cat_work WHERE id IS NOT NULL', NULL, true, 3, 4, 'utils', false, 'workcat_id', NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('sector_vdefault', 'config', 'Default value of sector parameter', 'role_edit', NULL, NULL, 'Sector:', 'SELECT sector_id as id, name as idval FROM sector WHERE sector_id IS NOT NULL', NULL, true, 4, 4, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('elementcat_vdefault', 'config', 'Default value of element catalog', 'role_edit', NULL, NULL, 'Element catalog:', 'SELECT cat_element.id as id, cat_element.id as idval FROM cat_element WHERE id IS NOT NULL', NULL, true, 11, 2, 'utils', false, 'elementcat_id', NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('soilcat_vdefault', 'config', 'Default value of soilcat catalog', 'role_edit', NULL, NULL, 'Soil catalog:', 'SELECT cat_soil.id AS id, cat_soil.id as idval FROM cat_soil WHERE id IS NOT NULL', NULL, true, 5, 3, 'utils', false, 'soilcat_id', NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('verified_vdefault', 'config', 'Default value of verified parameter', 'role_edit', NULL, NULL, 'Verified:', 'SELECT value_verified.id AS id, value_verified.id as idval  FROM value_verified WHERE id IS NOT NULL', NULL, true, 5, 5, 'utils', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('edit_connect_force_downgrade_linkvnode', 'config', 'If true, when a connec is downgraded, associated link and vnode are also downgraded', 'role_edit', NULL, NULL, 'Force link & vnode downgrade:', NULL, NULL, true, 8, 8, 'utils', false, NULL, NULL, NULL, false, 'boolean', 'check', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_end_time', 'epaoptions', 'Value of end time, which is the time of day on the ending date when the simulation will end', 'role_epa', NULL, 'END_TIME', 'End time:', NULL, NULL, true, 13, 14, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, '03:00:00', 'grl_date_13', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('gratecat_vdefault', 'config', 'Default value of grate catalog', 'role_edit', NULL, NULL, 'Grate catalog:', 'SELECT id AS id, id AS idval FROM cat_grate WHERE id IS NOT NULL', NULL, true, 12, 3, 'ud', false, NULL, 'connecat_id', NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_force_main_equation', 'epaoptions', 'Value of force main equation, which establishes whether the Hazen-Williams (H-W) or the Darcy-Weisbach (D-W) equation will be used to compute friction losses for pressurized flow in conduits that have been assigned a Circular Force Main crosssection shape', 'role_epa', NULL, 'FORCE_MAIN_EQUATION', 'Force main equation:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_options_fme''', NULL, true, 11, 4, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'H-W', 'grl_dyn_11', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_wet_step', 'epaoptions', 'Value of wet step, which is the time step length used to compute runoff from subcatchments during periods of rainfall or when ponded water still remains on the surface', 'role_epa', NULL, 'WET_STEP', 'Wet step:', NULL, NULL, true, 14, 21, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, '00:05:00', 'grl_date_14', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('qgistemplate_folder_path', 'config', 'Default path to a folder where QGIS templates are stored', 'role_edit', NULL, NULL, 'QGIS template path:', NULL, NULL, false, NULL, NULL, 'utils', false, NULL, NULL, NULL, false, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_sys_flow_tol', 'epaoptions', 'Flow tolerance used on the computation', 'role_epa', NULL, 'SYS_FLOW_TOL', 'Sys flow tol:', NULL, NULL, true, 14, 34, 'ud', false, NULL, NULL, NULL, false, 'integer', 'linetext', true, NULL, '5', 'grl_date_14', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_report_links', 'epaoptions', 'Value of links, which  gives a list of links whose results are to be reported', 'role_epa', NULL, 'LINKS', 'Links:', NULL, NULL, true, 18, 7, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, 'ALL', 'grl_reports_18', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_report_subcatchments', 'epaoptions', 'Value of subcatchments, which gives a list of subcatchments whose results are to be reported', 'role_epa', NULL, 'SUBCATCHMENTS', 'Subcatchments:', NULL, NULL, true, 18, 5, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, 'ALL', 'grl_reports_18', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_report_nodes', 'epaoptions', 'Value of node, which gives a list of nodes whose results are to be reported', 'role_epa', NULL, 'NODES', 'Nodes:', NULL, NULL, true, 18, 6, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, 'ALL', 'grl_reports_18', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_report_flowstats', 'epaoptions', 'Value of flowstats, which specifies whether summary flow statistics should be reported or not', 'role_epa', NULL, 'FLOWSTATS', 'Flowstats:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_yesno''', NULL, true, 17, 3, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'YES', 'grl_reports_17', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('dma_vdefault', 'config', 'Default value of dma parameter', 'role_edit', NULL, NULL, 'Dma:', 'SELECT dma_id as id, name as idval FROM dma WHERE dma_id IS NOT NULL ', 'exploitation_vdefault', true, 4, 3, 'utils', false, 'AND expl_id=', 'dma_id', NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('psector_vat_vdefault', 'config', 'Default value of psector vat value', 'role_master', NULL, NULL, 'Psector vat:', NULL, NULL, true, 7, 7, 'utils', false, NULL, NULL, NULL, false, 'double', 'spinbox', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('psector_scale_vdefault', 'config', 'Default value of psector scale', 'role_master', NULL, NULL, 'Psector scale:', NULL, NULL, true, 7, 4, 'utils', false, NULL, NULL, NULL, false, 'double', 'spinbox', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('search_municipality_vdefault', 'config', 'Selected municipality will be the one in which the address will be searched', 'role_basic', NULL, NULL, 'Search municipality:', 'SELECT muni_id AS id, name AS idval FROM ext_municipality WHERE muni_id IS NOT NULL', NULL, true, 1, 2, 'utils', false, NULL, 'muni_id', NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('municipality_vdefault', 'config', 'Default value of municipality parameter', 'role_edit', NULL, NULL, 'Municipality:', 'SELECT muni_id AS id, name AS idval FROM ext_municipality WHERE muni_id IS NOT NULL ', NULL, true, 4, 2, 'utils', false, NULL, 'muni_id', NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('psector_measurement_vdefault', 'config', 'Default value of psector measurement parameter', 'role_master', NULL, NULL, 'Psector measurement:', NULL, NULL, true, 7, 9, 'utils', false, NULL, NULL, NULL, false, 'double', 'spinbox', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_allow_ponding', 'epaoptions', 'Value of pounding, which determines whether excess water is allowed to collect atop nodes and be re-introduced into the system as conditions permit', 'role_epa', NULL, 'ALLOW_PONDING', 'Allow ponding:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_yesno''', NULL, true, 1, 30, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'YES', 'grl_general_1', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_flow_units', 'epaoptions', 'Value of flow units, makes a choice of flow units', 'role_epa', NULL, 'FLOW_UNITS', 'Flow units:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_options_fu''', NULL, true, 1, 1, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'CMS', 'grl_general_1', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('nodetype_vdefault', 'config', 'Default value of node type', 'role_edit', NULL, NULL, 'Node Type:', 'SELECT id AS id, id AS idval FROM node_type WHERE id IS NOT NULL', NULL, true, 9, 1, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('gullycat_vdefault', 'config', 'Default value of gully type', 'role_edit', NULL, NULL, 'Gully catalog:', 'SELECT id AS id, id AS idval FROM gully_type WHERE id IS NOT NULL', NULL, true, 12, 2, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('search_exploitation_vdefault', 'config', 'Selected exploitation will be the one in which the features will be searched', 'role_basic', NULL, NULL, 'Search exploitation:', 'SELECT expl_id AS id , name as idval FROM exploitation WHERE expl_id IS NOT NULL', NULL, true, 1, 1, 'utils', false, NULL, 'expl_id', NULL, false, 'string', 'combo', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_start_date', 'epaoptions', 'Value of start date, which is the date when the simulation begins', 'role_epa', NULL, 'START_DATE', 'Start date:', NULL, NULL, true, 14, 11, 'ud', false, NULL, NULL, NULL, false, 'date', 'datepickertime', true, NULL, '01/01/2017', 'grl_date_14', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_start_time', 'epaoptions', 'Value of start time, which is the time of day on the starting date when the simulation begins', 'role_epa', NULL, 'START_TIME', 'Start time:', NULL, NULL, true, 14, 12, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, '00:00:00', 'grl_date_14', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_sweep_end', 'epaoptions', 'Value of sweep end, which is the day of the year (month/day) when street sweeping operations end', 'role_epa', NULL, 'SWEEP_END', 'Sweep end:', NULL, NULL, true, 14, 18, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, '12/31', 'grl_date_14', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_sweep_start', 'epaoptions', 'Value of sweep start, which is the day of the year (month/day) when street sweeping operations begin', 'role_epa', NULL, 'SWEEP_START', 'Sweep start:', NULL, NULL, true, 14, 17, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, '01/01', 'grl_date_14', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_max_trials', 'epaoptions', 'Value of trials, which are the maximum number of trials used to solve network hydraulics at each hydraulic time step of a simulation. ', 'role_epa', NULL, 'MAX_TRIALS', 'Max trials:', NULL, NULL, true, 12, 32, 'ud', false, NULL, NULL, NULL, false, 'integer', 'linetext', true, NULL, '0', 'grl_dyn_12', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_dry_days', 'epaoptions', 'Value of dry days, which is the number of days with no rainfall prior to the start of the simulation. ', 'role_epa', NULL, 'DRY_DAYS', 'Dry days:', NULL, NULL, true, 13, 19, 'ud', false, NULL, NULL, NULL, false, 'integer', 'linetext', true, NULL, '10', 'grl_date_13', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_inertial_damping', 'epaoptions', 'Value of inertial damping, which indicates how the inertial terms in the Saint Venant momentum equation will be handled under dynamic wave flow routing', 'role_epa', NULL, 'INERTIAL_DAMPING', 'Inertial damping:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_options_id''', NULL, true, 11, 26, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'NONE', 'grl_dyn_11', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_lat_flow_tol', 'epaoptions', 'Lateral flow tolerance used on the computation', 'role_epa', NULL, 'LAT_FLOW_TOL', 'Lat flow tol:', NULL, NULL, true, 11, 35, 'ud', false, NULL, NULL, NULL, false, 'integer', 'linetext', true, NULL, '5', 'grl_dyn_11', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_report_controls', 'epaoptions', 'Value of controls, which specifies whether all control actions taken during a simulation should be listed or not', 'role_epa', NULL, 'CONTROLS', 'Controls:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_yesno''', NULL, true, 17, 4, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'YES', 'grl_reports_17', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_normal_flow_limited', 'epaoptions', 'Value of normal flow limited, which specifies which condition is checked to determine if flow in a conduit is supercritical and should thus be limited to the normal flow', 'role_epa', NULL, 'NORMAL_FLOW_LIMITED', 'Normal flow limited:', 'SELECT idval as id, idval FROM inp_typevalue WHERE typevalue = ''inp_value_options_nfl''', NULL, true, 12, 27, 'ud', false, NULL, NULL, NULL, false, 'string', 'combo', true, NULL, 'BOTH', 'grl_dyn_12', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_min_slope', 'epaoptions', 'Value of minimum slope, which is the minimum value allowed for a conduit’s slope (%)', 'role_epa', NULL, 'MIN_SLOPE', 'Min slope:', NULL, NULL, true, 1, 29, 'ud', false, NULL, NULL, NULL, false, 'double', 'spinbox', true, NULL, '0.00', 'grl_general_1', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_rtc_period_id', 'epaoptions', 'Billing period used to choose demands in order to export to SWMM', 'role_epa', NULL, 'RTC_PERIOD_ID', 'Rtc period id:', NULL, NULL, FALSE, 9, 36, 'ud', false, NULL, NULL, NULL, false, 'string', 'linetext', true, NULL, NULL, 'grl_crm_9', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_min_surfarea', 'epaoptions', 'Value of minimum surfarea, which is a minimum surface area used at nodes when computing changes in water depth under dynamic wave routing', 'role_epa', NULL, 'MIN_SURFAREA', 'Min surfarea:', NULL, NULL, true, 12, 28, 'ud', false, NULL, NULL, NULL, false, 'double', 'spinbox', true, NULL, '0.00', 'grl_dyn_12', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_head_tolerance', 'epaoptions', 'Value of head tolerance, which defines then tolerance of head on computation', 'role_epa', NULL, 'HEAD_TOLERANCE', 'Head tolerance:', NULL, NULL, true, 11, 33, 'ud', false, NULL, NULL, NULL, false, 'double', 'spinbox', true, NULL, '0.000', 'grl_dyn_11', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_param_user VALUES ('inp_options_lengthening_step', 'epaoptions', 'Value of lengthening step, which is a time step, in seconds, used to lengthen conduits under dynamic wave routing, so that they meet the Courant stability criterion under fullflow conditions', 'role_epa', NULL, 'LENGTHENING_STEP', 'Lengthening step:', NULL, NULL, true, 11, 24, 'ud', false, NULL, NULL, NULL, false, 'double', 'spinbox', true, NULL, '1', 'grl_dyn_11', NULL, NULL, NULL, NULL, NULL, NULL, false);


