/*
This file is part of Giswater 3
The program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This version of Giswater is provided by Giswater Association
*/


SET search_path = SCHEMA_NAME, public, pg_catalog;




INSERT INTO audit_cat_table VALUES ('sys_csv2pg_config', 'System table', 'Table to configure exportation parameters', 'role_admin', 1, NULL, NULL, 0, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('inp_typevalue', 'Auxiliar view', 'Unfiltered view with no state and no sector', 'role_admin', 2, NULL, NULL, 0, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('vu_arc', 'Auxiliar view', 'Unfiltered view with no state and no sector', NULL, 0, NULL, NULL, 0, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('vu_node', 'Auxiliar view', 'Unfiltered view with no state and no sector', NULL, 0, NULL, NULL, 0, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('vu_connec', 'Auxiliar view', 'Unfiltered view with no state and no sector', NULL, 0, NULL, NULL, 0, NULL, NULL, NULL, false);


UPDATE audit_cat_table SET description='Catalog of sequences' , sys_role_id='role_admin' WHERE id='audit_cat_sequence';
UPDATE audit_cat_table SET context= 'User interface view', description='Shows documents related to psectors' , sys_role_id='role_admin' WHERE id='v_ui_doc_x_psector';
UPDATE audit_cat_table SET context= 'User interface view', description='Shows corporate customitzation of hydrometers data' , sys_role_id='role_admin' WHERE id='v_ui_hydrometer';
UPDATE audit_cat_table SET context= 'User interface view', description='Shows all workcat polygoni features' , sys_role_id='role_admin' WHERE id='v_ui_workcat_polygon_all';



-- 2019/03/30

UPDATE sys_csv2pg_cat SET csv_structure='The csv file generated is according standard INP file of EPA software' WHERE id=10;
UPDATE sys_csv2pg_cat SET csv_structure='The csv file needs the standard RPT file structure of EPA software' WHERE id=11;
UPDATE sys_csv2pg_cat SET csv_structure='The csv file needs the standard INP file structure of EPA software' WHERE id=12;



-- 2019/03/29
delete from audit_cat_function;


INSERT INTO audit_cat_function VALUES (2436, 'gw_fct_plan_audit_check_data', 'utils', 'function', '{"featureType":""}', '[{"widgetname":"resultId", "label":"Result Id:","widgettype":"text","datatype":"string","layout_name":"grl_option_parameters","layout_order":1,"value":""}]', NULL, 'The function allows the possibility to find errors and data inconsistency before first budget calculation. It checks on PLAN feature tables prices and geometry mandatory data to enable the calculation.', 'role_master', false, true, 'Check plan missing/wrong data before prices', true);
INSERT INTO audit_cat_function VALUES (2632, 'gw_trg_visit_update_enddate', 'utils', 'trigger function', NULL, NULL, NULL, 'Trigger to update the enddate of visits', 'role_basic', true, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2544, 'gw_trg_link_connecrotation_update', 'utils', 'trigger function', NULL, NULL, NULL, 'Updates the rotation of connecs related to the azimut of link', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2534, 'gw_fct_repair_link', 'utils', '{"featureType":"connec"}', NULL, NULL, 'Function is not parametrized yet. Only works with the whole layers of v_edit_arc, v_edit_link, v_edit_connec and v_edit_vnode', 'Function allows to conected link geometries defined by user with the network. Function is not parametrized yet. It works: Selection: All elements from connec, arc and link tables. Parameters:  Harcoded values (0,5 mts for buffer).', 'role_edit', false, false, 'Repair link reconnecting to connec/gully/arc or vnode', false);
INSERT INTO audit_cat_function VALUES (2302, 'gw_fct_anl_node_topological_consistency', 'ws', 'function', '{"featureType":"node"}', NULL, NULL, 'Check topology assistant. Helps user  to identify nodes with more /less arcs that must be connected in function of the num_arcs field (node_type table)', 'role_edit', false, true, 'Check node topological consistency', true);
INSERT INTO audit_cat_function VALUES (2202, 'gw_fct_anl_arc_intersection', 'ud', 'function', '{"featureType":"arc"}', NULL, NULL, 'Check topology assistant.  Identifies intersections againts on the arc table', 'role_edit', false, true, 'Check arcs intersected', true);
INSERT INTO audit_cat_function VALUES (1248, 'gw_trg_gully_update', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2224, 'gw_fct_pg2epa_nodarc', 'ud', 'function', NULL, NULL, NULL, 'Transform node to arcs (in case that flow regulator must be designed as a node)', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2204, 'gw_fct_anl_arc_inverted', 'ud', 'function', '{"featureType":"arc"}', NULL, NULL, 'Check topology assistant. Identifies arcs that have the slope in a oposite sense that the direction', 'role_edit', false, true, 'Check arcs with the slope inverted', true);
INSERT INTO audit_cat_function VALUES (2212, 'gw_fct_anl_node_topological_consistency', 'ud', 'function', '{"featureType":"node"}', NULL, NULL, 'Check topology assistant. Helps user  to identify nodes with more /less arcs that must be connected in function of the num_arcs field (node_type table)', 'role_edit', false, true, 'Check node topological consistency', true);
INSERT INTO audit_cat_function VALUES (2106, 'gw_fct_anl_connec_duplicated', 'utils', 'function', '{"featureType":"connec"}', NULL, NULL, 'Check topology assistant. To review how many connecs are duplicated', 'role_edit', false, true, 'Check connecs duplicated', true);
INSERT INTO audit_cat_function VALUES (2206, 'gw_fct_anl_node_exit_upper_intro', 'ud', 'function', '{"featureType":"node"}', NULL, NULL, 'Check topology assistant.  Identifies nodes that all the exit arcs are upper that all the entry arcs. ', 'role_edit', false, true, 'Check nodes with exit arcs upper than entry arcs', true);
INSERT INTO audit_cat_function VALUES (2126, 'gw_fct_node_replace', 'utils', 'function', NULL, NULL, NULL, 'Replace one node on service for another one, copying all attributes, setting old one on obsolete and reconnecting arcs to the new node', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2102, 'gw_fct_anl_arc_no_startend_node', 'utils', 'function', '{"featureType":"arc"}', '[{"widgetname":"arcSearchNodes", "label":"Start/end points buffer","widgettype":"text","datatype":"float","layout_name":"grl_option_parameters","layout_order":1, "value":"0.5"}]', NULL, 'Check topology assistant. To review how many arcs do not have start or end nodes', 'role_edit', false, true, 'Check arcs without node start/end', true);
INSERT INTO audit_cat_function VALUES (2108, 'gw_fct_anl_node_duplicated', 'utils', 'function', '{"featureType":"node"}', '[{"widgetname":"nodeTolerance", "label":"Node tolerance:", "widgettype":"spinbox","datatype":"float","layout_name":"grl_option_parameters","layout_order":1,"value":0.01}]', NULL, 'Check topology assistant. To review how many nodes are duplicated', 'role_edit', false, true, 'Check nodes duplicated', true);
INSERT INTO audit_cat_function VALUES (2430, 'gw_fct_pg2epa_check_data', 'utils', 'function', '{"featureType":""}', '[{"widgetname":"resultId", "label":"Result Id:","widgettype":"text","datatype":"string","layout_name":"grl_option_parameters","layout_order":1,"value":""}]', NULL, 'The function allows the possibility to find errors and data inconsistency before first exportation to EPA models. It checks on EPA feature tables hydraulic mandatory data to enable the simulation. It works not only with one layers but also with all layers need on the go2epa process.', 'role_epa', false, true, 'Check epa wrong data after temptative using go2epa', true);
INSERT INTO audit_cat_function VALUES (2496, 'gw_fct_repair_arc', 'utils', 'function', '{"featureType":"", "durationType":"large"}', NULL, 'Function is not parametrized yet. Only works with the whole layers of v_edit_arc and v_edit_node.  Buffer value is taken from system variable "arc_searchnodes"', 'Massive repair function. All the arcs that are not connected with extremal node will be reconected using the parameter arc_searchnodes', 'role_edit', false, false, 'Repair arcs reconnecting with closest nodes', false);
INSERT INTO audit_cat_function VALUES (2618, 'gw_api_setsearch', 'utils', 'api function', NULL, NULL, NULL, 'Search elements by defined fields', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2112, 'gw_fct_arc_fusion', 'utils', 'function', NULL, NULL, NULL, 'Used to fusion two arcs in a unique new one, downgrading the node in case of it is possible to o it', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2616, 'gw_api_setinsert', 'utils', 'api function', NULL, NULL, NULL, 'Set insert feature', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2614, 'gw_api_setgo2epa', 'utils', 'api function', NULL, NULL, NULL, 'Function called to execute changes on go2epa forms', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2612, 'gw_api_setfileinsert', 'utils', 'api function', NULL, NULL, NULL, 'Set insert visit file', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2434, 'gw_fct_om_visit_multiplier', 'utils', 'function', NULL, NULL, NULL, 'This function enables the possibility to multiply the visit from unique one to individual ones in case of massive assignation of visit', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2608, 'gw_api_setdelete', 'utils', 'api function', NULL, NULL, NULL, 'Set delete feature', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2606, 'gw_api_setconfig', 'utils', 'api function', NULL, NULL, NULL, 'Set new config values', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2604, 'gw_api_getvisit', 'utils', 'api function', NULL, NULL, NULL, 'Get visit form fiels', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2602, 'gw_api_gettypeahead', 'utils', 'api function', NULL, NULL, NULL, 'Function called to fill typeahead widgets', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2600, 'gw_api_getsearch', 'utils', 'api function', NULL, NULL, NULL, 'Get search form fields', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2598, 'gw_api_getrowinsert', 'utils', 'api function', NULL, NULL, NULL, 'Function called to get eow insert', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2590, 'gw_api_getlayersfromcoordinates', 'utils', 'api function', NULL, NULL, NULL, 'Get information about layer by coordinates', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2588, 'gw_api_getinsertfeature', 'utils', 'api function', NULL, NULL, NULL, 'Function to insert features', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2586, 'gw_api_getinfoplan', 'utils', 'api function', NULL, NULL, NULL, 'Get information about plan cost', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2584, 'gw_api_getinfofromlist', 'utils', 'api function', NULL, NULL, NULL, 'Function to get info from lists', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2232, 'gw_fct_rpt2pg', 'ud', 'function', NULL, NULL, NULL, 'Called when the importation from rpt file is finished.', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2440, 'gw_fct_utils_csv2pg', 'utils', 'function', NULL, NULL, NULL, 'This function makes importations from csv to PostgreSQL database.  Requires a previous configuration after that every csv is possible to import into database', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2438, 'gw_fct_plan_psector_update_geom', 'utils', 'function', NULL, NULL, NULL, 'This automatic updates the geometry of plan_psector in function of the feature related to', 'role_master', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2322, 'gw_fct_rpt2pg', 'ws', 'function', NULL, NULL, NULL, 'This function is called when the importation from rpt file is finished.', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2120, 'gw_fct_check_delete', 'utils', 'function', NULL, NULL, NULL, 'To check if one feature is deletable or not', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2114, 'gw_fct_arc_divide', 'utils', 'function', NULL, NULL, NULL, 'Used to divide one arc into two news', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2580, 'gw_api_getinfofromcoordinates', 'utils', 'api function', NULL, NULL, NULL, 'Get information by feature coordinates', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2578, 'gw_api_getinfocrossection', 'utils', 'api function', NULL, NULL, NULL, 'Function called to get info of crossection for arc features', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2572, 'gw_api_getchilds', 'utils', 'api function', NULL, NULL, NULL, 'Get child view fields and data', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2670, 'gw_fct_om_check_data', 'utils', 'function',  '{"featureType":""}', NULL, 'Function not parametrized. Works with data needed to use tools of o&m toolbar', 'The function allows the possibility to find errors and data inconsistency before first om process (mincut (ws), profile (ud) , visit (utils)', 'role_om', false, true, 'Check data for o&m process', false);
INSERT INTO audit_cat_function VALUES (2660, 'gw_fct_edit_check_data', 'utils', 'function', NULL, NULL, 'Function not parametrized. Works with whole data used on edit funcionalities', 'The function allows the possibility to find errors and data inconsistency on editable data', 'role_edit', false, true, 'Check inconsistency on editable data', false);
INSERT INTO audit_cat_function VALUES (2240, 'gw_fct_pg2epa_nod2arc_geom', 'ud', 'function', NULL, NULL, NULL, 'Function used to create new geometries for that nodarc with more than one element (additional flow regulators)', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2242, 'gw_fct_cad_add_relative_point', 'utils', 'function', NULL, NULL, NULL, 'Function used as CAD assistant for edit user to place support points using relative coordinates', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2328, 'gw_fct_pg2epa_fill_data', 'ws', 'function', NULL, NULL, NULL, 'Function used to fill data from inventory tables to rpt_inp tables converting nod2arcs features from one node to two nodes and one arc', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1202, 'gw_trg_edit_arc', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2570, 'gw_api_getconfig', 'utils', 'api function', NULL, NULL, NULL, 'Get configs fields and data', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2566, 'gw_api_getattributetable', 'utils', 'api function', NULL, NULL, NULL, 'Get atrribute tcatalog of a feature', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1204, 'gw_trg_edit_connec', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1206, 'gw_trg_edit_gully', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1208, 'gw_trg_edit_inp_arc', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2502, 'gw_fct_utils_role_permisions', 'utils', 'function', NULL, NULL, NULL, 'Deprecated function used to admin role permissons.', 'role_admin', true, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1212, 'gw_trg_edit_man_arc', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1214, 'gw_trg_edit_man_connec', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1216, 'gw_trg_edit_man_gully', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2426, 'gw_fct_audit_schema_repair', 'utils', 'function', NULL, NULL, NULL, 'Deprecated function used to repair schemas.', 'role_admin', true, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1346, 'gw_trg_arc_noderotation_update', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1344, 'gw_trg_topocontrol_arc', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1342, 'gw_trg_rtc_hydrometer', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1340, 'gw_trg_review_audit_node', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1236, 'gw_trg_review_audit_arc', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1218, 'gw_trg_edit_man_node', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1116, 'gw_trg_edit_link', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1114, 'gw_trg_edit_element', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2564, 'gw_api_get_widgetjson', 'utils', 'api function', NULL, NULL, NULL, 'Get widget type of a field', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2610, 'gw_api_setfields', 'utils', 'api function', NULL, NULL, NULL, 'Function called to set fields on feature', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2592, 'gw_api_getlist', 'utils', 'api function', NULL, NULL, NULL, 'Function to call lists', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2222, 'gw_fct_pg2epa', 'ud', 'function', NULL, NULL, NULL, 'Starts the exportation process to inp file', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2648, 'gw_fct_admin_schema_manage_ct', 'utils', 'function', NULL, NULL, NULL, 'Function to manage fk', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1136, 'gw_trg_topocontrol_node', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1138, 'gw_trg_ui_doc', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1140, 'gw_trg_ui_element', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2464, 'gw_fct_node_replace', 'ud', 'function', NULL, NULL, NULL, 'This function enables the possibility to replace one connected node, disconnecting temporary the associated arcs, setting state=0 to node inserting a new one on the same position and reconnecting arcs to new one', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2422, 'gw_fct_audit_log_feature', 'utils', 'function', NULL, NULL, NULL, 'Deprecated function used to audit features. Replaced by customized function of corporate to do this', 'role_admin', true, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1336, 'gw_trg_review_audit_arc', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1142, 'gw_trg_vnode_proximity', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1144, 'gw_trg_vnode_update', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2512, 'gw_fct_utils_csv2pg_import_omvisit', 'utils', 'function', NULL, NULL, NULL, 'Function imports visits from csv file into database', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2514, 'gw_fct_utils_csv2pg_import_elements', 'utils', 'function', NULL, NULL, NULL, 'Function imports elements from csv file into database', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2516, 'gw_fct_utils_csv2pg_import_addfields', 'utils', 'function', NULL, NULL, NULL, 'Function imports personalized fields from csv file into database', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2216, 'gw_fct_flow_exit_recursive', 'ud', 'function', NULL, NULL, NULL, 'Recursive function of flow exit', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2646, 'gw_fct_pg2epa_recursive', 'utils', 'function', NULL, NULL, NULL, 'Function to enable recursive calculations on epa workflow', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2414, 'gw_fct_role_permissions', 'utils', 'function', NULL, NULL, NULL, 'Grant for all relations on database the permissions needed using the audit_cat_table ', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1330, 'gw_trg_edit_unconnected', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1328, 'gw_trg_edit_rtc_hydro_data', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2332, 'gw_fct_pg2epa_valvestatus', 'ws', 'function', NULL, NULL, NULL, 'Function used to set the network valve status using mincut result status, epa tables status or inventory status', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1332, 'gw_trg_man_addfields_control', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', true, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2498, 'gw_trg_visit_event_update_xy', 'utils', 'trigger function', NULL, NULL, NULL, 'Enables the posibility to update the xcoord, ,ycoord columns using position_id and position_value.', 'role_master', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2650, 'gw_fct_admin_schema_lastprocess', 'utils', 'function', NULL, NULL, NULL, 'Function to execute last process on the schema manager end', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2116, 'gw_fct_audit_function', 'utils', 'function', NULL, NULL, NULL, 'To audit all what happens wiht functions', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2220, 'gw_fct_flow_trace_recursive', 'ud', 'function', NULL, NULL, NULL, 'Recursive function of flow trace', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1238, 'gw_trg_review_audit_connec', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2504, 'gw_fct_utils_csv2pg_importblock', 'utils', 'function', NULL, NULL, NULL, 'Enables the possibility to import dxf blocks', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2424, 'gw_fct_audit_schema_check', 'utils', 'function', NULL, NULL, NULL, 'This function analyzes the schema', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1338, 'gw_trg_review_audit_connec', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1320, 'gw_trg_edit_node', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1250, 'gw_trg_man_addfields_value_control', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2548, 'gw_trg_om_visit', 'utils', 'trigger function', NULL, NULL, NULL, 'Manage different issues on visit in function of used variables', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1246, 'gw_trg_edit_macrosector', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1244, 'gw_trg_topocontrol_arc', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1242, 'gw_trg_review_audit_node', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1232, 'gw_trg_edit_subcatchment', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1222, 'gw_trg_edit_raingage', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1220, 'gw_trg_edit_node', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2596, 'gw_api_getpermissions', 'utils', 'api function', NULL, NULL, NULL, 'Get information about permissions', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2582, 'gw_api_getinfofromid', 'utils', 'api function', NULL, NULL, NULL, 'Get information by feature id', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2576, 'gw_api_getgo2epa', 'utils', 'api function', NULL, NULL, NULL, 'Function called to get the epa forms', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2574, 'gw_api_getfeatureinsert', 'utils', 'api function', NULL, NULL, NULL, 'Function to insert features', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2500, 'gw_trg_edit_field_node', 'utils', 'trigger function', NULL, NULL, NULL, 'To update values on field', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2634, 'gw_fct_refresh_mat_view', 'utils', 'function', NULL, NULL, NULL, 'Refresh mat views', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2636, 'gw_fct_admin_schema_renameviews', 'utils', 'function', NULL, NULL, NULL, 'Rename views', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2552, 'gw_fct_admin_role_permissions', 'utils', 'function', NULL, NULL, NULL, 'Function that assignes roles to database', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2550, 'gw_fct_admin_schema_dropdeprecated_rel', 'utils', 'function', NULL, NULL, NULL, 'Function that eliminates deprecated sequences, views, tables and functions', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2638, 'gw_fct_utils_update_dma_hydroval', 'ws', 'function', NULL, NULL, NULL, 'Function to update the values of hydrometers on dmas', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2122, 'gw_fct_clone_schema', 'utils', 'function', NULL, NULL, NULL, 'To clone schema', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2510, 'gw_fct_utils_csv2pg_import_dbprices', 'utils', 'function', NULL, NULL, NULL, 'Function imports prices from csv file into database', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2244, 'gw_fct_mincut_result_overlap', 'ws', 'function', NULL, NULL, NULL, 'Function used to overlap mincuts in order to planificate possible conflicts one each other', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1334, 'gw_trg_node_update', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2562, 'gw_api_get_formfields', 'utils', 'api function', NULL, NULL, NULL, 'Get fields of a form', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2490, 'gw_trg_edit_review_connec', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2492, 'gw_trg_edit_review_audit_connec', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2218, 'gw_fct_flow_trace', 'ud', 'function', NULL, NULL, NULL, 'Analisys of the network identifying all arc and nodes upstream of the selected node.', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2214, 'gw_fct_flow_exit', 'ud', 'function', NULL, NULL, NULL, 'Analisys of the network identifying all arc and nodes downstream of the selected node.', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1318, 'gw_trg_edit_man_node', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1314, 'gw_trg_edit_man_arc', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1312, 'gw_trg_edit_macrodma', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1310, 'gw_trg_edit_inp_node', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1308, 'gw_trg_edit_inp_demand', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1306, 'gw_trg_edit_inp_arc', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1304, 'gw_trg_edit_connec', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1302, 'gw_trg_edit_arc', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2104, 'gw_fct_anl_arc_same_startend', 'utils', 'function', '{"featureType":"arc"}', NULL, NULL, 'Check topology assistant. To review how many arcs have the same node as node1 and node2', 'role_edit', false, true, 'Check arcs with same start/end node', true);
INSERT INTO audit_cat_function VALUES (2230, 'gw_fct_repair_arc_searchnodes', 'utils', 'function', NULL, NULL, NULL, 'Massive repair function. All the arcs that are not connected with extremal node will be reconected using the parameter arc_searchnodes (from config table)', 'role_edit', true, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2538, 'gw_fct_dinlet', 'ws', 'function', NULL, NULL, NULL, 'Function to identify inlets of network.', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2330, 'gw_fct_pg2epa_rtc', 'ws', 'function', NULL, NULL, NULL, 'Function used to connect CRM values on the EPA exportation', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2558, 'gw_api_get_featureinfo', 'utils', 'api function', NULL, NULL, NULL, 'Function to provide information aboute feature', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2560, 'gw_api_get_featureupsert', 'utils', 'api function', NULL, NULL, NULL, 'Function to upsert features', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2594, 'gw_api_getmessage', 'utils', 'api function', NULL, NULL, NULL, 'Get message', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2400, 'gw_fct_mincut_inv_flowtrace', 'ws', 'function', NULL, NULL, NULL, 'This function calculates the area afected by the mincut valve status', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2402, 'gw_fct_mincut_inv_flowtrace_engine', 'ws', 'function', NULL, NULL, NULL, 'Recursive function of mincut', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2318, 'gw_fct_pg2epa_pump_additional', 'ws', 'function', NULL, NULL, NULL, 'This function creates new flow lines for the same pump station as pump as user have been defined on the table inp_pump_additional.', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2306, 'gw_fct_mincut_engine', 'ws', 'function', NULL, NULL, NULL, 'Recursive function of mincut', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2478, 'gw_trg_edit_review_gully', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2520, 'gw_fct_utils_csv2pg_import_epanet_rpt', 'ws', 'function', NULL, NULL, NULL, 'Function imports epanet model results from rpt file into database', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2508, 'gw_fct_getinsertform_vdef', 'utils', 'function', NULL, NULL, NULL, 'Function to serve vdefault for user', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2310, 'gw_fct_mincut_flowtrace_engine', 'ws', 'function', NULL, NULL, NULL, 'Recursive function of mincut', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2308, 'gw_fct_mincut_flowtrace', 'ws', 'function', NULL, NULL, NULL, 'This function calculates what is the area afected for the mincut valve status', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2428, 'gw_fct_edit_element_multiplier', 'utils', 'function', NULL, NULL, NULL, 'This function multiplies on element assigned to multiple features using one unique assignation', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2234, 'gw_fct_pg2epa_fill_data', 'ud', 'function', NULL, NULL, NULL, 'Function used to fill data from inventory tables to rpt_inp tables converting nod2arcs features from one node to two nodes and one arc', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2236, 'gw_fct_pg2epa_join_virtual', 'ud', 'function', NULL, NULL, NULL, 'Function used to join arcs connecteds trhough on virtual arc in order to don''t send to the EPA model that virtual element', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2238, 'gw_fct_pg2epa_nod2arc_data', 'ud', 'function', NULL, NULL, NULL, 'Function used to fill data for nod2arc features', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2444, 'gw_trg_audit_log_feature', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_admin', true, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2416, 'gw_trg_edit_man_gully_pol', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2418, 'gw_trg_edit_man_node_pol', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1210, 'gw_trg_edit_inp_node', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1118, 'gw_trg_edit_om_visits', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2546, 'gw_fct_admin_schema_update', 'utils', 'function', NULL, NULL, NULL, 'Deprecated function used to update schemas', 'role_admin', true, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2432, 'gw_fct_module_activate', 'utils', 'function', NULL, NULL, NULL, 'Deprecated function used to enable the possibility to activate modules', 'role_admin', true, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1316, 'gw_trg_edit_man_connec', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1240, 'gw_trg_review_audit_gully', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2542, 'gw_trg_arc_vnodelink_update', 'utils', 'trigger function', NULL, NULL, NULL, 'Function recreates link when arc was updated', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2486, 'gw_trg_edit_review_arc', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2488, 'gw_trg_edit_review_audit_arc', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2530, 'gw_fct_utils_csv2pg_import_swmm_rpt', 'ud', 'function', NULL, NULL, NULL, 'Function imports swmm model results from rpt file into database', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2528, 'gw_fct_utils_csv2pg_export_swmm_inp', 'ud', 'function', NULL, NULL, NULL, 'Function exports swmm model data from database into inp file', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2524, 'gw_fct_utils_csv2pg_import_swmm_inp', 'ud', 'function', NULL, NULL, NULL, 'Function imports network data from swmm inp file into database', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2532, 'gw_fct_utils_csv2pg_import_epa_inp', 'utils', 'function', NULL, NULL, NULL, 'Function indicates the correct inp data import depending on project type', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2522, 'gw_fct_utils_csv2pg_import_epanet_inp', 'ws', 'function', NULL, NULL, NULL, 'Function imports network data from epanet inp file into database', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2526, 'gw_fct_utils_csv2pg_export_epanet_inp', 'ws', 'function', NULL, NULL, NULL, 'Function exports epanet model data from database into inp file', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2536, 'gw_fct_utils_csv2pg_import_epa_rpt', 'ws', 'function', NULL, NULL, NULL, 'Function indicates the correct rpt data import depending on project type', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2316, 'gw_fct_pg2epa_nod2arc', 'ws', 'function', NULL, NULL, NULL, 'This functions transform node to arcs (in case of valve nodes and pump nodes). ', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2554, 'gw_fct_admin_schema_utils_fk', 'utils', 'function', NULL, NULL, NULL, 'Function that creates foreign keys for utils schema', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2506, 'gw_fct_create_utils_trigger', 'utils', 'function', NULL, NULL, NULL, 'Function to create fk to related tables on utils schema', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2540, 'gw_fct_inlet_flowtrace', 'ws', 'function', NULL, NULL, NULL, 'Auxiliar function to calculate flowtrace of inlet', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2312, 'gw_fct_mincut_valve_unaccess', 'ws', 'function', NULL, NULL, NULL, 'Insert into anl_mincut_result_valve_unaccess valve non accessibles on a specific mincut.', 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2124, 'gw_fct_connec_to_network', 'utils', 'function', NULL, NULL, NULL, 'Massive builder assistant. This function built as many link/vnodes as user connec/gully selects', 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1234, 'gw_trg_node_update', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2468, 'gw_trg_edit_review_audit_node', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2456, 'gw_fct_pg2epa_dscenario', 'ws', 'function', NULL, NULL, NULL, 'This function controls the demand scenario on epanet file exportation', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2460, 'gw_trg_edit_man_connec_pol', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2462, 'gw_trg_edit_man_node_pol', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2470, 'gw_trg_edit_review_arc', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2472, 'gw_trg_edit_review_audit_arc', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2474, 'gw_trg_edit_review_connec', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2476, 'gw_trg_edit_review_audit_connec', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2480, 'gw_trg_edit_review_audit_gully', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2482, 'gw_trg_edit_review_node', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2484, 'gw_trg_edit_review_audit_node', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2128, 'gw_fct_plan_estimate_result', 'utils', 'function', NULL, NULL, NULL, 'Used to insert economic results from calculations on the plan_result_table', 'role_master', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2130, 'gw_fct_state_control', 'utils', 'function', NULL, NULL, NULL, 'To control permisions of users to manage with state=2 and check inconsistency of state updates for arc / nodes, dissabling the update to state=0 if there are arcs (for node) and connecs (for arcs) with state 1 or 2', 'role_admin', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2132, 'gw_state_searchnodes', 'utils', 'function', NULL, NULL, NULL, 'Deprecated function used to check extreme nodes from arcs acording the tolerance parameter defined by user (arc_searchnodes) and the state topologic rules', 'role_admin', true, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1134, 'gw_trg_review_audit_node', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1126, 'gw_trg_edit_vnode', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1124, 'gw_trg_edit_sector', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1122, 'gw_trg_edit_samplepoint', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1120, 'gw_trg_edit_plan_psector', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1128, 'gw_trg_man_addfields_control', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1132, 'gw_trg_review_audit_arc', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2518, 'gw_fct_utils_csv2pg_export_epa_inp', 'utils', 'function', NULL, NULL, NULL, 'Function indicates the correct inp data export depending on project type', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1130, 'gw_trg_plan_psector_x_arc', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_master', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2630, 'gw_api_getgeometry', 'utils', 'api function', NULL, NULL, NULL, 'Function called to pass geometry to client projects', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2628, 'gw_api_gettoolbarbuttons', 'utils', 'api function', NULL, NULL, NULL, 'Function called to define toolbar on client projects', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2622, 'gw_api_setvisit', 'utils', 'api function', NULL, NULL, NULL, 'Set new visit values', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2620, 'gw_api_setsearch_add', 'utils', 'api function', NULL, NULL, NULL, 'Search address by defined fields', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2466, 'gw_trg_edit_review_node', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_om', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2626, 'gw_fct_json_object_set_key', 'utils', 'function', NULL, NULL, NULL, 'Auxiliar function with goal to delete json keys', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2624, 'gw_fct_json_object_delete_keys', 'utils', 'function', NULL, NULL, NULL, 'Auxiliar function with goal to delete json keys', 'role_basic', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2454, 'gw_fct_edit_node_switch_arc_id', 'utils', 'function', NULL, NULL, NULL, 'Function used to switch arc_id', 'role_edit', true, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2420, 'gw_trg_flw_regulator', 'ud', 'trigger function', NULL, NULL, NULL, NULL, 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2458, 'gw_trg_edit_cat_node', 'ws', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2452, 'gw_trg_selector_expl', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2450, 'gw_trg_psector_selector', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_master', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2448, 'gw_trg_edit_psector_x_other', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_master', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2446, 'gw_trg_edit_psector', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_master', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2442, 'gw_trg_node_arc_divide', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2228, 'gw_fct_pg2epa_dump_subcatch', 'ud', 'function', NULL, NULL, NULL, 'Exports the subcatchments in case user have been ckecked the checkbox on form of xportation', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1112, 'gw_trg_edit_dma', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1110, 'gw_trg_edit_dimensions', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1108, 'gw_trg_connec_update', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1106, 'gw_trg_connec_proximity', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1104, 'gw_trg_arc_orphannode_delete', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (1102, 'gw_trg_arc_noderotation_update', 'utils', 'trigger function', NULL, NULL, NULL, NULL, 'role_edit', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2314, 'gw_fct_pg2epa', 'ws', 'function', NULL, NULL, NULL, 'This function starts the exportation process to inp file', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2226, 'gw_fct_pg2epa_flowreg_additional', 'ud', 'function', NULL, NULL, NULL, 'Creates new flow regulator for the same node flow regulator (nodarc) as user have been defined on the tables enabled to do this (inp_flwreg-*)', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2110, 'gw_fct_anl_node_orphan', 'utils', 'function', '{"featureType":"node"}', NULL, NULL, 'Check topology assistant. To review how many nodes are disconnected of the network', 'role_edit', false, true, 'Check nodes orphan', true);
INSERT INTO audit_cat_function VALUES (2208, 'gw_fct_anl_node_flowregulator', 'ud', 'function', '{"featureType":"node"}', NULL, NULL, 'Check topology assistant.  Identifies nodes with more than one exit arc', 'role_edit', false, true, 'Check nodes with more than one exit', true);
INSERT INTO audit_cat_function VALUES (2210, 'gw_fct_anl_node_sink', 'ud', 'function', '{"featureType":"node"}', NULL, NULL, 'Check topology assistant. Identifies nodes not disconnecteds without exit arcs.', 'role_edit', false, true, 'Check nodes as a outfall', true);
INSERT INTO audit_cat_function VALUES (2680, 'gw_fct_pg2epa_inlet_flowtrace', 'ws', 'function', NULL, NULL, NULL, 'Check disconnected arcs on specific epa analysis.', 'role_epa', false, false, NULL, false);
INSERT INTO audit_cat_function VALUES (2118, 'gw_fct_built_nodefromarc', 'utils', 'function', '{"featureType":""}', NULL, 'Function not parametrized. Works with whole layers of arc and node.', 'Massive builder assistant. Built as many nodes as network need to achieve the topologic rules. To do this, all nodes are inserted using the default values of user (catalog, state...)', 'role_admin', false, true, 'Build nodes from start/end of arc without start/end node', false);
INSERT INTO audit_cat_function VALUES (2304, 'gw_fct_mincut', 'ws', 'function', NULL, NULL, 'Function not parametrized yet. Works with the whole layers of v_edit_arc and v_edit_node', 'This function proposes what valves must be closed in a mincut operation', 'role_om', false, false, 'Massive mincut process', false);
