--DROP

ALTER TABLE anl_node ALTER COLUMN node_id DROP NOT NULL;
ALTER TABLE anl_node ALTER COLUMN context DROP NOT NULL;
ALTER TABLE anl_node ALTER COLUMN cur_user DROP NOT NULL;

ALTER TABLE anl_connec ALTER COLUMN connec_id DROP NOT NULL;
ALTER TABLE anl_connec ALTER COLUMN context DROP NOT NULL;
ALTER TABLE anl_connec ALTER COLUMN cur_user DROP NOT NULL;

ALTER TABLE anl_arc ALTER COLUMN arc_id DROP NOT NULL;
ALTER TABLE anl_arc ALTER COLUMN context DROP NOT NULL;
ALTER TABLE anl_arc ALTER COLUMN cur_user DROP NOT NULL;

ALTER TABLE anl_arc_x_node ALTER COLUMN arc_id DROP NOT NULL;
ALTER TABLE anl_arc_x_node ALTER COLUMN node_id DROP NOT NULL;
ALTER TABLE anl_arc_x_node ALTER COLUMN context DROP NOT NULL;
ALTER TABLE anl_arc_x_node ALTER COLUMN cur_user DROP NOT NULL;

--SET

ALTER TABLE anl_node ALTER COLUMN node_id SET NOT NULL;
ALTER TABLE anl_node ALTER COLUMN context SET NOT NULL;
ALTER TABLE anl_node ALTER COLUMN cur_user SET NOT NULL;


ALTER TABLE anl_connec ALTER COLUMN connec_id SET NOT NULL;
ALTER TABLE anl_connec ALTER COLUMN context SET NOT NULL;
ALTER TABLE anl_connec ALTER COLUMN cur_user SET NOT NULL;

ALTER TABLE anl_arc ALTER COLUMN arc_id SET NOT NULL;
ALTER TABLE anl_arc ALTER COLUMN context SET NOT NULL;
ALTER TABLE anl_arc ALTER COLUMN cur_user SET NOT NULL;

ALTER TABLE anl_arc_x_node ALTER COLUMN arc_id SET NOT NULL;
ALTER TABLE anl_arc_x_node ALTER COLUMN node_id SET NOT NULL;
ALTER TABLE anl_arc_x_node ALTER COLUMN context SET NOT NULL;
ALTER TABLE anl_arc_x_node ALTER COLUMN cur_user SET NOT NULL;
