ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN label text;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN dv_querytext text;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN dv_parent_id text;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN isenabled boolean;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN layout_id integer;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN layout_order integer;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN project_type character varying;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN isparent boolean;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN dv_querytext_filterc text;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN feature_field_id text;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN feature_dv_parent_value text;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN isautoupdate boolean;
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN datatype character varying(30);
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN widgettype character varying(30);
ALTER TABLE ws_sample.audit_cat_param_user ADD COLUMN vdefault text;
