--DROP
ALTER TABLE cat_arc ALTER COLUMN arctype_id DROP NOT NULL;

ALTER TABLE cat_node ALTER COLUMN nodetype_id DROP NOT NULL;

ALTER TABLE cat_connec ALTER COLUMN connectype_id DROP NOT NULL;

ALTER TABLE macrodma ALTER COLUMN name DROP NOT NULL;
ALTER TABLE macrodma ALTER COLUMN expl_id DROP NOT NULL;

ALTER TABLE dma ALTER COLUMN name DROP NOT NULL;
ALTER TABLE dma ALTER COLUMN expl_id DROP NOT NULL;

ALTER TABLE sector ALTER COLUMN name DROP NOT NULL;

ALTER TABLE node ALTER COLUMN nodecat_id DROP NOT NULL;
ALTER TABLE node ALTER COLUMN epa_type DROP NOT NULL;
ALTER TABLE node ALTER COLUMN sector_id DROP NOT NULL;
ALTER TABLE node ALTER COLUMN "state" DROP NOT NULL;
ALTER TABLE node ALTER COLUMN dma_id DROP NOT NULL;
ALTER TABLE node ALTER COLUMN expl_id DROP NOT NULL;

ALTER TABLE arc ALTER COLUMN arccat_id DROP NOT NULL;
ALTER TABLE arc ALTER COLUMN epa_type DROP NOT NULL;
ALTER TABLE arc ALTER COLUMN sector_id DROP NOT NULL;
ALTER TABLE arc ALTER COLUMN "state" DROP NOT NULL;
ALTER TABLE arc ALTER COLUMN dma_id DROP NOT NULL;
ALTER TABLE arc ALTER COLUMN expl_id DROP NOT NULL;

ALTER TABLE connec ALTER COLUMN connecat_id DROP NOT NULL;
ALTER TABLE connec ALTER COLUMN sector_id DROP NOT NULL;
ALTER TABLE connec ALTER COLUMN "state" DROP NOT NULL;
ALTER TABLE connec ALTER COLUMN dma_id DROP NOT NULL;
ALTER TABLE connec ALTER COLUMN expl_id DROP NOT NULL;


ALTER TABLE pond ALTER COLUMN "state" DROP NOT NULL;
ALTER TABLE pond ALTER COLUMN dma_id DROP NOT NULL;
ALTER TABLE pond ALTER COLUMN expl_id DROP NOT NULL;

ALTER TABLE pool ALTER COLUMN "state" DROP NOT NULL;
ALTER TABLE pool ALTER COLUMN dma_id DROP NOT NULL;
ALTER TABLE pool ALTER COLUMN expl_id DROP NOT NULL;



--EXTRA NOT NULLS

--ALTER TABLE node ALTER COLUMN inventory DROP NOT NULL;
--ALTER TABLE node ALTER COLUMN state_type DROP NOT NULL;
--ALTER TABLE node ALTER COLUMN workcat_id DROP NOT NULL;
--ALTER TABLE node ALTER COLUMN builtdate DROP NOT NULL;
--ALTER TABLE node ALTER COLUMN verified DROP NOT NULL;
--ALTER TABLE node ALTER COLUMN code DROP NOT NULL;
--ALTER TABLE node ALTER COLUMN the_geom DROP NOT NULL;

--ALTER TABLE arc ALTER COLUMN inventory DROP NOT NULL;
--ALTER TABLE arc ALTER COLUMN state_type DROP NOT NULL;
--ALTER TABLE arc ALTER COLUMN workcat_id DROP NOT NULL;
--ALTER TABLE arc ALTER COLUMN builtdate DROP NOT NULL;
--ALTER TABLE arc ALTER COLUMN verified DROP NOT NULL;
--ALTER TABLE arc ALTER COLUMN code DROP NOT NULL;
--ALTER TABLE arc ALTER COLUMN node_1 DROP NOT NULL;
--ALTER TABLE arc ALTER COLUMN node_2 DROP NOT NULL;
--ALTER TABLE arc ALTER COLUMN the_geom DROP NOT NULL;


--ALTER TABLE connec ALTER COLUMN inventory DROP NOT NULL;
--ALTER TABLE connec ALTER COLUMN state_type DROP NOT NULL;
--ALTER TABLE connec ALTER COLUMN workcat_id DROP NOT NULL;
--ALTER TABLE connec ALTER COLUMN builtdate DROP NOT NULL;
--ALTER TABLE connec ALTER COLUMN verified DROP NOT NULL;
--ALTER TABLE connec ALTER COLUMN code DROP NOT NULL;
--ALTER TABLE connec ALTER COLUMN the_geom DROP NOT NULL;

--SET
ALTER TABLE cat_arc ALTER COLUMN arctype_id SET NOT NULL;

ALTER TABLE cat_node ALTER COLUMN nodetype_id SET NOT NULL;

ALTER TABLE cat_connec ALTER COLUMN connectype_id SET NOT NULL;

ALTER TABLE macrodma ALTER COLUMN name SET NOT NULL;
ALTER TABLE macrodma ALTER COLUMN expl_id SET NOT NULL;

ALTER TABLE dma ALTER COLUMN name SET NOT NULL;
ALTER TABLE dma ALTER COLUMN expl_id SET NOT NULL;

ALTER TABLE sector ALTER COLUMN name SET NOT NULL;

ALTER TABLE node ALTER COLUMN nodecat_id SET NOT NULL;
ALTER TABLE node ALTER COLUMN epa_type SET NOT NULL;
ALTER TABLE node ALTER COLUMN sector_id SET NOT NULL;
ALTER TABLE node ALTER COLUMN "state" SET NOT NULL;
ALTER TABLE node ALTER COLUMN dma_id SET NOT NULL;
ALTER TABLE node ALTER COLUMN expl_id SET NOT NULL;

ALTER TABLE arc ALTER COLUMN arccat_id SET NOT NULL;
ALTER TABLE arc ALTER COLUMN epa_type SET NOT NULL;
ALTER TABLE arc ALTER COLUMN sector_id SET NOT NULL;
ALTER TABLE arc ALTER COLUMN "state" SET NOT NULL;
ALTER TABLE arc ALTER COLUMN dma_id SET NOT NULL;
ALTER TABLE arc ALTER COLUMN expl_id SET NOT NULL;

ALTER TABLE connec ALTER COLUMN connecat_id SET NOT NULL;
ALTER TABLE connec ALTER COLUMN sector_id SET NOT NULL;
ALTER TABLE connec ALTER COLUMN "state" SET NOT NULL;
ALTER TABLE connec ALTER COLUMN dma_id SET NOT NULL;
ALTER TABLE connec ALTER COLUMN expl_id SET NOT NULL;


ALTER TABLE pond ALTER COLUMN "state" SET NOT NULL;
ALTER TABLE pond ALTER COLUMN dma_id SET NOT NULL;
ALTER TABLE pond ALTER COLUMN expl_id SET NOT NULL;

ALTER TABLE pool ALTER COLUMN "state" SET NOT NULL;
ALTER TABLE pool ALTER COLUMN dma_id SET NOT NULL;
ALTER TABLE pool ALTER COLUMN expl_id SET NOT NULL;


--EXTRA NOT NULLS

--ALTER TABLE node ALTER COLUMN inventory SET NOT NULL;
--ALTER TABLE node ALTER COLUMN state_type SET NOT NULL;
--ALTER TABLE node ALTER COLUMN workcat_id SET NOT NULL;
--ALTER TABLE node ALTER COLUMN builtdate SET NOT NULL;
--ALTER TABLE node ALTER COLUMN verified SET NOT NULL;
--ALTER TABLE node ALTER COLUMN code SET NOT NULL;
--ALTER TABLE node ALTER COLUMN the_geom SET NOT NULL;

--ALTER TABLE arc ALTER COLUMN inventory SET NOT NULL;
--ALTER TABLE arc ALTER COLUMN state_type SET NOT NULL;
--ALTER TABLE arc ALTER COLUMN workcat_id SET NOT NULL;
--ALTER TABLE arc ALTER COLUMN builtdate SET NOT NULL;
--ALTER TABLE arc ALTER COLUMN verified SET NOT NULL;
--ALTER TABLE arc ALTER COLUMN code SET NOT NULL;
--ALTER TABLE arc ALTER COLUMN node_1 SET NOT NULL;
--ALTER TABLE arc ALTER COLUMN node_2 SET NOT NULL;
--ALTER TABLE arc ALTER COLUMN the_geom SET NOT NULL;


--ALTER TABLE connec ALTER COLUMN inventory SET NOT NULL;
--ALTER TABLE connec ALTER COLUMN state_type SET NOT NULL;
--ALTER TABLE connec ALTER COLUMN workcat_id SET NOT NULL;
--ALTER TABLE connec ALTER COLUMN builtdate SET NOT NULL;
--ALTER TABLE connec ALTER COLUMN verified SET NOT NULL;
--ALTER TABLE connec ALTER COLUMN code SET NOT NULL;
--ALTER TABLE connec ALTER COLUMN the_geom SET NOT NULL;