/*
This file is part of Giswater
The program is free software: you can redistribute it and/or modify it under the terms of the GNU
General Public License as published by the Free Software Foundation, either version 3 of the License,
or (at your option) any later version.
*/


SET search_path = SCHEMA_NAME, public, pg_catalog;

UPDATE config_form_tableview SET alias = 'Link' WHERE columnname = 'link' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Layout id' WHERE columnname = 'layout_id' AND objectname = 'config_form_fields';
UPDATE config_form_tableview SET alias = 'Layout name' WHERE columnname = 'layout_name' AND objectname = 'config_form_fields';
UPDATE config_form_tableview SET alias = 'Layout order' WHERE columnname = 'layout_order' AND objectname = 'config_form_fields';
UPDATE config_form_tableview SET alias = 'Date' WHERE columnname = 'date' AND objectname = 'doc';
UPDATE config_form_tableview SET alias = 'Doc type' WHERE columnname = 'doc_type' AND objectname = 'doc';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'doc';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'doc';
UPDATE config_form_tableview SET alias = 'Path' WHERE columnname = 'path' AND objectname = 'doc';
UPDATE config_form_tableview SET alias = 'Tstamp' WHERE columnname = 'tstamp' AND objectname = 'doc';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'doc';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_controls';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_junction';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_pump';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 'dscenario_results';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'dscenario_results';
UPDATE config_form_tableview SET alias = 'Dscenario type' WHERE columnname = 'dscenario_type' AND objectname = 'dscenario_results';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 'dscenario_results';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_results';
UPDATE config_form_tableview SET alias = 'Log' WHERE columnname = 'log' AND objectname = 'dscenario_results';
UPDATE config_form_tableview SET alias = 'Name' WHERE columnname = 'name' AND objectname = 'dscenario_results';
UPDATE config_form_tableview SET alias = 'Parent id' WHERE columnname = 'parent_id' AND objectname = 'dscenario_results';
UPDATE config_form_tableview SET alias = 'Buildercat id' WHERE columnname = 'buildercat_id' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Builtdate' WHERE columnname = 'builtdate' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Category type' WHERE columnname = 'category_type' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Code' WHERE columnname = 'code' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Comment' WHERE columnname = 'comment' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Element id' WHERE columnname = 'element_id' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Elementcat id' WHERE columnname = 'elementcat_id' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Enddate' WHERE columnname = 'enddate' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Feature type' WHERE columnname = 'feature_type' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Fluid type' WHERE columnname = 'fluid_type' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Function type' WHERE columnname = 'function_type' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Inventory' WHERE columnname = 'inventory' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Label rotation' WHERE columnname = 'label_rotation' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Label x' WHERE columnname = 'label_x' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Label y' WHERE columnname = 'label_y' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Link' WHERE columnname = 'link' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Location type' WHERE columnname = 'location_type' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Num elements' WHERE columnname = 'num_elements' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Ownercat id' WHERE columnname = 'ownercat_id' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Publish' WHERE columnname = 'publish' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Rotation' WHERE columnname = 'rotation' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Serial number' WHERE columnname = 'serial_number' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'State type' WHERE columnname = 'state_type' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'The geom' WHERE columnname = 'the_geom' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Tstamp' WHERE columnname = 'tstamp' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Undelete' WHERE columnname = 'undelete' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Verified' WHERE columnname = 'verified' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Workcat id' WHERE columnname = 'workcat_id' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Workcat id end' WHERE columnname = 'workcat_id_end' AND objectname = 'element';
UPDATE config_form_tableview SET alias = 'Addparam' WHERE columnname = 'addparam' AND objectname = 'epa_results';
UPDATE config_form_tableview SET alias = 'Export options' WHERE columnname = 'export_options' AND objectname = 'epa_results';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'epa_results';
UPDATE config_form_tableview SET alias = 'Inp options' WHERE columnname = 'inp_options' AND objectname = 'epa_results';
UPDATE config_form_tableview SET alias = 'Network stats' WHERE columnname = 'network_stats' AND objectname = 'epa_results';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Atlas id' WHERE columnname = 'atlas_id' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Gexpenses' WHERE columnname = 'gexpenses' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Name' WHERE columnname = 'name' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Other' WHERE columnname = 'other' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Priority' WHERE columnname = 'priority' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Psector id' WHERE columnname = 'psector_id' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Psector type' WHERE columnname = 'psector_type' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Rotation' WHERE columnname = 'rotation' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Scale' WHERE columnname = 'scale' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Sector id' WHERE columnname = 'sector_id' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Text1' WHERE columnname = 'text1' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Text2' WHERE columnname = 'text2' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'The geom' WHERE columnname = 'the_geom' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Vat' WHERE columnname = 'vat' AND objectname = 'plan_psector';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 'plan_psector_x_arc';
UPDATE config_form_tableview SET alias = 'Addparam' WHERE columnname = 'addparam' AND objectname = 'plan_psector_x_arc';
UPDATE config_form_tableview SET alias = 'Arc id' WHERE columnname = 'arc_id' AND objectname = 'plan_psector_x_arc';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'plan_psector_x_arc';
UPDATE config_form_tableview SET alias = 'Doable' WHERE columnname = 'doable' AND objectname = 'plan_psector_x_arc';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'plan_psector_x_arc';
UPDATE config_form_tableview SET alias = 'Insert tstamp' WHERE columnname = 'insert_tstamp' AND objectname = 'plan_psector_x_arc';
UPDATE config_form_tableview SET alias = 'Insert user' WHERE columnname = 'insert_user' AND objectname = 'plan_psector_x_arc';
UPDATE config_form_tableview SET alias = 'Psector id' WHERE columnname = 'psector_id' AND objectname = 'plan_psector_x_arc';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'plan_psector_x_arc';
UPDATE config_form_tableview SET alias = ' link geom ' WHERE columnname = '_link_geom_' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = ' userdefined geom ' WHERE columnname = '_userdefined_geom_' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Arc id' WHERE columnname = 'arc_id' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Connec id' WHERE columnname = 'connec_id' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Doable' WHERE columnname = 'doable' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Insert tstamp' WHERE columnname = 'insert_tstamp' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Insert user' WHERE columnname = 'insert_user' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Link id' WHERE columnname = 'link_id' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Psector id' WHERE columnname = 'psector_id' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 'plan_psector_x_node';
UPDATE config_form_tableview SET alias = 'Addparam' WHERE columnname = 'addparam' AND objectname = 'plan_psector_x_node';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'plan_psector_x_node';
UPDATE config_form_tableview SET alias = 'Doable' WHERE columnname = 'doable' AND objectname = 'plan_psector_x_node';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'plan_psector_x_node';
UPDATE config_form_tableview SET alias = 'Insert tstamp' WHERE columnname = 'insert_tstamp' AND objectname = 'plan_psector_x_node';
UPDATE config_form_tableview SET alias = 'Insert user' WHERE columnname = 'insert_user' AND objectname = 'plan_psector_x_node';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'plan_psector_x_node';
UPDATE config_form_tableview SET alias = 'Psector id' WHERE columnname = 'psector_id' AND objectname = 'plan_psector_x_node';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'plan_psector_x_node';
UPDATE config_form_tableview SET alias = 'Arc id' WHERE columnname = 'arc_id' AND objectname = 'tbl_doc_x_arc';
UPDATE config_form_tableview SET alias = 'Date' WHERE columnname = 'date' AND objectname = 'tbl_doc_x_arc';
UPDATE config_form_tableview SET alias = 'Doc id' WHERE columnname = 'doc_id' AND objectname = 'tbl_doc_x_arc';
UPDATE config_form_tableview SET alias = 'Doc type' WHERE columnname = 'doc_type' AND objectname = 'tbl_doc_x_arc';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'tbl_doc_x_arc';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'tbl_doc_x_arc';
UPDATE config_form_tableview SET alias = 'Path' WHERE columnname = 'path' AND objectname = 'tbl_doc_x_arc';
UPDATE config_form_tableview SET alias = 'Sys id' WHERE columnname = 'sys_id' AND objectname = 'tbl_doc_x_arc';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'tbl_doc_x_arc';
UPDATE config_form_tableview SET alias = 'Connec id' WHERE columnname = 'connec_id' AND objectname = 'tbl_doc_x_connec';
UPDATE config_form_tableview SET alias = 'Date' WHERE columnname = 'date' AND objectname = 'tbl_doc_x_connec';
UPDATE config_form_tableview SET alias = 'Doc id' WHERE columnname = 'doc_id' AND objectname = 'tbl_doc_x_connec';
UPDATE config_form_tableview SET alias = 'Doc type' WHERE columnname = 'doc_type' AND objectname = 'tbl_doc_x_connec';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'tbl_doc_x_connec';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'tbl_doc_x_connec';
UPDATE config_form_tableview SET alias = 'Path' WHERE columnname = 'path' AND objectname = 'tbl_doc_x_connec';
UPDATE config_form_tableview SET alias = 'Sys id' WHERE columnname = 'sys_id' AND objectname = 'tbl_doc_x_connec';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'tbl_doc_x_connec';
UPDATE config_form_tableview SET alias = 'Date' WHERE columnname = 'date' AND objectname = 'tbl_doc_x_link';
UPDATE config_form_tableview SET alias = 'Doc id' WHERE columnname = 'doc_id' AND objectname = 'tbl_doc_x_link';
UPDATE config_form_tableview SET alias = 'Doc type' WHERE columnname = 'doc_type' AND objectname = 'tbl_doc_x_link';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'tbl_doc_x_link';
UPDATE config_form_tableview SET alias = 'Link id' WHERE columnname = 'link_id' AND objectname = 'tbl_doc_x_link';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'tbl_doc_x_link';
UPDATE config_form_tableview SET alias = 'Path' WHERE columnname = 'path' AND objectname = 'tbl_doc_x_link';
UPDATE config_form_tableview SET alias = 'Sys id' WHERE columnname = 'sys_id' AND objectname = 'tbl_doc_x_link';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'tbl_doc_x_link';
UPDATE config_form_tableview SET alias = 'Date' WHERE columnname = 'date' AND objectname = 'tbl_doc_x_node';
UPDATE config_form_tableview SET alias = 'Doc id' WHERE columnname = 'doc_id' AND objectname = 'tbl_doc_x_node';
UPDATE config_form_tableview SET alias = 'Doc type' WHERE columnname = 'doc_type' AND objectname = 'tbl_doc_x_node';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'tbl_doc_x_node';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'tbl_doc_x_node';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'tbl_doc_x_node';
UPDATE config_form_tableview SET alias = 'Path' WHERE columnname = 'path' AND objectname = 'tbl_doc_x_node';
UPDATE config_form_tableview SET alias = 'Sys id' WHERE columnname = 'sys_id' AND objectname = 'tbl_doc_x_node';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'tbl_doc_x_node';
UPDATE config_form_tableview SET alias = 'Arc id' WHERE columnname = 'arc_id' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Builtdate' WHERE columnname = 'builtdate' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Comment' WHERE columnname = 'comment' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Element id' WHERE columnname = 'element_id' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Element type' WHERE columnname = 'element_type' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Elementcat id' WHERE columnname = 'elementcat_id' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Enddate' WHERE columnname = 'enddate' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Epa type' WHERE columnname = 'epa_type' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Feature class' WHERE columnname = 'feature_class' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Inventory' WHERE columnname = 'inventory' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Location type' WHERE columnname = 'location_type' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Num elements' WHERE columnname = 'num_elements' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Publish' WHERE columnname = 'publish' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'State type' WHERE columnname = 'state_type' AND objectname = 'tbl_element_x_arc';
UPDATE config_form_tableview SET alias = 'Builtdate' WHERE columnname = 'builtdate' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Comment' WHERE columnname = 'comment' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Connec id' WHERE columnname = 'connec_id' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Element id' WHERE columnname = 'element_id' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Element type' WHERE columnname = 'element_type' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Elementcat id' WHERE columnname = 'elementcat_id' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Enddate' WHERE columnname = 'enddate' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Epa type' WHERE columnname = 'epa_type' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Feature class' WHERE columnname = 'feature_class' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Inventory' WHERE columnname = 'inventory' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Link' WHERE columnname = 'link' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Location type' WHERE columnname = 'location_type' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Num elements' WHERE columnname = 'num_elements' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Publish' WHERE columnname = 'publish' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'State type' WHERE columnname = 'state_type' AND objectname = 'tbl_element_x_connec';
UPDATE config_form_tableview SET alias = 'Builtdate' WHERE columnname = 'builtdate' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Comment' WHERE columnname = 'comment' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Element id' WHERE columnname = 'element_id' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Element type' WHERE columnname = 'element_type' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Elementcat id' WHERE columnname = 'elementcat_id' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Enddate' WHERE columnname = 'enddate' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Epa type' WHERE columnname = 'epa_type' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Feature class' WHERE columnname = 'feature_class' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Inventory' WHERE columnname = 'inventory' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Link' WHERE columnname = 'link' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Link id' WHERE columnname = 'link_id' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Location type' WHERE columnname = 'location_type' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Num elements' WHERE columnname = 'num_elements' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Publish' WHERE columnname = 'publish' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'State type' WHERE columnname = 'state_type' AND objectname = 'tbl_element_x_link';
UPDATE config_form_tableview SET alias = 'Builtdate' WHERE columnname = 'builtdate' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Comment' WHERE columnname = 'comment' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Element id' WHERE columnname = 'element_id' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Element type' WHERE columnname = 'element_type' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Elementcat id' WHERE columnname = 'elementcat_id' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Enddate' WHERE columnname = 'enddate' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Epa type' WHERE columnname = 'epa_type' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Feature class' WHERE columnname = 'feature_class' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Inventory' WHERE columnname = 'inventory' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Link' WHERE columnname = 'link' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Location type' WHERE columnname = 'location_type' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Num elements' WHERE columnname = 'num_elements' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Publish' WHERE columnname = 'publish' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'State type' WHERE columnname = 'state_type' AND objectname = 'tbl_element_x_node';
UPDATE config_form_tableview SET alias = 'Curve id' WHERE columnname = 'curve_id' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'Dscenario id' WHERE columnname = 'dscenario_id' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'Element id' WHERE columnname = 'element_id' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'Status' WHERE columnname = 'status' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'The geom' WHERE columnname = 'the_geom' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'Connec ccode' WHERE columnname = 'connec_customer_code' AND objectname = 'tbl_hydrometer';
UPDATE config_form_tableview SET alias = 'Sys connec id' WHERE columnname = 'connec_id' AND objectname = 'tbl_hydrometer';
UPDATE config_form_tableview SET alias = 'Exploitation' WHERE columnname = 'expl_id' AND objectname = 'tbl_hydrometer';
UPDATE config_form_tableview SET alias = 'Hydro ccode' WHERE columnname = 'hydrometer_customer_code' AND objectname = 'tbl_hydrometer';
UPDATE config_form_tableview SET alias = 'Sys hydrometer id' WHERE columnname = 'hydrometer_id' AND objectname = 'tbl_hydrometer';
UPDATE config_form_tableview SET alias = 'Link' WHERE columnname = 'hydrometer_link' AND objectname = 'tbl_hydrometer';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'tbl_hydrometer';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 'tbl_nvo_mng_controls';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'tbl_nvo_mng_controls';
UPDATE config_form_tableview SET alias = 'Sector id' WHERE columnname = 'sector_id' AND objectname = 'tbl_nvo_mng_controls';
UPDATE config_form_tableview SET alias = 'Text' WHERE columnname = 'text' AND objectname = 'tbl_nvo_mng_controls';
UPDATE config_form_tableview SET alias = 'Curve type' WHERE columnname = 'curve_type' AND objectname = 'tbl_nvo_mng_curves';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'tbl_nvo_mng_curves';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 'tbl_nvo_mng_curves';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'tbl_nvo_mng_curves';
UPDATE config_form_tableview SET alias = 'Log' WHERE columnname = 'log' AND objectname = 'tbl_nvo_mng_curves';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 'tbl_nvo_mng_patterns';
UPDATE config_form_tableview SET alias = 'Log' WHERE columnname = 'log' AND objectname = 'tbl_nvo_mng_patterns';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'tbl_nvo_mng_patterns';
UPDATE config_form_tableview SET alias = 'Pattern id' WHERE columnname = 'pattern_id' AND objectname = 'tbl_nvo_mng_patterns';
UPDATE config_form_tableview SET alias = 'Tscode' WHERE columnname = 'tscode' AND objectname = 'tbl_nvo_mng_patterns';
UPDATE config_form_tableview SET alias = 'Tsparameters' WHERE columnname = 'tsparameters' AND objectname = 'tbl_nvo_mng_patterns';
UPDATE config_form_tableview SET alias = 'Arc id' WHERE columnname = 'arc_id' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Catalog' WHERE columnname = 'catalog' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Feature code' WHERE columnname = 'feature_code' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Feature id' WHERE columnname = 'feature_id' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Feature state' WHERE columnname = 'feature_state' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Featurecat id' WHERE columnname = 'featurecat_id' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Rid' WHERE columnname = 'rid' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Sys id' WHERE columnname = 'sys_id' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Sys table id' WHERE columnname = 'sys_table_id' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Sys type' WHERE columnname = 'sys_type' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'X' WHERE columnname = 'x' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Y' WHERE columnname = 'y' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Sys id' WHERE columnname = 'sys_id' AND objectname = 'tbl_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Sys id' WHERE columnname = 'sys_id' AND objectname = 'tbl_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Sys id' WHERE columnname = 'sys_id' AND objectname = 'tbl_visit_x_node';
UPDATE config_form_tableview SET alias = 'Config' WHERE columnname = 'config' AND objectname = 'tbl_workspace_manager';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'tbl_workspace_manager';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'tbl_workspace_manager';
UPDATE config_form_tableview SET alias = 'Name' WHERE columnname = 'name' AND objectname = 'tbl_workspace_manager';
UPDATE config_form_tableview SET alias = 'Private' WHERE columnname = 'private' AND objectname = 'tbl_workspace_manager';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Arc id' WHERE columnname = 'arc_id' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Connec id' WHERE columnname = 'connec_id' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Doable' WHERE columnname = 'doable' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Insert tstamp' WHERE columnname = 'insert_tstamp' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Insert user' WHERE columnname = 'insert_user' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Link id' WHERE columnname = 'link_id' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Psector id' WHERE columnname = 'psector_id' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Rank' WHERE columnname = 'rank' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'v_edit_plan_psector_x_connec';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'v_edit_plan_psector_x_other';
UPDATE config_form_tableview SET alias = 'Psector id' WHERE columnname = 'psector_id' AND objectname = 'v_edit_plan_psector_x_other';
UPDATE config_form_tableview SET alias = 'Annotation' WHERE columnname = 'annotation' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Budget' WHERE columnname = 'budget' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Cost' WHERE columnname = 'cost' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Cost unit' WHERE columnname = 'cost_unit' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Elev' WHERE columnname = 'elev' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Epa type' WHERE columnname = 'epa_type' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Units' WHERE columnname = 'measurement' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Node type' WHERE columnname = 'node_type' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Nodecat id' WHERE columnname = 'nodecat_id' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Sector id' WHERE columnname = 'sector_id' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'The geom' WHERE columnname = 'the_geom' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Top elev' WHERE columnname = 'top_elev' AND objectname = 'v_plan_node';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_price_compost';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'v_price_compost';
UPDATE config_form_tableview SET alias = 'Price' WHERE columnname = 'price' AND objectname = 'v_price_compost';
UPDATE config_form_tableview SET alias = 'Unit' WHERE columnname = 'unit' AND objectname = 'v_price_compost';
UPDATE config_form_tableview SET alias = 'Address1' WHERE columnname = 'address1' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Address2' WHERE columnname = 'address2' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Address2 1' WHERE columnname = 'address2_1' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Address2 2' WHERE columnname = 'address2_2' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Address2 3' WHERE columnname = 'address2_3' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Address3' WHERE columnname = 'address3' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Catalog id' WHERE columnname = 'catalog_id' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Category id' WHERE columnname = 'category_id' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Connec customer code' WHERE columnname = 'connec_customer_code' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Connec id' WHERE columnname = 'connec_id' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Crm number' WHERE columnname = 'crm_number' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Customer name' WHERE columnname = 'customer_name' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'End date' WHERE columnname = 'end_date' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Expl name' WHERE columnname = 'expl_name' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Hydro man date' WHERE columnname = 'hydro_man_date' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Hydro number' WHERE columnname = 'hydro_number' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Hydrometer customer code' WHERE columnname = 'hydrometer_customer_code' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Hydrometer id' WHERE columnname = 'hydrometer_id' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Hydrometer link' WHERE columnname = 'hydrometer_link' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'M3 volume' WHERE columnname = 'm3_volume' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Muni name' WHERE columnname = 'muni_name' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Plot code' WHERE columnname = 'plot_code' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Priority id' WHERE columnname = 'priority_id' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Start date' WHERE columnname = 'start_date' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Update date' WHERE columnname = 'update_date' AND objectname = 'v_rtc_hydrometer';
UPDATE config_form_tableview SET alias = 'Connec id' WHERE columnname = 'connec_id' AND objectname = 'v_rtc_hydrometer_x_connec';
UPDATE config_form_tableview SET alias = 'N hydrometer' WHERE columnname = 'n_hydrometer' AND objectname = 'v_rtc_hydrometer_x_connec';
UPDATE config_form_tableview SET alias = 'Date' WHERE columnname = 'date' AND objectname = 'v_ui_doc';
UPDATE config_form_tableview SET alias = 'Doc type' WHERE columnname = 'doc_type' AND objectname = 'v_ui_doc';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'v_ui_doc';
UPDATE config_form_tableview SET alias = 'Name' WHERE columnname = 'name' AND objectname = 'v_ui_doc';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'v_ui_doc';
UPDATE config_form_tableview SET alias = 'Path' WHERE columnname = 'path' AND objectname = 'v_ui_doc';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'v_ui_doc';
UPDATE config_form_tableview SET alias = 'Anl cause' WHERE columnname = 'anl_cause' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Anl descript' WHERE columnname = 'anl_descript' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Anl tstamp' WHERE columnname = 'anl_tstamp' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Anl user' WHERE columnname = 'anl_user' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Connec id' WHERE columnname = 'connec_id' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'End date' WHERE columnname = 'end_date' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Exec appropiate' WHERE columnname = 'exec_appropiate' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Exec descript' WHERE columnname = 'exec_descript' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Exec end' WHERE columnname = 'exec_end' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Exec start' WHERE columnname = 'exec_start' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Exec user' WHERE columnname = 'exec_user' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Forecast end' WHERE columnname = 'forecast_end' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Forecast start' WHERE columnname = 'forecast_start' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Hydrometer id' WHERE columnname = 'hydrometer_id' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Mincut class' WHERE columnname = 'mincut_class' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Mincut state' WHERE columnname = 'mincut_state' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Mincut type' WHERE columnname = 'mincut_type' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Received date' WHERE columnname = 'received_date' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Result id' WHERE columnname = 'result_id' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Start date' WHERE columnname = 'start_date' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Work order' WHERE columnname = 'work_order' AND objectname = 'v_ui_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Code' WHERE columnname = 'code' AND objectname = 'v_ui_node_x_relations';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'v_ui_node_x_relations';
UPDATE config_form_tableview SET alias = 'Nodecat id' WHERE columnname = 'nodecat_id' AND objectname = 'v_ui_node_x_relations';
UPDATE config_form_tableview SET alias = 'Nodetype id' WHERE columnname = 'nodetype_id' AND objectname = 'v_ui_node_x_relations';
UPDATE config_form_tableview SET alias = 'Parent id' WHERE columnname = 'parent_id' AND objectname = 'v_ui_node_x_relations';
UPDATE config_form_tableview SET alias = 'Rid' WHERE columnname = 'rid' AND objectname = 'v_ui_node_x_relations';
UPDATE config_form_tableview SET alias = 'Sys type' WHERE columnname = 'sys_type' AND objectname = 'v_ui_node_x_relations';
UPDATE config_form_tableview SET alias = 'Cur user' WHERE columnname = 'cur_user' AND objectname = 'v_ui_om_result_cat';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_ui_om_result_cat';
UPDATE config_form_tableview SET alias = 'Name' WHERE columnname = 'name' AND objectname = 'v_ui_om_result_cat';
UPDATE config_form_tableview SET alias = 'Network price coeff' WHERE columnname = 'network_price_coeff' AND objectname = 'v_ui_om_result_cat';
UPDATE config_form_tableview SET alias = 'Pricecat id' WHERE columnname = 'pricecat_id' AND objectname = 'v_ui_om_result_cat';
UPDATE config_form_tableview SET alias = 'Result id' WHERE columnname = 'result_id' AND objectname = 'v_ui_om_result_cat';
UPDATE config_form_tableview SET alias = 'Result type' WHERE columnname = 'result_type' AND objectname = 'v_ui_om_result_cat';
UPDATE config_form_tableview SET alias = 'Tstamp' WHERE columnname = 'tstamp' AND objectname = 'v_ui_om_result_cat';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_ui_om_visit';
UPDATE config_form_tableview SET alias = 'Enddate' WHERE columnname = 'enddate' AND objectname = 'v_ui_om_visit';
UPDATE config_form_tableview SET alias = 'Exploitation' WHERE columnname = 'exploitation' AND objectname = 'v_ui_om_visit';
UPDATE config_form_tableview SET alias = 'Ext code' WHERE columnname = 'ext_code' AND objectname = 'v_ui_om_visit';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'v_ui_om_visit';
UPDATE config_form_tableview SET alias = 'Is done' WHERE columnname = 'is_done' AND objectname = 'v_ui_om_visit';
UPDATE config_form_tableview SET alias = 'Startdate' WHERE columnname = 'startdate' AND objectname = 'v_ui_om_visit';
UPDATE config_form_tableview SET alias = 'The geom' WHERE columnname = 'the_geom' AND objectname = 'v_ui_om_visit';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'v_ui_om_visit';
UPDATE config_form_tableview SET alias = 'Visit catalog' WHERE columnname = 'visit_catalog' AND objectname = 'v_ui_om_visit';
UPDATE config_form_tableview SET alias = 'Webclient id' WHERE columnname = 'webclient_id' AND objectname = 'v_ui_om_visit';
UPDATE config_form_tableview SET alias = 'Arc id' WHERE columnname = 'arc_id' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Code' WHERE columnname = 'code' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Compass' WHERE columnname = 'compass' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Document' WHERE columnname = 'document' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Event code' WHERE columnname = 'event_code' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Event id' WHERE columnname = 'event_id' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Feature type' WHERE columnname = 'feature_type' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Form type' WHERE columnname = 'form_type' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Gallery' WHERE columnname = 'gallery' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Is done' WHERE columnname = 'is_done' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Parameter id' WHERE columnname = 'parameter_id' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Parameter type' WHERE columnname = 'parameter_type' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Tstamp' WHERE columnname = 'tstamp' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Value' WHERE columnname = 'value' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Visit end' WHERE columnname = 'visit_end' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Visit id' WHERE columnname = 'visit_id' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Visit start' WHERE columnname = 'visit_start' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Visitcat id' WHERE columnname = 'visitcat_id' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Xcoord' WHERE columnname = 'xcoord' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Ycoord' WHERE columnname = 'ycoord' AND objectname = 'v_ui_om_visit_x_arc';
UPDATE config_form_tableview SET alias = 'Code' WHERE columnname = 'code' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Compass' WHERE columnname = 'compass' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Connec id' WHERE columnname = 'connec_id' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Document' WHERE columnname = 'document' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Event code' WHERE columnname = 'event_code' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Event id' WHERE columnname = 'event_id' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Feature type' WHERE columnname = 'feature_type' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Form type' WHERE columnname = 'form_type' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Gallery' WHERE columnname = 'gallery' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Is done' WHERE columnname = 'is_done' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Parameter id' WHERE columnname = 'parameter_id' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Parameter type' WHERE columnname = 'parameter_type' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Tstamp' WHERE columnname = 'tstamp' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Value' WHERE columnname = 'value' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Visit end' WHERE columnname = 'visit_end' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Visit id' WHERE columnname = 'visit_id' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Visit start' WHERE columnname = 'visit_start' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Visitcat id' WHERE columnname = 'visitcat_id' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Xcoord' WHERE columnname = 'xcoord' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Ycoord' WHERE columnname = 'ycoord' AND objectname = 'v_ui_om_visit_x_connec';
UPDATE config_form_tableview SET alias = 'Compass' WHERE columnname = 'compass' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Document' WHERE columnname = 'document' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Event code' WHERE columnname = 'event_code' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Event id' WHERE columnname = 'event_id' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Ext code' WHERE columnname = 'ext_code' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Feature type' WHERE columnname = 'feature_type' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Form type' WHERE columnname = 'form_type' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Gallery' WHERE columnname = 'gallery' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Gully id' WHERE columnname = 'gully_id' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Is done' WHERE columnname = 'is_done' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Parameter id' WHERE columnname = 'parameter_id' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Parameter type' WHERE columnname = 'parameter_type' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Tstamp' WHERE columnname = 'tstamp' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Value' WHERE columnname = 'value' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Visit end' WHERE columnname = 'visit_end' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Visit id' WHERE columnname = 'visit_id' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Visit start' WHERE columnname = 'visit_start' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Visitcat id' WHERE columnname = 'visitcat_id' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Xcoord' WHERE columnname = 'xcoord' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Ycoord' WHERE columnname = 'ycoord' AND objectname = 'v_ui_om_visit_x_gully';
UPDATE config_form_tableview SET alias = 'Code' WHERE columnname = 'code' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Compass' WHERE columnname = 'compass' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Document' WHERE columnname = 'document' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Event code' WHERE columnname = 'event_code' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Event id' WHERE columnname = 'event_id' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Feature type' WHERE columnname = 'feature_type' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Form type' WHERE columnname = 'form_type' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Gallery' WHERE columnname = 'gallery' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Is done' WHERE columnname = 'is_done' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Parameter id' WHERE columnname = 'parameter_id' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Parameter type' WHERE columnname = 'parameter_type' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Tstamp' WHERE columnname = 'tstamp' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Value' WHERE columnname = 'value' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Visit end' WHERE columnname = 'visit_end' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Visit id' WHERE columnname = 'visit_id' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Visit start' WHERE columnname = 'visit_start' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Visitcat id' WHERE columnname = 'visitcat_id' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Xcoord' WHERE columnname = 'xcoord' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Ycoord' WHERE columnname = 'ycoord' AND objectname = 'v_ui_om_visit_x_node';
UPDATE config_form_tableview SET alias = 'Arc id' WHERE columnname = 'arc_id' AND objectname = 'v_ui_om_visitman_x_arc';
UPDATE config_form_tableview SET alias = 'Code' WHERE columnname = 'code' AND objectname = 'v_ui_om_visitman_x_arc';
UPDATE config_form_tableview SET alias = 'Feature type' WHERE columnname = 'feature_type' AND objectname = 'v_ui_om_visitman_x_arc';
UPDATE config_form_tableview SET alias = 'Form type' WHERE columnname = 'form_type' AND objectname = 'v_ui_om_visitman_x_arc';
UPDATE config_form_tableview SET alias = 'Is done' WHERE columnname = 'is_done' AND objectname = 'v_ui_om_visitman_x_arc';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'v_ui_om_visitman_x_arc';
UPDATE config_form_tableview SET alias = 'Visit end' WHERE columnname = 'visit_end' AND objectname = 'v_ui_om_visitman_x_arc';
UPDATE config_form_tableview SET alias = 'Visit id' WHERE columnname = 'visit_id' AND objectname = 'v_ui_om_visitman_x_arc';
UPDATE config_form_tableview SET alias = 'Visit start' WHERE columnname = 'visit_start' AND objectname = 'v_ui_om_visitman_x_arc';
UPDATE config_form_tableview SET alias = 'Visitcat name' WHERE columnname = 'visitcat_name' AND objectname = 'v_ui_om_visitman_x_arc';
UPDATE config_form_tableview SET alias = 'Code' WHERE columnname = 'code' AND objectname = 'v_ui_om_visitman_x_connec';
UPDATE config_form_tableview SET alias = 'Connec id' WHERE columnname = 'connec_id' AND objectname = 'v_ui_om_visitman_x_connec';
UPDATE config_form_tableview SET alias = 'Feature type' WHERE columnname = 'feature_type' AND objectname = 'v_ui_om_visitman_x_connec';
UPDATE config_form_tableview SET alias = 'Form type' WHERE columnname = 'form_type' AND objectname = 'v_ui_om_visitman_x_connec';
UPDATE config_form_tableview SET alias = 'Is done' WHERE columnname = 'is_done' AND objectname = 'v_ui_om_visitman_x_connec';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'v_ui_om_visitman_x_connec';
UPDATE config_form_tableview SET alias = 'Visit end' WHERE columnname = 'visit_end' AND objectname = 'v_ui_om_visitman_x_connec';
UPDATE config_form_tableview SET alias = 'Visit id' WHERE columnname = 'visit_id' AND objectname = 'v_ui_om_visitman_x_connec';
UPDATE config_form_tableview SET alias = 'Visit start' WHERE columnname = 'visit_start' AND objectname = 'v_ui_om_visitman_x_connec';
UPDATE config_form_tableview SET alias = 'Visitcat name' WHERE columnname = 'visitcat_name' AND objectname = 'v_ui_om_visitman_x_connec';
UPDATE config_form_tableview SET alias = 'Code' WHERE columnname = 'code' AND objectname = 'v_ui_om_visitman_x_node';
UPDATE config_form_tableview SET alias = 'Feature type' WHERE columnname = 'feature_type' AND objectname = 'v_ui_om_visitman_x_node';
UPDATE config_form_tableview SET alias = 'Form type' WHERE columnname = 'form_type' AND objectname = 'v_ui_om_visitman_x_node';
UPDATE config_form_tableview SET alias = 'Is done' WHERE columnname = 'is_done' AND objectname = 'v_ui_om_visitman_x_node';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'v_ui_om_visitman_x_node';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'v_ui_om_visitman_x_node';
UPDATE config_form_tableview SET alias = 'Visit end' WHERE columnname = 'visit_end' AND objectname = 'v_ui_om_visitman_x_node';
UPDATE config_form_tableview SET alias = 'Visit id' WHERE columnname = 'visit_id' AND objectname = 'v_ui_om_visitman_x_node';
UPDATE config_form_tableview SET alias = 'Visit start' WHERE columnname = 'visit_start' AND objectname = 'v_ui_om_visitman_x_node';
UPDATE config_form_tableview SET alias = 'Visitcat name' WHERE columnname = 'visitcat_name' AND objectname = 'v_ui_om_visitman_x_node';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Archived' WHERE columnname = 'archived' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Creation date' WHERE columnname = 'creation_date' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Ext code' WHERE columnname = 'ext_code' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Name' WHERE columnname = 'name' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Other' WHERE columnname = 'other' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Parent id' WHERE columnname = 'parent_id' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Priority' WHERE columnname = 'priority' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Psector id' WHERE columnname = 'psector_id' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Psector type' WHERE columnname = 'psector_type' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Status' WHERE columnname = 'status' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Text1' WHERE columnname = 'text1' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Text2' WHERE columnname = 'text2' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Vat' WHERE columnname = 'vat' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Workcat id' WHERE columnname = 'workcat_id' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Workcat id plan' WHERE columnname = 'workcat_id_plan' AND objectname = 'v_ui_plan_psector';
UPDATE config_form_tableview SET alias = 'Addparam' WHERE columnname = 'addparam' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Cur user' WHERE columnname = 'cur_user' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Exec date' WHERE columnname = 'exec_date' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Export options' WHERE columnname = 'export_options' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Inp options' WHERE columnname = 'inp_options' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Iscorporate' WHERE columnname = 'iscorporate' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Network stats' WHERE columnname = 'network_stats' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Network type' WHERE columnname = 'network_type' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Result id' WHERE columnname = 'result_id' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Rpt stats' WHERE columnname = 'rpt_stats' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Sector id' WHERE columnname = 'sector_id' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Status' WHERE columnname = 'status' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Code' WHERE columnname = 'code' AND objectname = 'v_ui_workcat_x_feature';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 'v_ui_workcat_x_feature';
UPDATE config_form_tableview SET alias = 'Expl name' WHERE columnname = 'expl_name' AND objectname = 'v_ui_workcat_x_feature';
UPDATE config_form_tableview SET alias = 'Feature id' WHERE columnname = 'feature_id' AND objectname = 'v_ui_workcat_x_feature';
UPDATE config_form_tableview SET alias = 'Feature type' WHERE columnname = 'feature_type' AND objectname = 'v_ui_workcat_x_feature';
UPDATE config_form_tableview SET alias = 'Featurecat id' WHERE columnname = 'featurecat_id' AND objectname = 'v_ui_workcat_x_feature';
UPDATE config_form_tableview SET alias = 'Rid' WHERE columnname = 'rid' AND objectname = 'v_ui_workcat_x_feature';
UPDATE config_form_tableview SET alias = 'Workcat id' WHERE columnname = 'workcat_id' AND objectname = 'v_ui_workcat_x_feature';
UPDATE config_form_tableview SET alias = 'Code' WHERE columnname = 'code' AND objectname = 'v_ui_workcat_x_feature_end';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 'v_ui_workcat_x_feature_end';
UPDATE config_form_tableview SET alias = 'Expl name' WHERE columnname = 'expl_name' AND objectname = 'v_ui_workcat_x_feature_end';
UPDATE config_form_tableview SET alias = 'Feature id' WHERE columnname = 'feature_id' AND objectname = 'v_ui_workcat_x_feature_end';
UPDATE config_form_tableview SET alias = 'Feature type' WHERE columnname = 'feature_type' AND objectname = 'v_ui_workcat_x_feature_end';
UPDATE config_form_tableview SET alias = 'Featurecat id' WHERE columnname = 'featurecat_id' AND objectname = 'v_ui_workcat_x_feature_end';
UPDATE config_form_tableview SET alias = 'Rid' WHERE columnname = 'rid' AND objectname = 'v_ui_workcat_x_feature_end';
UPDATE config_form_tableview SET alias = 'Workcat id' WHERE columnname = 'workcat_id' AND objectname = 'v_ui_workcat_x_feature_end';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 've_inp_controls';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 've_inp_controls';
UPDATE config_form_tableview SET alias = 'Sector id' WHERE columnname = 'sector_id' AND objectname = 've_inp_controls';
UPDATE config_form_tableview SET alias = 'Text' WHERE columnname = 'text' AND objectname = 've_inp_controls';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 've_inp_curve';
UPDATE config_form_tableview SET alias = 'Curve type' WHERE columnname = 'curve_type' AND objectname = 've_inp_curve';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 've_inp_curve';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 've_inp_curve';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 've_inp_curve';
UPDATE config_form_tableview SET alias = 'Expl id' WHERE columnname = 'expl_id' AND objectname = 've_inp_pattern';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 've_inp_pattern';
UPDATE config_form_tableview SET alias = 'Pattern id' WHERE columnname = 'pattern_id' AND objectname = 've_inp_pattern';
UPDATE config_form_tableview SET alias = 'Pattern type' WHERE columnname = 'pattern_type' AND objectname = 've_inp_pattern';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 'cat_mat_roughness';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'cat_mat_roughness';
UPDATE config_form_tableview SET alias = 'End age' WHERE columnname = 'end_age' AND objectname = 'cat_mat_roughness';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'cat_mat_roughness';
UPDATE config_form_tableview SET alias = 'Init age' WHERE columnname = 'init_age' AND objectname = 'cat_mat_roughness';
UPDATE config_form_tableview SET alias = 'Matcat id' WHERE columnname = 'matcat_id' AND objectname = 'cat_mat_roughness';
UPDATE config_form_tableview SET alias = 'Period id' WHERE columnname = 'period_id' AND objectname = 'cat_mat_roughness';
UPDATE config_form_tableview SET alias = 'Roughness' WHERE columnname = 'roughness' AND objectname = 'cat_mat_roughness';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_additional';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_connec';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_demand';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_inlet';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_pipe';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_reservoir';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_rules';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_shortpipe';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_tank';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_valve';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_virtualpump';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'dscenario_virtualvalve';
UPDATE config_form_tableview SET alias = 'Demand' WHERE columnname = 'demand' AND objectname = 'inp_dscenario_demand';
UPDATE config_form_tableview SET alias = 'Demand type' WHERE columnname = 'demand_type' AND objectname = 'inp_dscenario_demand';
UPDATE config_form_tableview SET alias = 'Dscenario id' WHERE columnname = 'dscenario_id' AND objectname = 'inp_dscenario_demand';
UPDATE config_form_tableview SET alias = 'Feature id' WHERE columnname = 'feature_id' AND objectname = 'inp_dscenario_demand';
UPDATE config_form_tableview SET alias = 'Feature type' WHERE columnname = 'feature_type' AND objectname = 'inp_dscenario_demand';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'inp_dscenario_demand';
UPDATE config_form_tableview SET alias = 'Pattern id' WHERE columnname = 'pattern_id' AND objectname = 'inp_dscenario_demand';
UPDATE config_form_tableview SET alias = 'Source' WHERE columnname = 'source' AND objectname = 'inp_dscenario_demand';
UPDATE config_form_tableview SET alias = 'Curve id' WHERE columnname = 'curve_id' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Dscenario id' WHERE columnname = 'dscenario_id' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Effic curve id' WHERE columnname = 'effic_curve_id' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Energy pattern id' WHERE columnname = 'energy_pattern_id' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Energy price' WHERE columnname = 'energy_price' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Energyparam' WHERE columnname = 'energyparam' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Energyvalue' WHERE columnname = 'energyvalue' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Order id' WHERE columnname = 'order_id' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Pattern id' WHERE columnname = 'pattern_id' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Power' WHERE columnname = 'power' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Speed' WHERE columnname = 'speed' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Status' WHERE columnname = 'status' AND objectname = 'inp_dscenario_pump_additional';
UPDATE config_form_tableview SET alias = 'Curve id' WHERE columnname = 'curve_id' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Effic curve id' WHERE columnname = 'effic_curve_id' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Energy pattern id' WHERE columnname = 'energy_pattern_id' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Energy price' WHERE columnname = 'energy_price' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Energyparam' WHERE columnname = 'energyparam' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Energyvalue' WHERE columnname = 'energyvalue' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Order id' WHERE columnname = 'order_id' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Pattern id' WHERE columnname = 'pattern_id' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Power' WHERE columnname = 'power' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Speed' WHERE columnname = 'speed' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Status' WHERE columnname = 'status' AND objectname = 'inp_pump_additional';
UPDATE config_form_tableview SET alias = 'Netscenari id' WHERE columnname = 'netscenari_id' AND objectname = 'plan_netscenario_arc';
UPDATE config_form_tableview SET alias = 'Netscenari id' WHERE columnname = 'netscenari_id' AND objectname = 'plan_netscenario_connec';
UPDATE config_form_tableview SET alias = 'Netscenari id' WHERE columnname = 'netscenari_id' AND objectname = 'plan_netscenario_dma';
UPDATE config_form_tableview SET alias = 'Netscenari id' WHERE columnname = 'netscenari_id' AND objectname = 'plan_netscenario_node';
UPDATE config_form_tableview SET alias = 'Netscenari id' WHERE columnname = 'netscenari_id' AND objectname = 'plan_netscenario_valve';
UPDATE config_form_tableview SET alias = 'Effic curve id' WHERE columnname = 'effic_curve_id' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'Energy pattern id' WHERE columnname = 'energy_pattern_id' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'Energy price' WHERE columnname = 'energy_price' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'Pattern id' WHERE columnname = 'pattern_id' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'Power' WHERE columnname = 'power' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'Speed' WHERE columnname = 'speed' AND objectname = 'tbl_frelem_dsc_pump';
UPDATE config_form_tableview SET alias = 'Bulk coeff' WHERE columnname = 'bulk_coeff' AND objectname = 'tbl_frelem_dsc_shortpipe';
UPDATE config_form_tableview SET alias = 'Custom dint' WHERE columnname = 'custom_dint' AND objectname = 'tbl_frelem_dsc_shortpipe';
UPDATE config_form_tableview SET alias = 'Dscenario id' WHERE columnname = 'dscenario_id' AND objectname = 'tbl_frelem_dsc_shortpipe';
UPDATE config_form_tableview SET alias = 'Element id' WHERE columnname = 'element_id' AND objectname = 'tbl_frelem_dsc_shortpipe';
UPDATE config_form_tableview SET alias = 'Minorloss' WHERE columnname = 'minorloss' AND objectname = 'tbl_frelem_dsc_shortpipe';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'tbl_frelem_dsc_shortpipe';
UPDATE config_form_tableview SET alias = 'The geom' WHERE columnname = 'the_geom' AND objectname = 'tbl_frelem_dsc_shortpipe';
UPDATE config_form_tableview SET alias = 'Wall coeff' WHERE columnname = 'wall_coeff' AND objectname = 'tbl_frelem_dsc_shortpipe';
UPDATE config_form_tableview SET alias = 'Add settings' WHERE columnname = 'add_settings' AND objectname = 'tbl_frelem_dsc_valve';
UPDATE config_form_tableview SET alias = 'Curve id' WHERE columnname = 'curve_id' AND objectname = 'tbl_frelem_dsc_valve';
UPDATE config_form_tableview SET alias = 'Custom dint' WHERE columnname = 'custom_dint' AND objectname = 'tbl_frelem_dsc_valve';
UPDATE config_form_tableview SET alias = 'Dscenario id' WHERE columnname = 'dscenario_id' AND objectname = 'tbl_frelem_dsc_valve';
UPDATE config_form_tableview SET alias = 'Element id' WHERE columnname = 'element_id' AND objectname = 'tbl_frelem_dsc_valve';
UPDATE config_form_tableview SET alias = 'Init quality' WHERE columnname = 'init_quality' AND objectname = 'tbl_frelem_dsc_valve';
UPDATE config_form_tableview SET alias = 'Minorloss' WHERE columnname = 'minorloss' AND objectname = 'tbl_frelem_dsc_valve';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'tbl_frelem_dsc_valve';
UPDATE config_form_tableview SET alias = 'Setting' WHERE columnname = 'setting' AND objectname = 'tbl_frelem_dsc_valve';
UPDATE config_form_tableview SET alias = 'The geom' WHERE columnname = 'the_geom' AND objectname = 'tbl_frelem_dsc_valve';
UPDATE config_form_tableview SET alias = 'Valve type' WHERE columnname = 'valve_type' AND objectname = 'tbl_frelem_dsc_valve';
UPDATE config_form_tableview SET alias = 'Connec code' WHERE columnname = 'connec_code' AND objectname = 'tbl_mincut_hydro';
UPDATE config_form_tableview SET alias = 'Connec id' WHERE columnname = 'connec_id' AND objectname = 'tbl_mincut_hydro';
UPDATE config_form_tableview SET alias = 'Hydrometer customer code' WHERE columnname = 'hydrometer_customer_code' AND objectname = 'tbl_mincut_hydro';
UPDATE config_form_tableview SET alias = 'Hydrometer id' WHERE columnname = 'hydrometer_id' AND objectname = 'tbl_mincut_hydro';
UPDATE config_form_tableview SET alias = 'Anl cause' WHERE columnname = 'anl_cause' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Anl descript' WHERE columnname = 'anl_descript' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Anl feature id' WHERE columnname = 'anl_feature_id' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Anl feature type' WHERE columnname = 'anl_feature_type' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Anl the geom' WHERE columnname = 'anl_the_geom' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Anl tstamp' WHERE columnname = 'anl_tstamp' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Anl user' WHERE columnname = 'anl_user' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Assigned to' WHERE columnname = 'assigned_to' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Class' WHERE columnname = 'class' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Exec appropiate' WHERE columnname = 'exec_appropiate' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Exec depth' WHERE columnname = 'exec_depth' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Exec descript' WHERE columnname = 'exec_descript' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Exec end' WHERE columnname = 'exec_end' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Exec from plot' WHERE columnname = 'exec_from_plot' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Exec start' WHERE columnname = 'exec_start' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Exec the geom' WHERE columnname = 'exec_the_geom' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Exec user' WHERE columnname = 'exec_user' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Forecast end' WHERE columnname = 'forecast_end' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Forecast start' WHERE columnname = 'forecast_start' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Macroexpl id' WHERE columnname = 'macroexpl_id' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Mincut type' WHERE columnname = 'mincut_type' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Name' WHERE columnname = 'name' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Postcode' WHERE columnname = 'postcode' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Postnumber' WHERE columnname = 'postnumber' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Received date' WHERE columnname = 'received_date' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Streetaxis id' WHERE columnname = 'streetaxis_id' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Work order' WHERE columnname = 'work_order' AND objectname = 'tbl_mincut_manager';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 'tbl_nvo_mng_roughness';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'tbl_nvo_mng_roughness';
UPDATE config_form_tableview SET alias = 'End age' WHERE columnname = 'end_age' AND objectname = 'tbl_nvo_mng_roughness';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'tbl_nvo_mng_roughness';
UPDATE config_form_tableview SET alias = 'Init age' WHERE columnname = 'init_age' AND objectname = 'tbl_nvo_mng_roughness';
UPDATE config_form_tableview SET alias = 'Matcat id' WHERE columnname = 'matcat_id' AND objectname = 'tbl_nvo_mng_roughness';
UPDATE config_form_tableview SET alias = 'Period id' WHERE columnname = 'period_id' AND objectname = 'tbl_nvo_mng_roughness';
UPDATE config_form_tableview SET alias = 'Roughness' WHERE columnname = 'roughness' AND objectname = 'tbl_nvo_mng_roughness';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 'tbl_nvo_mng_rules';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'tbl_nvo_mng_rules';
UPDATE config_form_tableview SET alias = 'Sector id' WHERE columnname = 'sector_id' AND objectname = 'tbl_nvo_mng_rules';
UPDATE config_form_tableview SET alias = 'Text' WHERE columnname = 'text' AND objectname = 'tbl_nvo_mng_rules';
UPDATE config_form_tableview SET alias = 'Arc state' WHERE columnname = 'arc_state' AND objectname = 'tbl_relations';
UPDATE config_form_tableview SET alias = 'Connec code' WHERE columnname = 'connec_code' AND objectname = 'v_om_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Connec id' WHERE columnname = 'connec_id' AND objectname = 'v_om_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Hydrometer customer code' WHERE columnname = 'hydrometer_customer_code' AND objectname = 'v_om_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Hydrometer id' WHERE columnname = 'hydrometer_id' AND objectname = 'v_om_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'v_om_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Result id' WHERE columnname = 'result_id' AND objectname = 'v_om_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Work order' WHERE columnname = 'work_order' AND objectname = 'v_om_mincut_hydrometer';
UPDATE config_form_tableview SET alias = 'Date' WHERE columnname = 'date' AND objectname = 'v_ui_doc_x_gully';
UPDATE config_form_tableview SET alias = 'Doc id' WHERE columnname = 'doc_id' AND objectname = 'v_ui_doc_x_gully';
UPDATE config_form_tableview SET alias = 'Doc type' WHERE columnname = 'doc_type' AND objectname = 'v_ui_doc_x_gully';
UPDATE config_form_tableview SET alias = 'Gully id' WHERE columnname = 'gully_id' AND objectname = 'v_ui_doc_x_gully';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'v_ui_doc_x_gully';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'v_ui_doc_x_gully';
UPDATE config_form_tableview SET alias = 'Path' WHERE columnname = 'path' AND objectname = 'v_ui_doc_x_gully';
UPDATE config_form_tableview SET alias = 'User name' WHERE columnname = 'user_name' AND objectname = 'v_ui_doc_x_gully';
UPDATE config_form_tableview SET alias = 'Builtdate' WHERE columnname = 'builtdate' AND objectname = 'v_ui_element_x_gully';
UPDATE config_form_tableview SET alias = 'Comment' WHERE columnname = 'comment' AND objectname = 'v_ui_element_x_gully';
UPDATE config_form_tableview SET alias = 'Descript' WHERE columnname = 'descript' AND objectname = 'v_ui_element_x_gully';
UPDATE config_form_tableview SET alias = 'Element id' WHERE columnname = 'element_id' AND objectname = 'v_ui_element_x_gully';
UPDATE config_form_tableview SET alias = 'Elementcat id' WHERE columnname = 'elementcat_id' AND objectname = 'v_ui_element_x_gully';
UPDATE config_form_tableview SET alias = 'Enddate' WHERE columnname = 'enddate' AND objectname = 'v_ui_element_x_gully';
UPDATE config_form_tableview SET alias = 'Gully id' WHERE columnname = 'gully_id' AND objectname = 'v_ui_element_x_gully';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 'v_ui_element_x_gully';
UPDATE config_form_tableview SET alias = 'Num elements' WHERE columnname = 'num_elements' AND objectname = 'v_ui_element_x_gully';
UPDATE config_form_tableview SET alias = 'Observ' WHERE columnname = 'observ' AND objectname = 'v_ui_element_x_gully';
UPDATE config_form_tableview SET alias = 'State' WHERE columnname = 'state' AND objectname = 'v_ui_element_x_gully';
UPDATE config_form_tableview SET alias = 'Arccat id' WHERE columnname = 'arccat_id' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Depth' WHERE columnname = 'depth' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Downstream code' WHERE columnname = 'downstream_code' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Downstream depth' WHERE columnname = 'downstream_depth' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Downstream id' WHERE columnname = 'downstream_id' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Downstream type' WHERE columnname = 'downstream_type' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Feature code' WHERE columnname = 'feature_code' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Feature id' WHERE columnname = 'feature_id' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Featurecat id' WHERE columnname = 'featurecat_id' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Length' WHERE columnname = 'length' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Rid' WHERE columnname = 'rid' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Sys type' WHERE columnname = 'sys_type' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'X' WHERE columnname = 'x' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Y' WHERE columnname = 'y' AND objectname = 'v_ui_node_x_connection_downstream';
UPDATE config_form_tableview SET alias = 'Arccat id' WHERE columnname = 'arccat_id' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Depth' WHERE columnname = 'depth' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Feature code' WHERE columnname = 'feature_code' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Feature id' WHERE columnname = 'feature_id' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Featurecat id' WHERE columnname = 'featurecat_id' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Length' WHERE columnname = 'length' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Node id' WHERE columnname = 'node_id' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Rid' WHERE columnname = 'rid' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Sys type' WHERE columnname = 'sys_type' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Upstream code' WHERE columnname = 'upstream_code' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Upstream depth' WHERE columnname = 'upstream_depth' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Upstream id' WHERE columnname = 'upstream_id' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Upstream type' WHERE columnname = 'upstream_type' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'X' WHERE columnname = 'x' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Y' WHERE columnname = 'y' AND objectname = 'v_ui_node_x_connection_upstream';
UPDATE config_form_tableview SET alias = 'Dma id' WHERE columnname = 'dma_id' AND objectname = 'v_ui_rpt_cat_result';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 've_inp_pattern';
UPDATE config_form_tableview SET alias = 'Active' WHERE columnname = 'active' AND objectname = 've_inp_rules';
UPDATE config_form_tableview SET alias = 'Id' WHERE columnname = 'id' AND objectname = 've_inp_rules';
UPDATE config_form_tableview SET alias = 'Sector id' WHERE columnname = 'sector_id' AND objectname = 've_inp_rules';
UPDATE config_form_tableview SET alias = 'Text' WHERE columnname = 'text' AND objectname = 've_inp_rules';